force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Employee&#39;s email address</description>
    <inlineHelpText>Email address for Salesforce users will be set automatically.
If the employee is NOT a Salesforce user, please enter their email address here.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to the DIR Employee object creating a hierarchial relationship between an employee and his or her manager. Used in code to modify the role hierarchy and dynamically build teams</description>
    <inlineHelpText>Select the employee&#39;s manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Manages these Employees</relationshipLabel>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The office the user is associated to. Related fields are used on output documents</description>
    <inlineHelpText>The office to which the employee is associated.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Internal Employees</relationshipLabel>
    <relationshipName>Internal_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <description>Holds internal office location information</description>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ReceiptLogFormControllerTest.cls
@isTest
public class ReceiptLogFormControllerTest {
    static testmethod void testPkList(){
        ReceiptLogFormController.getBankLocation();
        ReceiptLogFormController.getPaymentTypes();
        ReceiptLogFormController.getDepositAccount();
        ReceiptLogFormController.getPaymentExchange();
        ReceiptLogFormController.getOfficeUnit();
    }
    
    static testmethod void getPayorAndDeputyName(){
        Account acc = new Account();
        acc.name = 'Test Account';
        acc.Bankruptcy_Status_Date__c = Date.today();
        insert acc;
        
        System.assertEquals(acc.name, ReceiptLogFormController.getPayorName(String.valueOf(acc.Id)));
        
        //If adding Senior Deputy in future
        /*
        Office__c o = new Office__c(
            Name = 'myOffice'
        );
        insert o;
        
        DIR_Employee__c ma = new DIR_Employee__c(
            User__c = UserInfo.getUserId(),
            Name = UserInfo.getName(),
            Email__c = 'testEmail@vertibatest.com'
        );
        insert ma; 
        
        DIR_Employee__c dir = new DIR_Employee__c(
            Manager__c = ma.Id,
            Office__c = o.Id,
            Name = UserInfo.getName(),
            User__c = UserInfo.getUserId()
        );
        insert dir;
        
        System.assertEquals(UserInfo.getName(), ReceiptLogFormController.getDeputyName(String.valueOf(dir.Id)));
		*/
        
    }
    
}