force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position the employee holds</description>
    <inlineHelpText>Select the position the employee holds</inlineHelpText>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Senior Deputy</fullName>
            </value>
            <value>
                <fullName>Deputy</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>CIU</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Registration_Services</fullName>
                <label>Registration Services</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office_Account__c/Office_Account__c.object-meta.xml
<CustomObject>
    <description>This object allows a cashier to view the details associated to a deposit into and office account so that they can monitor the historical transactions associated with a deposit account.</description>
    <label>Office Account</label>
    <nameField>
        <label>Office Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <description>Represents a receivable: an incoming payment, or an advice of incoming funds. [Encompasses the former Payment Log, Payment Group and Receipt objects to 1 single object.]</description>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RCT-{0000000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Deduction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deduction_Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Deduction amount if any</description>
    <label>Deduction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Deposit_Account__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Account__c</fullName>
    <description>Picklist for capturing the Deposit Account</description>
    <label>Deposit Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>108</fullName>
            </value>
            <value>
                <fullName>01-112</fullName>
            </value>
            <value>
                <fullName>04-112</fullName>
            </value>
            <value>
                <fullName>05-113</fullName>
            </value>
            <value>
                <fullName>06-114</fullName>
            </value>
            <value>
                <fullName>633-114</fullName>
            </value>
            <value>
                <fullName>07-119</fullName>
            </value>
            <value>
                <fullName>08-116</fullName>
            </value>
            <value>
                <fullName>09-117</fullName>
            </value>
            <value>
                <fullName>10-117</fullName>
            </value>
            <value>
                <fullName>11-119</fullName>
            </value>
            <value>
                <fullName>12-119</fullName>
            </value>
            <value>
                <fullName>13-113</fullName>
            </value>
            <value>
                <fullName>14-112</fullName>
            </value>
            <value>
                <fullName>15-116</fullName>
            </value>
            <value>
                <fullName>17-113</fullName>
            </value>
            <value>
                <fullName>18-113</fullName>
            </value>
            <value>
                <fullName>23-124</fullName>
            </value>
            <value>
                <fullName>32-117</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Office_Unit__c.field-meta.xml
<CustomField>
    <fullName>Office_Unit__c</fullName>
    <description>Picklist field that allows user to designate the Office Unit on the Payment record.</description>
    <label>Office Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCU 32</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>WCA 1</fullName>
            </value>
            <value>
                <fullName>WCA 4</fullName>
            </value>
            <value>
                <fullName>WCA 5</fullName>
            </value>
            <value>
                <fullName>WCA 6</fullName>
            </value>
            <value>
                <fullName>WCA 7</fullName>
            </value>
            <value>
                <fullName>WCA 8</fullName>
            </value>
            <value>
                <fullName>WCA 9</fullName>
            </value>
            <value>
                <fullName>WCA 10</fullName>
            </value>
            <value>
                <fullName>WCA 11</fullName>
            </value>
            <value>
                <fullName>WCA 12</fullName>
            </value>
            <value>
                <fullName>WCA 13</fullName>
            </value>
            <value>
                <fullName>WCA 14</fullName>
            </value>
            <value>
                <fullName>WCA 15</fullName>
            </value>
            <value>
                <fullName>WCA 17</fullName>
            </value>
            <value>
                <fullName>WCA 18</fullName>
            </value>
            <value>
                <fullName>WCA 23</fullName>
            </value>
            <value>
                <fullName>WCA 633</fullName>
            </value>
            <value>
                <fullName>RCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>Required field for capturing the payment amount</description>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent transaction that ends up being deposited or reversed with the bank.</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>WCA</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>PW</fullName>
            </value>
            <value>
                <fullName>CCU 32</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Office_Account__c.field-meta.xml
<CustomField>
    <fullName>Office_Account__c</fullName>
    <label>Office Account</label>
    <referenceTo>Office_Account__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Receipting_Cashier__c.field-meta.xml
<CustomField>
    <fullName>Receipting_Cashier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the internal employee that is the Receipting Cashier on the transaction.</description>
    <label>Receipting Cashier</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <inlineHelpText>Please use Transaction Status of Adjusted for adjustments made by the Sr. Deputy of Cashiering.</inlineHelpText>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deposited</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Adjusted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Sum__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Sum__c</fullName>
    <description>For deposits, this is the sum of all eligible RCTs. Populated on record creation by the recordDeposits_Controller apex class. If Transaction type is adjustment, this is populated by Transaction Flow by taking the deposit total and adding it here.</description>
    <inlineHelpText>Sum of all payments in this transaction.</inlineHelpText>
    <label>Transaction Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Defines what type of transaction is taking place.</description>
    <inlineHelpText>Set to Adjustment if submitting this transaction to modify the balance of the bank account for any reason other than a standard deposit.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DepositReceiptsController.cls
/*********************************************************************
Usage   : This class creates a Transaction from a list of Receipts.
            DepositReceiptsVFP calls this class.
*********************************************************************/

public class DepositReceiptsController {
    
    public List<Receipt__c> receiptList {get;set;}
    public Boolean showErrors {get;set;}
    
    public String[] ids {
        get {
            if (ids == null) {
                String s = ApexPages.currentPage().getParameters().get('ids');
                if (s != null) {
                    ids = s.split(',');
                } else {
                    ids = new String[] {};
                }
            }
            return ids;
        }
        set;
    }
    
    public String retURL {
        get{
            if(retURL == null){
                String s = ApexPages.currentPage().getParameters().get('retURL');
                if(s != null){
                    retURL = s;
                }
            }
            //return retURL;
            return '/a2r/o'; //hard coded Receipt list view - fix in Tier 2 - may need to update for PROD
        }
        set;
    }
    
    public DepositReceiptsController(){}
    
    public PageReference returnToList(){
        
        PageReference pr = new PageReference(retURL);
        pr.setRedirect(true);
        
        return pr;
    }
    
    
    public PageReference recordDeposits(){
        Id trnId;
        retURL = retURL;
        showErrors = false;
        receiptList = [SELECT Id, Name, Deposit_Account__c, Payment_Amount__c, Deduction_Amount__c, Office_Unit__c
                                            FROM Receipt__c
                                            WHERE Id IN :ids];
        
        List<Office_Account__c> officeAccountList = [SELECT Id, Name 
                                                        FROM Office_Account__c
                                                        WHERE Name = :receiptList[0].Deposit_Account__c];
        
        List<DIR_Employee__c> cashier = [SELECT Id, Position__c, User__c
                                            FROM DIR_Employee__c
                                            WHERE User__c = :UserInfo.getUserId()
                                                AND Position__c = 'Cashiering'
                                            LIMIT 1];
        
        Set<String> depositAccountNameSet = new Set<String>();
        Set<String> officeUnitNameSet = new Set<String>();
        
        for(Receipt__c rct : receiptList){ 
            if(rct.Deduction_Amount__c != null && rct.Deduction_Amount__c != 0.00){
                ApexPages.Message deducAmtErr = new ApexPages.Message(ApexPages.Severity.ERROR,'Error on '+ rct.Name +': Deduction amount cannot be deposited.');
                ApexPages.addMessage(deducAmtErr);
            }
            
            if(rct.Deposit_Account__c == '108'){ 
                ApexPages.Message depAccNeedErr = new ApexPages.Message(ApexPages.Severity.ERROR,'Error on '+ rct.Name +': Deposit account 108 need not be deposited.'); 
                ApexPages.addMessage(depAccNeedErr);
            }
            
            depositAccountNameSet.add(rct.Deposit_Account__c); 
            officeUnitNameSet.add(rct.Office_Unit__c);
            //sumOfReceipts += rct.Payment_Amount__c; //Payment_Amount__c rollups tackled in ReceiptTrigger and receiptMethods
        }
        
        if(depositAccountNameSet.size() != 1){
            ApexPages.Message depAccErr = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Deposit accounts should be same on each Receipt.');
            ApexPages.addMessage(depAccErr);
        }
        
        if(officeUnitNameSet.size() != 1){
            ApexPages.Message unitErr = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Business units should be same on each Receipt.');
            ApexPages.addMessage(unitErr);
        }
        
        if(cashier == null || cashier.isEmpty()){
            ApexPages.Message employeeErr = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Internal Employee must have a Cashiering position to deposit a payment.');
            ApexPages.addMessage(employeeErr);
        }
        
        if(officeAccountList.size() != 1){ //This error message should never show up
            ApexPages.Message offAccErr = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Only one office account should exist for a selected deposit account.');
            ApexPages.addMessage(offAccErr);
        }
        
        if(ApexPages.getMessages().size() == 0){
            
            Decimal transactionSum = 0.00;
            for(Receipt__c rct : receiptList){
                transactionSum += rct.Payment_Amount__c;
            }
            
            Transaction__c trn = new Transaction__c(
                RecordTypeId = Schema.SObjectType.Transaction__c.getRecordTypeInfosByName().get('TRN Pending').getRecordTypeId(),
                //TRN.Office_Account__c m/d RCT.Deposit_Account__c
                Office_Account__c = officeAccountList[0].Id,
                Receipting_Cashier__c = cashier[0].Id,
                Transaction_Type__c = 'Deposit',
                Business_Unit__c = receiptList[0].Office_Unit__c,
                Transaction_Status__c = 'Pending',
                Transaction_Sum__c = transactionSum
            );
            insert trn;
            trnId = trn.Id;

            
            Id db = Database.executeBatch(new DepositBatch(ids, trnId), 50);
            
            PageReference pr = new PageReference(retURL);
            pr.setRedirect(true);
            system.debug(pr);
            return pr;
        }else{
            showErrors = true;
            return null;
        }
    }
    
}