force-app/main/default/objects/Office_Account__c/Office_Account__c.object-meta.xml
<CustomObject>
    <description>This object allows a cashier to view the details associated to a deposit into and office account so that they can monitor the historical transactions associated with a deposit account.</description>
    <label>Office Account</label>
    <nameField>
        <label>Office Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Account__c/fields/Account_Balance__c.field-meta.xml
<CustomField>
    <fullName>Account_Balance__c</fullName>
    <formula>Total_Transactions__c -  Total_Checks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Balance_After_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Account_Balance_After_Transaction__c</fullName>
    <description>Set via flow when transaction is deposited or returned and captures the balance of the account after the transaction is committed.</description>
    <label>Account Balance After Transaction</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Account_Balance_Before_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Account_Balance_Before_Transaction__c</fullName>
    <description>Set via flow when transaction is deposited or returned and captures the balance of the account prior to the transaction being committed.</description>
    <label>Account Balance Before Transaction</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Balances_Set__c.field-meta.xml
<CustomField>
    <fullName>Balances_Set__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicating that the balance references on the transaction have been set from the account. Set by the transaction flow when the before and after transaction balance values are set.</description>
    <label>Balances Set</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Check_Count__c.field-meta.xml
<CustomField>
    <fullName>Check_Count__c</fullName>
    <label>Check Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Checks_Amount__c.field-meta.xml
<CustomField>
    <fullName>Checks_Amount__c</fullName>
    <label>Checks Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Office_Account__c.field-meta.xml
<CustomField>
    <fullName>Office_Account__c</fullName>
    <label>Office Account</label>
    <referenceTo>Office_Account__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <inlineHelpText>Please use Transaction Status of Adjusted for adjustments made by the Sr. Deputy of Cashiering.</inlineHelpText>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deposited</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Adjusted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Sum__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Sum__c</fullName>
    <description>For deposits, this is the sum of all eligible RCTs. Populated on record creation by the recordDeposits_Controller apex class. If Transaction type is adjustment, this is populated by Transaction Flow by taking the deposit total and adding it here.</description>
    <inlineHelpText>Sum of all payments in this transaction.</inlineHelpText>
    <label>Transaction Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Defines what type of transaction is taking place.</description>
    <inlineHelpText>Set to Adjustment if submitting this transaction to modify the balance of the bank account for any reason other than a standard deposit.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Treasury_Deposit_Number__c.field-meta.xml
<CustomField>
    <fullName>Treasury_Deposit_Number__c</fullName>
    <label>Treasury Deposit Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TransactionMethods.cls
/*
Called by the TransactionDIRTrigger class
*/
public class TransactionMethods{
    
    public static boolean hasRun = false;
    
    public void TransactionMethods(){  }
    
    public static void accountingDeposit(List<Transaction__c> newTrnList, Map<Id, Transaction__c> oldTrnMap){
        
        hasRun = true;
        
        Set<Id> trnIdsWithRctsToUpdate = new Set<Id>();
        List<Transaction__c> trnsToUpdate = new List<Transaction__c>();
        
        for(Transaction__c trn : [SELECT Id, Transaction_Type__c, Transaction_Status__c, Transaction_Sum__c, Treasury_Deposit_Number__c, Check_Count__c, Checks_Amount__c,
                                        Account_Balance_Before_Transaction__c, Account_Balance_After_Transaction__c, Balances_Set__c, RecordTypeId,
                                        Office_Account__c, Office_Account__r.Account_Balance__c
                                    FROM Transaction__c
                                    WHERE Id IN :newTrnList]){
            
            if(trn.Transaction_Type__c == 'Deposit' && trn.Transaction_Status__c == 'Pending' &&
                    trn.Treasury_Deposit_Number__c != NULL && oldTrnMap.get(trn.Id).Treasury_Deposit_Number__c == NULL &&
                    trn.Check_Count__c != NULL && oldTrnMap.get(trn.Id).Check_Count__c == NULL &&
                    trn.Checks_Amount__c != NULL && oldTrnMap.get(trn.Id).Checks_Amount__c == NULL){
                    
                trn.Transaction_Status__c = 'Deposited';
                trn.Account_Balance_Before_Transaction__c = trn.Office_Account__r.Account_Balance__c;
                trn.Account_Balance_After_Transaction__c = trn.Office_Account__r.Account_Balance__c + trn.Transaction_Sum__c;
                trn.Balances_Set__c = TRUE;
                trn.RecordTypeId = Schema.SObjectType.Transaction__c.getRecordTypeInfosByName().get('TRN Locked').getRecordTypeId();
                
                trnIdsWithRctsToUpdate.add(trn.Id);
                trnsToUpdate.add(trn);
            }
        }
        update trnsToUpdate;
        
        if(!trnIdsWithRctsToUpdate.isEmpty()){
            Id db = Database.executeBatch(new AccountingDepositBatch(trnIdsWithRctsToUpdate), 10);
        }
    }
}