force-app/main/default/objects/Check__c/Check__c.object-meta.xml
<CustomObject>
    <description>Check object for capturing relevant check data</description>
    <label>Check</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check__c/fields/Office_Account__c.field-meta.xml
<CustomField>
    <fullName>Office_Account__c</fullName>
    <description>Lookup to the Office Account object</description>
    <label>Office Account</label>
    <referenceTo>Office_Account__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Check__c/recordTypes/Check.recordType-meta.xml
<RecordType>
    <fullName>Check</fullName>
    <active>true</active>
    <description>Normal page layout for check record type</description>
    <label>Check</label>
</RecordType>

force-app/main/default/objects/Conga_Template_Mapping__c/Conga_Template_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>mapping for IDs for templates, queries for conga called by apex</description>
    <label>Conga Template Mapping</label>
</CustomObject>

force-app/main/default/objects/Conga_Template_Mapping__c/fields/Mapping_Group__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Group__c</fullName>
    <inlineHelpText>Group that the mapping belongs to, for example, WCA daily calendar</inlineHelpText>
    <label>Mapping Group</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conga_Template_Mapping__c/fields/RecordID__c.field-meta.xml
<CustomField>
    <fullName>RecordID__c</fullName>
    <description>pairs the parameter with the ID that needs to be passed into the apex for launching the conga interface</description>
    <inlineHelpText>ID to be passed into the parameter.</inlineHelpText>
    <label>RecordID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office_Account__c/Office_Account__c.object-meta.xml
<CustomObject>
    <description>This object allows a cashier to view the details associated to a deposit into and office account so that they can monitor the historical transactions associated with a deposit account.</description>
    <label>Office Account</label>
    <nameField>
        <label>Office Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GenerateDailyCheckLogController.cls
public with sharing class GenerateDailyCheckLogController {
    
    public Check__c check {get;set;}
    public Id userId {get;set;}
    public String docURL {get;set;}
    //public String selectedRT {get;set;}
    public List<SelectOption> rtList {get;set;}
    //public Map<string, string> ctMap {get;set;}
    public List<Conga_Template_Mapping__c> objCTMapping {get;set;}
    
    public GenerateDailyCheckLogController(){
        check = new Check__c();
        userId = userInfo.getUserId();

        
        // get mapping settings from Conga Template Mapping custom setting
        objCTMapping = [Select Name, RecordID__c FROM Conga_Template_Mapping__c WHERE Mapping_Group__c = 'DailyCheckLog'];
        system.debug('objCTMapping:::: ' +objCTMapping);
        
    }
    
    
    public void setURL(){
        Map<string, string> ctMap = new Map<string, string>();
        system.debug('objCTMapping:::: ' + objCTMapping);
        for (Conga_Template_Mapping__c c : objCTMapping){
            system.debug('c.Name: ' + c.Name + ' & c.RecordID__c: ' + c.RecordID__c);
            ctMap.put(c.Name, c.RecordID__c); 
        }
    DateTime newTimestamp = DateTime.newInstance(check.Issue_Date__c.year(), check.Issue_Date__c.month(), check.Issue_Date__c.day());
    //newTimestamp.format('yyyy-MM-dd');
        if(ctMap.isEmpty())
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR,'CTMap is empty'));
        system.debug('ctMAP::::: ' + ctmap);
        docURL += ''
            +'&id=' + userId
            //+'&queryid=[Calendar]a0md00000064cjs?'
            //+'&queryid=a0m63000000J4rC?'
            +'&queryid='+ctMap.get('DailyCheckLogQuery')+'?'
            //+'pv0=2016-07-13'
            +'pv0='+newTimestamp.format('yyyy-MM-dd')
            +'~pv1='+check.Office_Account__c
            //+'&templateId=a0n63000000KJh3'
            +'&templateid='+ctMap.get('DailyCheckLogTemplate')
            +'&DS7=3';
        system.debug('******************URL: '+docURL);
    }
    
}