force-app/main/default/objects/Check__c/Check__c.object-meta.xml
<CustomObject>
    <description>Check object for capturing relevant check data</description>
    <label>Check</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Check_Batch__c.field-meta.xml
<CustomField>
    <fullName>Check_Batch__c</fullName>
    <label>Check Batch</label>
    <referenceTo>Check_Batch__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Payee to whom the check is written</inlineHelpText>
    <label>Payee</label>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Secondary Approval Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Void Requested</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
            <value>
                <fullName>Uncleared</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>UWF Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Check__c/recordTypes/Check.recordType-meta.xml
<RecordType>
    <fullName>Check</fullName>
    <active>true</active>
    <description>Normal page layout for check record type</description>
    <label>Check</label>
</RecordType>

force-app/main/default/objects/Check_Batch__c/Check_Batch__c.object-meta.xml
<CustomObject>
    <description>Object for associating groups of checks so that they can be approved/voided in batches</description>
    <label>Check Batch</label>
    <nameField>
        <displayFormat>CB-{0}</displayFormat>
        <label>Check Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Check_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that allows a disbursement clerk to indicate whether or not a batch of checks has been successfully printed so that the balances update and the batch closes.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Review Complete</fullName>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
            <value>
                <fullName>Void Requested</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>UWF Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Office_Name__c.field-meta.xml
<CustomField>
    <fullName>Office_Name__c</fullName>
    <formula>If(Office__r.Name = &#39;Judgment Enforcement Unit&#39; || CONTAINS(Office__r.Name, &#39;BOFE&#39;), &#39;Statewide BOFE&#39;, Office__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Office Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/Judgment_Payment__c.object-meta.xml
<CustomObject>
    <description>Records payments made against Judgments and their related interests, filing fees, and attorney fees.</description>
    <label>Judgment Payment</label>
    <nameField>
        <displayFormat>JP-{000000}</displayFormat>
        <label>Judgment Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgment Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Key_Value_Store__c/Key_Value_Store__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores keys and associated values for use in code so that changes can be made without modifying code whenever possible.</description>
    <label>Key Value Store</label>
</CustomObject>

force-app/main/default/objects/Key_Value_Store__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value associated with the key ( Name field )</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Liability_Payment__c/Liability_Payment__c.object-meta.xml
<CustomObject>
    <description>DIR BOFE Payments against Liabilities.</description>
    <label>Liability Payment</label>
    <nameField>
        <displayFormat>LP-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Liability Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Payment__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>Case_Payment__r.Case__r.Case_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Liability_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <inlineHelpText>Amount actually posted from the Case Payment to this payment type.</inlineHelpText>
    <label>Payment Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <description>Used to capture data for Payee information related to a case and liability</description>
    <label>Payee</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payee__c/fields/DIR_Office__c.field-meta.xml
<CustomField>
    <fullName>DIR_Office__c</fullName>
    <formula>Case_Management__r.Office__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DIR Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payee__c/fields/Payee_Type__c.field-meta.xml
<CustomField>
    <fullName>Payee_Type__c</fullName>
    <description>Used to capture if the payee is the state or an employee</description>
    <label>Payee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>Assignee</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Court</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the payee record</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unverified</fullName>
            </value>
            <value>
                <fullName>Incomplete-2nd Request</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Undeliverable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Record__c/Payment_Record__c.object-meta.xml
<CustomObject>
    <label>Payment Record</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Payment Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Record__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>Payee__r.Case_Management__r.Case_Number__c</formula>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Check__c.field-meta.xml
<CustomField>
    <fullName>Check__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check</label>
    <referenceTo>Check__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/DIR_Office__c.field-meta.xml
<CustomField>
    <fullName>DIR_Office__c</fullName>
    <formula>Payee__r.DIR_Office__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DIR Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <label>Payee</label>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Payment_applies_to__c.field-meta.xml
<CustomField>
    <fullName>Payment_applies_to__c</fullName>
    <description>Displays where the payment has been applied on the violations</description>
    <formula>IF(!ISBLANK(Liability_Payment__c) , TEXT(Liability_Payment__r.Payment_Applied_To__c),
   IF(!ISBLANK(Judgment_Payment__c), TEXT( Judgment_Payment__r.Apply_Payment_To__c), &#39;Other&#39;))</formula>
    <label>Payment applies to</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/UWF_Payee_Office__c.field-meta.xml
<CustomField>
    <fullName>UWF_Payee_Office__c</fullName>
    <formula>IF(CONTAINS(Payee__r.DIR_Office__c, &#39;BOFE&#39;), &#39;Statewide BOFE&#39;, Payee__r.DIR_Office__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UWF Payee Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateUWFCheckController.cls
public class CreateUWFCheckController {
    
    public Check_Batch__c shellObject {get;set;}
    public List<Payment_Record__c> paymentRecords {get;set;}
    public Decimal pmtTotal {get;set;}
    public boolean disableCreate {get;set;}
    public boolean updateList {get;set;}
    @testVisible
    private Key_Value_Store__c payeeKVS = Key_Value_Store__c.getInstance('UWF Payee');
    @testVisible
    private DIR_Employee__c intUser;
    
    public CreateUWFCheckController(){
        disableCreate = true;
        updatelist = false;
        if(payeeKVS == null || payeeKVS.Value__c == null){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'There are no values for the Key_Value_Store__c Custom Settings table. Please update the Custom Settings to include a "UWF Payee" record'));
            disableCreate = true;
            return;
        }
        
        try{
            intUser = [SELECT id, name, User__c, Office_Name__c FROM DIR_Employee__c WHERE User__c = :UserInfo.getUserId() LIMIT 1];
        }catch(exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Could not locate a DIR Employee record for your user account. Please contact a System Administrator'));
            disableCreate = true;
            return;
        }
        shellObject = new Check_Batch__c();
        Date pmtRecDateRange = Date.today().addMonths(-6);
        pmtTotal = 0;
        paymentRecords = new List<Payment_Record__c>([SELECT Id, Name, Check__c, DIR_Office__c, UWF_Payee_Office__c, Payee__r.case_number__c, Payment_Amount__c ,
                                                            Payment_applies_to__c, Payee__r.Payee_Type__c, Payee__r.Name, Payee__r.Status__c, Payee__r.Case_management__c,
                                                            Liability_Payment__r.Case_Payment__r.Date_Payment_Received__c, Judgment_Payment__r.Case_Payment__r.Date_Payment_Received__c,
                                                            Check__r.Status__c, Payee__r.Include__c, Payee__r.Payee_Name__c
                                                        FROM Payment_Record__c
                                                        WHERE (Payee__r.Payee_Type__c = 'Employee'
                                                            AND Payee__r.Status__c = 'Unverified' 
                                                            AND Check__c = null
                                                            AND Payment_Amount__c > 0
                                                            AND Payee__r.Include__c = False
                                                            AND ((Liability_Payment__r.Case_Payment__r.Date_Payment_Received__c < :pmtRecDateRange) OR (Judgment_Payment__r.Case_Payment__r.Date_Payment_Received__c < :pmtRecDateRange))
                                                            AND UWF_Payee_Office__c = :intUser.Office_Name__c)
                                                        OR (Payee__r.Payee_Type__c = 'Employee' 
                                                            AND Payee__r.Status__c = 'Unverified' 
                                                            AND Check__c != null
                                                            AND (Check__r.Status__c = 'Voided' OR Check__r.Status__c = 'Canceled')
                                                            AND Payment_Amount__c > 0
                                                            AND Payee__r.Include__c = False
                                                            AND ((Liability_Payment__r.Case_Payment__r.Date_Payment_Received__c < :pmtRecDateRange) OR (Judgment_Payment__r.Case_Payment__r.Date_Payment_Received__c < :pmtRecDateRange))
                                                            AND UWF_Payee_Office__c = :intUser.Office_Name__c)]);
        
        if(paymentRecords == null || paymentRecords.isEmpty()){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No payment records were returned. Please contact a System Administrator for assitance'));
            disableCreate = true;
            return;
        }
        
        for(Payment_Record__c pr : paymentRecords){
            Decimal amt = pr.Payment_Amount__c == null ? 0 : pr.Payment_Amount__c;
            pmtTotal += amt;
            pr.Payee__r.Include__c = True;
        }
        }
        
        public void updateList(){
            disableCreate = false;
            Integer j = 0;
        while (j<paymentRecords.size()){
            if(paymentRecords.get(j).Payee__r.Include__c==false){
                pmtTotal -=paymentRecords.get(j).Payment_Amount__c;
                paymentRecords.remove(j);
            }else{
                j++;
            }
        }
        
        if(paymentRecords == null || paymentRecords.isEmpty()){
            disableCreate = true;
            updateList = true;
            return;
        }
    }
    
    
    public void createCheckBatchRecords(){
        if(shellObject.Office_Account__c == null){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'You must select an Office Account in order to continue'));
            return;
        }
        
        Check_Batch__c newCheckBatch = new Check_Batch__c(
            Requested_By__c = intUser.Id,
            Status__c = 'New',
            Office_Account__c = shellObject.Office_Account__c
        );
        insert newCheckBatch;
        
        Check__c newCheck = new Check__c(
            Payee__c = payeeKVS.Value__c,
            Status__c = 'Pending Approval',
            Check_Batch__c = newCheckBatch.Id,
            Office_Account__c = shellObject.Office_Account__c,
            Amount__c = pmtTotal
        );
        insert newCheck;
        
        for(Payment_Record__c pr : paymentRecords){
            pr.Check__c = newCheck.Id;
        }
        update paymentRecords;
        disableCreate = true;
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Success! Click<a href="/'+newCheckBatch.Id+'">Here</a>to view the Check Batch'));
    }
    
    public pageReference returnHome(){
        return new pageReference('/home/home.jsp');
    }
}