force-app/main/default/objects/Check__c/Check__c.object-meta.xml
<CustomObject>
    <description>Check object for capturing relevant check data</description>
    <label>Check</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check__c/fields/Check_Batch__c.field-meta.xml
<CustomField>
    <fullName>Check_Batch__c</fullName>
    <label>Check Batch</label>
    <referenceTo>Check_Batch__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Check__c/recordTypes/Check.recordType-meta.xml
<RecordType>
    <fullName>Check</fullName>
    <active>true</active>
    <description>Normal page layout for check record type</description>
    <label>Check</label>
</RecordType>

force-app/main/default/objects/Check_Batch__c/Check_Batch__c.object-meta.xml
<CustomObject>
    <description>Object for associating groups of checks so that they can be approved/voided in batches</description>
    <label>Check Batch</label>
    <nameField>
        <displayFormat>CB-{0}</displayFormat>
        <label>Check Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Check_Batch__c/fields/Starting_Check_Number__c.field-meta.xml
<CustomField>
    <fullName>Starting_Check_Number__c</fullName>
    <description>Allows the user to set the starting check number when printing the batch. Upon populating or changing the starting check number, apex updates the checks in the batch to set the check number on each check</description>
    <inlineHelpText>Enter the starting check number for this batch when printing</inlineHelpText>
    <label>Starting Check Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/checkBatchAction.cls
public class checkBatchAction extends TriggerAction {

    public boolean shouldRun;
    
    private List<Check_Batch__c> batches = new List<Check_Batch__c>();
    
    public checkBatchAction(Map<Id, sObject> triggerNewMap, Map<Id, sObject> triggerOldMap){ //is update
        super(triggerNewMap, triggerOldMap);
        
        for(sObject sObj : triggerNewMap.values()){
        	//CV: put entrance logic here so that batches only contains records that we want to manipulate
            Check_Batch__c cb = (Check_Batch__c)sObj;
            Check_Batch__c oldCb = (Check_Batch__c)triggerOldMap.get(cb.Id);
            if ( cb.Starting_Check_Number__c != Null && cb.Starting_Check_Number__c != oldCb.Starting_Check_Number__c ){
                batches.add(cb);
            }
            
            
            
            
        }
        
    }
    

    
    public override boolean shouldRunOnInsert() {
    	return false; 
    }
     
    public override boolean shouldRunOnUpdate() {
    	//CV: put check here to validate that the batches list contains records (not empty). If it's empty, no reason to run the action
    	//CV: use and return the shouldRun variable here
    	if(!batches.isEmpty())
    		shouldRun = true; 
        else
            shouldRun = false;
        
        return shouldRun;
    }
    
    public override boolean shouldRunOnDelete() { return false; } 
        
    public override void doAction() {   
        
        Map<Id, Check_batch__c> checkBatchMap = new Map<Id, Check_batch__c>(batches);
        
        list<Check_Batch__c> checkBatch = new list<Check_Batch__c>([SELECT Id, Starting_Check_Number__c, (SELECT Id, Check_Number__c FROM Checks__r Order by Name) FROM Check_Batch__c WHERE ID in :checkBatchMap.keySet()]);
        system.debug('****** checkBatch' + checkBatch);
        
        if (!checkBatch.isEmpty()){
            list<Check__c> checksToUpdate = new list<Check__c>();
            for(Check_Batch__c cb : checkBatch){
                if (!cb.Checks__r.isEmpty()){
                    integer num = Integer.valueOf(cb.Starting_Check_Number__c);
                    for(Check__c c : cb.Checks__r){
                        c.Check_Number__c = string.valueOf(num);
                        num++;
                        checksToUpdate.add(c);
                        system.debug('******* Added ' + c.Id + ' to checksToUpdate');
                    }
                }
            }
            if(!checksToUpdate.isEmpty())
            update checksToUpdate;
        }
    }
    
    public static void runHandler() {  
        
        if (trigger.isBefore){
            return;
        }
        if (trigger.isUpdate) {
            checkBatchAction action = new checkBatchAction(trigger.newMap, trigger.oldMap);
            if(action.shouldRunOnUpdate()){
                action.doAction();
            }
        }

       
    }
}