force-app/main/default/objects/Check__c/Check__c.object-meta.xml
<CustomObject>
    <description>Check object for capturing relevant check data</description>
    <label>Check</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Case Managment object</description>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Payee to whom the check is written</inlineHelpText>
    <label>Payee</label>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Funds_Drawn_on_Deposits__c.field-meta.xml
<CustomField>
    <fullName>Funds_Drawn_on_Deposits__c</fullName>
    <description>Sum of all the Payment Records with Checks issued disbursed on this Case. Populated by apex: PaymentRecordTrigger, then PaymentRecordMethods</description>
    <inlineHelpText>Sum of all disbursements on this Case.</inlineHelpText>
    <label>Funds Drawn on Deposits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>When a case is related to another, for example, a duplicate of another case, this field holds the case that is related to this one.</description>
    <inlineHelpText>If this case is related to another, the other case is indicated here.</inlineHelpText>
    <label>Related Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Related Cases</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <description>Used to capture data for Payee information related to a case and liability</description>
    <label>Payee</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payee__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <description>M/D to the Case Management object</description>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Payees</relationshipLabel>
    <relationshipName>Payees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/Payment_Record__c.object-meta.xml
<CustomObject>
    <label>Payment Record</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Payment Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Record__c/fields/Check__c.field-meta.xml
<CustomField>
    <fullName>Check__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check</label>
    <referenceTo>Check__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <label>Payee</label>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PRRollupToCMHack.cls
/*Scheduled by the SchedulePRRollupToCMHack class, q.v. 
-Runs nightly.
-Queries Checks last modified within the past X days, then for each Case on those Checks, updates one of the child PRs, seemingly pointlessly,
    to trigger the PaymentRecordTrigger so PR.Payment_Amount__c rolls up to the CM.Funds_Drawn_on_Deposits__c.
-This is a kludge which should no longer be needed once the Cashiering Rearchitecting (Tier 3?) project is completed.*/
global without sharing class PRRollupToCMHack implements Database.Batchable<sObject>, Database.Stateful{
    
    Set<Payment_Record__c> prs = new Set<Payment_Record__c>();
    Set<Id> cmIds = new Set<Id>();
    Set<Payment_Record__c> prsToUpdate = new Set<Payment_Record__c>();
    
    
    global Database.QueryLocator start(Database.BatchableContext info){
        
        return Database.getQueryLocator(
            'SELECT Id, Name, Case__c, LastModifiedDate, '
                    + '(SELECT Id, Name, Payment_Amount__c, Payee__c, Payee__r.Case_Management__c, Payee__r.Case_Management__r.Id '
                        + 'FROM Payment_Records__r) '
                + 'FROM Check__c'
        );
    }
    
    
    global void execute(Database.BatchableContext info, List<sObject> scopeX){
        List<Check__c> scope = (List<Check__c>)scopeX;
        
        for(Check__c chk : scope){
            prs.addAll(chk.Payment_Records__r);
        }
        
        for(Payment_Record__c pr : prs){
            cmIds.add(pr.Payee__r.Case_Management__r.Id);
        }
        
        for(Id cmId : cmIds){
            for(Payment_Record__c pr : prs){
                if(cmId == pr.Payee__r.Case_Management__r.Id){
                    prsToUpdate.add(pr);
                    break; //We only need to find one PR under a Case
                }
            }
        }
        
        List<Payment_Record__c> prsToUpdateList = new List<Payment_Record__c>(prsToUpdate);
        update prsToUpdateList;
    }
    
    global void finish(Database.BatchableContext info){ }
    
}