force-app/main/default/objects/Check__c/Check__c.object-meta.xml
<CustomObject>
    <description>Check object for capturing relevant check data</description>
    <label>Check</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Office_Account__c.field-meta.xml
<CustomField>
    <fullName>Office_Account__c</fullName>
    <description>Lookup to the Office Account object</description>
    <label>Office Account</label>
    <referenceTo>Office_Account__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Secondary Approval Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Void Requested</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
            <value>
                <fullName>Uncleared</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>UWF Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Check__c/recordTypes/Check.recordType-meta.xml
<RecordType>
    <fullName>Check</fullName>
    <active>true</active>
    <description>Normal page layout for check record type</description>
    <label>Check</label>
</RecordType>

force-app/main/default/objects/Office_Account_Monthly_Totals__c/Office_Account_Monthly_Totals__c.object-meta.xml
<CustomObject>
    <description>Used for Balance sheet to capture monthly totals</description>
    <label>Office Account Monthly Totals</label>
    <nameField>
        <displayFormat>OAMT-{0}</displayFormat>
        <label>Office Account Monthly Totals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Office Account Monthly Totals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Account_Monthly_Totals__c/fields/Adjustments__c.field-meta.xml
<CustomField>
    <fullName>Adjustments__c</fullName>
    <description>From CreateOAMTRecords apex class - sum of Transaction__c.Transaction_Sum__c for all Transactions where Deposit Date is in the previous month and Transaction Type = Adjustment.</description>
    <label>+ Adjustments</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Office_Account_Monthly_Totals__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date for this balance sheet. From CreateOAMTRecords apex class - last day of the month for the month of this report. The month of this report is the month PREVIOUS to the month when the flow is being run, i.e., for a flow run on July 1, 2017 to get June 2017&#39;s totals, this field will show 6/30/2017.</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Office_Account_Monthly_Totals__c/fields/Deposited_Receipts__c.field-meta.xml
<CustomField>
    <fullName>Deposited_Receipts__c</fullName>
    <description>From CreateOAMTRecords apex class - sum of Receipt__c.Payment_Amount__c where Status = Deposited or Returned, and Deposit Date is in the previous month.</description>
    <label>+ Deposited Receipts</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Office_Account_Monthly_Totals__c/fields/Disbursements__c.field-meta.xml
<CustomField>
    <fullName>Disbursements__c</fullName>
    <description>From CreateOAMTRecords apex class - sum of Check__c.Amount__c for all Checks where Issue Date is in the previous month and Status = Printed or Cleared.</description>
    <label>- Disbursements</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Office_Account_Monthly_Totals__c/fields/Office_Account__c.field-meta.xml
<CustomField>
    <fullName>Office_Account__c</fullName>
    <label>Office Account</label>
    <referenceTo>Office_Account__c</referenceTo>
    <relationshipLabel>Office Account Monthly Totals</relationshipLabel>
    <relationshipName>Office_Account_Monthly_Totals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Office_Account_Monthly_Totals__c/fields/Prior_Month_Returned_Receipts__c.field-meta.xml
<CustomField>
    <fullName>Prior_Month_Returned_Receipts__c</fullName>
    <description>From CreateOAMTRecords apex class - sum of Receipt__c.Payment_Amount__c for all Receipts where Deposit Date is _before_ the previous month, Returned Date _in_ the previous month, and Returned Item = TRUE.</description>
    <label>+ Prior Month Returned Receipts</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Office_Account_Monthly_Totals__c/fields/Prior_Month_Voided_and_Canceled_Checks__c.field-meta.xml
<CustomField>
    <fullName>Prior_Month_Voided_and_Canceled_Checks__c</fullName>
    <description>From CreateOAMTRecords apex class  - sum of Check__c.Amount__c for all Checks where Issue Date is _before_ the previous month, Status Date is _in_ the previous month, and Status = Voided or Canceled.</description>
    <label>+ Prior Month Voided and Canceled Checks</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <description>Represents a receivable: an incoming payment, or an advice of incoming funds. [Encompasses the former Payment Log, Payment Group and Receipt objects to 1 single object.]</description>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RCT-{0000000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Deposit_Account__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Account__c</fullName>
    <description>Picklist for capturing the Deposit Account</description>
    <label>Deposit Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>108</fullName>
            </value>
            <value>
                <fullName>01-112</fullName>
            </value>
            <value>
                <fullName>04-112</fullName>
            </value>
            <value>
                <fullName>05-113</fullName>
            </value>
            <value>
                <fullName>06-114</fullName>
            </value>
            <value>
                <fullName>633-114</fullName>
            </value>
            <value>
                <fullName>07-119</fullName>
            </value>
            <value>
                <fullName>08-116</fullName>
            </value>
            <value>
                <fullName>09-117</fullName>
            </value>
            <value>
                <fullName>10-117</fullName>
            </value>
            <value>
                <fullName>11-119</fullName>
            </value>
            <value>
                <fullName>12-119</fullName>
            </value>
            <value>
                <fullName>13-113</fullName>
            </value>
            <value>
                <fullName>14-112</fullName>
            </value>
            <value>
                <fullName>15-116</fullName>
            </value>
            <value>
                <fullName>17-113</fullName>
            </value>
            <value>
                <fullName>18-113</fullName>
            </value>
            <value>
                <fullName>23-124</fullName>
            </value>
            <value>
                <fullName>32-117</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Deposit_Date__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Date__c</fullName>
    <formula>Transaction__r.Deposit_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deposit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>Required field for capturing the payment amount</description>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Returned_Date__c.field-meta.xml
<CustomField>
    <fullName>Returned_Date__c</fullName>
    <description>Date a payment was returned from the bank. Different from Date_Returned__c which is the date a payment was mailed back to the submitter.</description>
    <inlineHelpText>Date a payment was returned from the bank. Different from Date Returned which is the date a payment was mailed back to the submitter.</inlineHelpText>
    <label>Returned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Returned_Item__c.field-meta.xml
<CustomField>
    <fullName>Returned_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This marks the Item returned so that the transactions related to this item may be reversed within the system.</description>
    <inlineHelpText>Check this box when the bank notifies Cashiering that this deposited Receipt has been returned, e.g., Non-Sufficient Funds (NSF) or Stopped Payment.</inlineHelpText>
    <label>Returned Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Deposit Pending</fullName>
            </value>
            <value>
                <fullName>Deposited</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Mailed to Employee</fullName>
            </value>
            <value>
                <fullName>Restitution Warrant sent to JEU</fullName>
            </value>
            <value>
                <fullName>Returned to Sender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent transaction that ends up being deposited or reversed with the bank.</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Voided_Item__c.field-meta.xml
<CustomField>
    <fullName>Voided_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if this Receipt needs to be voided.</inlineHelpText>
    <label>Voided Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Office_Account__c.field-meta.xml
<CustomField>
    <fullName>Office_Account__c</fullName>
    <label>Office Account</label>
    <referenceTo>Office_Account__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Sum__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Sum__c</fullName>
    <description>For deposits, this is the sum of all eligible RCTs. Populated on record creation by the recordDeposits_Controller apex class. If Transaction type is adjustment, this is populated by Transaction Flow by taking the deposit total and adding it here.</description>
    <inlineHelpText>Sum of all payments in this transaction.</inlineHelpText>
    <label>Transaction Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Defines what type of transaction is taking place.</description>
    <inlineHelpText>Set to Adjustment if submitting this transaction to modify the balance of the bank account for any reason other than a standard deposit.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateOAMTRecords.cls
//Scheduled by the ScheduleCreateOAMTRecords class, q.v. Should be run on the 1st of each month for the month previous.
public class CreateOAMTRecords{
    // TODO: change this to a batch class if RCT and Check record amounts get too large
    public List<Office_Account_Monthly_Totals__c> OAMTsToInsert = new List<Office_Account_Monthly_Totals__c>();
    
    public void CreateOAMTRecords(){
        Date today = Date.today(); //Date this class is scheduled to run, which should be the 1st of each month for the month just previous
        if(Test.isRunningTest()){
            today = Date.parse('08/01/2019'); //test class has hard-coded dates
        }
        Date firstOfPreviousMonth = today.addMonths(-1).toStartOfMonth(); //first day of the month that the OAMT records are created FOR
        Date lastOfPreviousMonth = Date.newInstance(firstOfPreviousMonth.year(), firstOfPreviousMonth.month(), Date.daysInMonth(firstOfPreviousMonth.year(), firstOfPreviousMonth.month()));
        Date firstOf2MonthsPrevious = firstOfPreviousMonth.addMonths(-1).toStartOfMonth();
        Date lastOf2MonthsPrevious = Date.newInstance(firstOf2MonthsPrevious.year(), firstOf2MonthsPrevious.month(), Date.daysInMonth(firstOf2MonthsPrevious.year(), firstOf2MonthsPrevious.month()));
        
        List<Office_Account__c> OAs = [SELECT Id, Name FROM Office_Account__c];
        
        /*OAMT.Adjustments__c : Adjustment type TRNs deposited in the previous month. */
        List<Transaction__c> adjustmentTRNs = [SELECT Id, Name, Deposit_Date__c, Transaction_Type__c, Transaction_Sum__c, Office_Account__c
                                                FROM Transaction__c
                                                WHERE ((Deposit_Date__c >= :firstOfPreviousMonth AND Deposit_Date__c <= :lastOfPreviousMonth)
                                                        AND Transaction_Type__c = 'Adjustment')];
        
        /*OAMT.Deposited_Receipts__c : RCTs deposited in the previous month (including RCTs deposited AND returned in the previous month) */
        /*OAMT.Prior_Month_Returned_Receipts__c : RCTs returned in the previous month that were deposited prior to the previous month */
        List<Receipt__c> depositedOrReturnedRCTs = [SELECT Id, Name, Deposit_Date__c, Deposit_Account__c, Returned_Item__c, Returned_Date__c, Voided_Item__c, Status__c, Payment_Amount__c,
                                                        Transaction__c, Transaction__r.Id, Transaction__r.Deposit_Date__c, Transaction__r.Transaction_Type__c,
                                                        Transaction__r.Office_Account__c, Transaction__r.Office_Account__r.Id, Transaction__r.Office_Account__r.Name
                                                    FROM Receipt__c
                                                    WHERE (((Deposit_Date__c >= :firstOfPreviousMonth AND Deposit_Date__c <= :lastOfPreviousMonth)
                                                                AND (Status__c = 'Deposited'
                                                                    OR Status__c = 'Returned'))
                                                            OR((Deposit_Date__c <= :lastOf2MonthsPrevious)
                                                                AND(Returned_Date__c >= :firstOfPreviousMonth AND Returned_Date__c <= :lastOfPreviousMonth)
                                                                AND Returned_Item__c = TRUE))];
        
        /*OAMT.Disbursements__c : Printed or cleared status Checks issued in the previous month
        /*OAMT.Prior_Month_Voided_and_Canceled_Checks__c : Voided or canceled status Checks voided or canceled in the previous month, issued prior to the previous month */
        List<Check__c> printedOrVoidedChecks = [SELECT Id, Name, Status__c, Status_Date__c, Issue_Date__c, Amount__c, Office_Account__c, Office_Account__r.Id, Office_Account__r.Name
                                                FROM Check__c
                                                WHERE (((Issue_Date__c >= :firstOfPreviousMonth AND Issue_Date__c <= :lastOfPreviousMonth)
                                                        AND(Status__c = 'Printed' OR Status__c = 'Cleared'))
                                                    OR((Issue_Date__c <= :lastOf2MonthsPrevious)
                                                        AND(Status_Date__c >= :firstOfPreviousMonth AND Status_Date__c <= :lastOfPreviousMonth)
                                                        AND(Status__c = 'Voided' OR Status__c = 'Canceled')))];
        
        //Assumes previous OAMT records were created by this code on the 1st of the previous month
        List<Office_Account_Monthly_Totals__c> OAMTs = [SELECT Id, Name, CreatedDate, Office_Account__c, Date__c, Ending_Balance__c, Adjustments__c, Prior_Month_Returned_Receipts__c,
                                                            Prior_Month_Voided_and_Canceled_Checks__c, Deposited_Receipts__c, Disbursements__c, Month_Year__c
                                                        FROM Office_Account_Monthly_Totals__c
                                                        WHERE (Date__c = :lastOf2MonthsPrevious)];
        
        for(Office_Account__c OA : OAs){
            for(Office_Account_Monthly_Totals__c OAMT : OAMTs){
                
                if(OA.Id == OAMT.Office_Account__c){
                    Decimal sumOfDepositedRCTs = 0.00;
                    Decimal sumOfReturnedRCTs = 0.00;
                    Decimal sumOfPrintedChecks = 0.00;
                    Decimal sumOfVoidedChecks = 0.00;
                    Decimal sumOfAdjustmentTRNs = 0.00;

                    for(Receipt__c RCT : depositedOrReturnedRCTs){
                        if(RCT.Transaction__r.Office_Account__c == OAMT.Office_Account__c){
                            if(RCT.Deposit_Date__c >= firstOfPreviousMonth && RCT.Deposit_Date__c <= lastOfPreviousMonth){
                                sumOfDepositedRCTs += RCT.Payment_Amount__c;
                            }else{
                                sumOfReturnedRCTs += RCT.Payment_Amount__c;
                            }
                        }
                    }
                    for(Check__c check : printedOrVoidedChecks){
                        if(check.Office_Account__c == OAMT.Office_Account__c){
                            if(check.Status__c == 'Printed' || check.Status__c == 'Cleared'){
                                sumOfPrintedChecks += check.Amount__c;
                            }else{
                                sumOfVoidedChecks += check.Amount__c;
                            }
                        }
                    }
                    for(Transaction__c trn : adjustmentTRNs){
                        if(trn.Office_Account__c == OAMT.Office_Account__c){
                            sumOfAdjustmentTRNs += trn.Transaction_Sum__c;
                        }
                    }

                    Office_Account_Monthly_Totals__c newOAMT = new Office_Account_Monthly_Totals__c(
                        Office_Account__c = OA.Id,
                        Date__c = lastOfPreviousMonth,
                        Prior_Month_Starting_Balance__c = OAMT.Ending_Balance__c,
                        Adjustments__c = sumOfAdjustmentTRNs,
                        Prior_Month_Returned_Receipts__c = sumOfReturnedRCTs,
                        Prior_Month_Voided_and_Canceled_Checks__c = sumOfVoidedChecks,
                        Deposited_Receipts__c = sumOfDepositedRCTs,
                        Disbursements__c = sumOfPrintedChecks
                    );
                    OAMTsToInsert.add(newOAMT);
                }
            }
        }
        insert OAMTsToInsert;
    }
}