force-app/main/default/objects/A_Auto_Assign_Rule__mdt/A_Auto_Assign_Rule__mdt.object-meta.xml
<CustomObject>
    <label>A+ Auto Assign Rule</label>
    <pluralLabel>A+ Auto Assign Rules</pluralLabel>
</CustomObject>

force-app/main/default/objects/A_Auto_Assign_Rule__mdt/fields/A_Configuration__c.field-meta.xml
<CustomField>
    <fullName>A_Configuration__c</fullName>
    <label>A+ Configuration</label>
    <referenceTo>A_Configuration__mdt</referenceTo>
    <relationshipLabel>A+ Auto Assign Rules</relationshipLabel>
    <relationshipName>A_Auto_Assign_Rules</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/A_Auto_Assign_Rule__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>Field API name to which auto assigned value has to be populated</description>
    <inlineHelpText>Field API name to which auto assigned value has to be populated</inlineHelpText>
    <label>Field API Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A_Auto_Assign_Rule__mdt/fields/Field_value__c.field-meta.xml
<CustomField>
    <fullName>Field_value__c</fullName>
    <description>Field value to be auto populated</description>
    <inlineHelpText>Field value to be auto populated</inlineHelpText>
    <label>Field value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A_Auto_Assign_Rule__mdt/fields/Keyword_To_Match__c.field-meta.xml
<CustomField>
    <fullName>Keyword_To_Match__c</fullName>
    <label>Keyword To Match</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A_Configuration__mdt/A_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>A+ Configuration</label>
    <pluralLabel>A+ Configuration</pluralLabel>
</CustomObject>

force-app/main/default/objects/A_Configuration__mdt/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A_Configuration__mdt/fields/Record_Type_API_Names__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_API_Names__c</fullName>
    <description>Record Type API Names (Comma seperated)</description>
    <inlineHelpText>Record Type API Names (Comma seperated)</inlineHelpText>
    <label>Record Type API Names</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Attachments_Data__c/Attachments_Data__c.object-meta.xml
<CustomObject>
    <label>Attachments + Data</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Attachments + Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments + Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Data__c/fields/Attachments__c.field-meta.xml
<CustomField>
    <fullName>Attachments__c</fullName>
    <label>Attachments +</label>
    <referenceTo>Attachments_New__c</referenceTo>
    <relationshipLabel>Attachments + Data</relationshipLabel>
    <relationshipName>Attachments_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attachments_Data__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <formula>Attachments__r.File_Type__c</formula>
    <label>File Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/Attachments_New__c.object-meta.xml
<CustomObject>
    <label>Attachments +</label>
    <nameField>
        <displayFormat>A+-{000000}</displayFormat>
        <label>Attachments Plus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments +</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_New__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Related_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Id__c</fullName>
    <label>Related Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Purge_Date__c.field-meta.xml
<CustomField>
    <fullName>Purge_Date__c</fullName>
    <description>Purge date.</description>
    <inlineHelpText>The date after which the file may be purged from the system.</inlineHelpText>
    <label>Purge Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <description>Vertiba</description>
    <label>RCI</label>
</RecordType>

force-app/main/default/classes/DIR_ContentDocumentLinkTriggerHandler.cls
//-----------------------------
// @author: Oswin Correa
// @date: 20/4/2018
// @description: Trigger Handler of DIR_ContentDocumentLink Trigger on Content Document
//-----------------------------
public with sharing class DIR_ContentDocumentLinkTriggerHandler {
    
    //-----------------------------
    // @param: Map<Id,ContentDocumentLink> mapCDL
    // @description: Method called on After insert of ContentDocumentLinks
    // @return: void
    //-----------------------------    
    public static void onAfterInsert(Map<Id,ContentDocumentLink> mapCDL){
        
        linkFilesToAttachmentsNew(mapCDL);
    }
    
    //-----------------------------
    // @param: Map<Id,ContentDocumentLink> mapCDL
    // @description: Method to link inserted files to Attachments New
    // @return: void
    //-----------------------------    
    private static void linkFilesToAttachmentsNew(Map<Id,ContentDocumentLink> mapCDL){
        
        Map<String,String> mapFilteredCDL = new Map<String,String>();
        Set<String> setConfiguredObjects = new Set<String>();
        Map<String,List<ContentDocumentLink>> mapObjectNameToCDL =  new Map<String,List<ContentDocumentLink>>();
        Map<String,ContentDocumentLink> mapCDLidToAttachmentCDL = new Map<String,ContentDocumentLink>();
        Map<String,Attachments_New__c> mapCDLidToAttachment =  new Map<String,Attachments_New__c>();
        Map<String,Map<String,Attachments_Data__c>> mapCDLidToAttachmentData =  new Map<String,Map<String,Attachments_Data__c>>();
        List<Attachments_Data__c> lstAttachmentDetails =  new List<Attachments_Data__c>();
        
        String testConfigDataJSON = '[{"Id":"m06350000004DlIAAU","Object_API_Name__c":"Attachments_New__c","File_Type__c":"Intake","Record_Type_API_Names__c":"RCI"}]';
        String testRulesJSON = '[{"Id":"m083500000000Q9AAI","Field_value__c":"Intake Form","Keyword_To_Match__c":"test","Field_API_Name__c":"Subtype","A_Configuration__c":"m06350000004DlIAAU",'+
                                '"A_Configuration__r":{"Id":"m06350000004DlIAAU","Record_Type_API_Names__c":"RCI","File_Type__c":"Intake","Object_API_Name__c":"Attachments_New__c"}},'+
                                '{"Id":"m083500000000PVAAY","Field_value__c":"true","Keyword_To_Match__c":"test","Field_API_Name__c":"New_Boolean","A_Configuration__c":"m06350000004DlIAAU",'+
                                '"A_Configuration__r":{"Id":"m06350000004DlIAAU","Record_Type_API_Names__c":"RCI","File_Type__c":"Intake","Object_API_Name__c":"Attachments_New__c"}}]';

        
        List<A_Configuration__mdt>  configurations;
        
        if(!Test.isRunningTest()){
            
             configurations = [SELECT Id,Object_API_Name__c,File_Type__c,Record_Type_API_Names__c
                               FROM A_Configuration__mdt
                               WHERE Object_API_Name__c != Null
                               AND File_Type__c != Null];
        }
        else{
            
            configurations = (List<A_Configuration__mdt>) JSON.deserialize(testConfigDataJSON, List<A_Configuration__mdt>.class);
        }
            
        for(A_Configuration__mdt objConfig : configurations){
                                                   
             setConfiguredObjects.add(objConfig.Object_API_Name__c);
         }
         
         for(ContentDocumentLink objCDL : mapCDL.values()){
            
            if(setConfiguredObjects.contains(String.valueof(Id.valueof(objCDL.LinkedEntityId).getSobjectType()))){

                mapFilteredCDL.put(objCDL.Id,objCDL.ContentDocumentId);
            }
        }
        

         for(ContentDocument objCD: [SELECT Id,Title,
                                    (SELECT Id,LinkedEntityId,LinkedEntity.RecordType.DeveloperName,LinkedEntity.Type,ContentDocumentId,ContentDocument.Title FROM  ContentDocumentLinks 
                                    WHERE Id =: mapFilteredCDL.keyset())
                                    FROM ContentDocument 
                                    WHERE Id =: mapFilteredCDL.values()]){
                                        
                                        
              for(ContentDocumentLink objCDL : objCD.ContentDocumentLinks){
                  

                   if(!mapObjectNameToCDL.containskey(objCDL.LinkedEntity.Type)){
                
                        mapObjectNameToCDL.put(objCDL.LinkedEntity.Type, new List<ContentDocumentLink>());
                   }
                   
                   mapObjectNameToCDL.get(objCDL.LinkedEntity.Type).add(objCDL);
                   
                   mapCDLidToAttachmentCDL.put(objCDL.id,new ContentDocumentLink(ContentDocumentId = objCD.Id,ShareType = 'I'));
                                                              
                   mapCDLidToAttachment.put(objCDL.id, new Attachments_New__c(Related_Id__c = objCDL.LinkedEntityId,
                                                                              File_Type__c = 'Related Files',
                                                                              File_Name__c = objCD.Title));

                   mapCDLidToAttachmentData.put(objCDL.id,new Map<String,Attachments_Data__c>{'File_Name' => new Attachments_Data__c( Field_API_Name__c = 'File_Name',
                                                                                                                                       Field_Name__c = 'File_Name',
                                                                                                                                       Value__c = objCD.Title),
                                                                                                                       
                                                                                              'Private' => new Attachments_Data__c(Field_API_Name__c = 'Private',
                                                                                                                                   Field_Name__c = 'Private',
                                                                                                                                   Value__c = 'true')});                                                            
              }
                                        
        }
        
        List<A_Auto_Assign_Rule__mdt>  rules;
        
        if(!Test.isRunningTest()){
            
             rules = [SELECT Id,Field_value__c,Keyword_To_Match__c,Field_API_Name__c,A_Configuration__r.Record_Type_API_Names__c,A_Configuration__r.File_Type__c,A_Configuration__r.Object_API_Name__c 
                      FROM A_Auto_Assign_Rule__mdt
                      WHERE A_Configuration__r.Object_API_Name__c =: mapObjectNameToCDL.keyset()
                      AND A_Configuration__r.File_Type__c != Null];
        }
        else{
            rules = (List<A_Auto_Assign_Rule__mdt>) JSON.deserialize(testRulesJSON, List<A_Auto_Assign_Rule__mdt>.class);
        }
        
        for(A_Auto_Assign_Rule__mdt objAAR : rules){
          
             if(mapObjectNameToCDL.containsKey(objAAR.A_Configuration__r.Object_API_Name__c)){
                 
                for(ContentDocumentLink objCDL : mapObjectNameToCDL.get(objAAR.A_Configuration__r.Object_API_Name__c)){
                  
                  if((String.isBlank(objCDL.LinkedEntity.RecordType.DeveloperName) ||
                      objAAR.A_Configuration__r.Record_Type_API_Names__c.trim().contains(objCDL.LinkedEntity.RecordType.DeveloperName)) &&
                      objCDL.ContentDocument.Title.trim().toLowerCase().contains(objAAR.Keyword_To_Match__c.trim().toLowerCase())){
                          
                      mapCDLidToAttachment.get(objCDL.Id).File_Type__c = objAAR.A_Configuration__r.File_Type__c;
                      
                      if(objAAR.Field_API_Name__c == 'File_Name'){
                          
                          mapCDLidToAttachment.get(objCDL.Id).File_Name__c = objAAR.Field_value__c;
                          mapCDLidToAttachmentData.get(objCDL.Id).get('File_Name').Value__c = objAAR.Field_value__c;
                      }
                      else if(objAAR.Field_API_Name__c != 'Private'){
                          
                           mapCDLidToAttachmentData.get(objCDL.id).put(objAAR.Field_API_Name__c, new Attachments_Data__c(Field_API_Name__c = objAAR.Field_API_Name__c,
                                                                                                                         Field_Name__c = objAAR.Field_API_Name__c,
                                                                                                                         Value__c = objAAR.Field_value__c));
                      }
                  }
                }
            }
         }
         
         insert mapCDLidToAttachment.values();
         
         
         for(String clId : mapCDLidToAttachmentData.keyset()){
             
             Attachments_New__c objAtt = mapCDLidToAttachment.get(clId);
             mapCDLidToAttachmentCDL.get(clId).LinkedEntityId = objAtt.Id;
             
             for(Attachments_Data__c objAttDetails : mapCDLidToAttachmentData.get(clId).values()){
                 
                 objAttDetails.Attachments__c = objAtt.Id;
                 lstAttachmentDetails.add(objAttDetails);
             }
         }
         
         insert lstAttachmentDetails;
         
         if(!Test.isRunningTest()){
             
            insert mapCDLidToAttachmentCDL.values();
         }
    }

    //-----------------------------
    // @param: Map<Id,ContentDocumentLink> mapCDL
    // @description: Method called on Before Deelete of  ContentDocumentLinks
    // @return: void
    //-----------------------------    
    public static void onBeforeDelete(Map<Id,ContentDocumentLink> mapCDL){
        
        List<ContentDocumentLink> filteredCDL =  new List<ContentDocumentLink>();
        Set<String> setRelatedAttachments = new Set<String>();

        for(ContentDocumentLink objCDL : mapCDL.values()){
            
            if(String.valueof(Id.valueof(objCDL.LinkedEntityId).getSobjectType()) == 'Attachments_New__c'){
                
                 setRelatedAttachments.add(objCDL.LinkedEntityId);
                 filteredCDL.add(objCDL);
            }
        }
        
        
        if(!filteredCDL.isEmpty()){
            
            preventDelete(setRelatedAttachments,filteredCDL);
        }

    }
    
    //-----------------------------
    // @param: Set<String> setRelatedAttachments, List<ContentDocumentLink> filteredCDL
    // @description: Method to prevent non admins from deleting ContentDocumentLinks for the files uploaded via attachments + considering the related Case purge date
    // @return: void
    //-----------------------------
    private static void preventDelete(Set<String> setRelatedAttachments, List<ContentDocumentLink> filteredCDL){
         
         Set<String> setCaseIds = new Set<String>();
         Map<String,String> mapAttachmentIdToRelatedCase =  new Map<String,String>();
         
         Boolean isSystemAdmin = false;
         
         List<Profile> sysAdminList = [SELECT Id FROM Profile WHERE Name  like 'System Administrator%'];
         
         if (sysAdminList.size() > 0)
         {
             for (Integer i = 0; i < sysAdminList.size(); i++)
             {
                 if (Userinfo.getProfileId() == sysAdminList[i].Id)
                 {
                     isSystemAdmin = true;
                 }
             }
         }                
         
         if(!isSystemAdmin || Test.isRunningTest()){
             
            for(Attachments_New__c objAttachment : [SELECT Id,Related_Id__c
                                                    FROM Attachments_New__c
                                                    WHERE Id =: setRelatedAttachments]){
            
                if(String.isNotBlank(objAttachment.Related_Id__c) && objAttachment.Related_Id__c InstanceOf Id && 
                    String.valueof(Id.valueof(objAttachment.Related_Id__c).getSobjectType()) == 'DIR_Case__c'){
                        
                        mapAttachmentIdToRelatedCase.put(objAttachment.Id,objAttachment.Related_Id__c);
                        
                }
            }
            
            
            
            for(DIR_Case__c objCase : [SELECT Id
                                       FROM DIR_Case__c
                                       WHERE Id =: mapAttachmentIdToRelatedCase.values()
                                       AND(Purge_Date__c = Null OR Purge_Date__c < TODAY)]){
                                       
                 setCaseIds.add(objCase.Id);                      
            }
            

            for(ContentDocumentLink objCDL : filteredCDL){
                
                if(mapAttachmentIdToRelatedCase.containsKey(objCDL.LinkedEntityId) && 
                    setCaseIds.contains(mapAttachmentIdToRelatedCase.get(objCDL.LinkedEntityId))){ 
                    
                    objCDL.addError('Only system administrators can delete historical attachments.');
                }
            }
            
         }
    }
}