force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Class_Title_CodeNo__c.field-meta.xml
<CustomField>
    <fullName>Class_Title_CodeNo__c</fullName>
    <label>Class Title CodeNo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Reporting_Unit_CodeNo__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Unit_CodeNo__c</fullName>
    <label>Reporting Unit CodeNo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial #</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/position_Extension_Test.cls
@isTest
(SeeAllData = true)
public with sharing class position_Extension_Test {
    public static testMethod void position_extension_UnitTest() {
        Position__c p = new Position__c();
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(p);
        position_Extension pe = new position_Extension(sc);
        pe.save();
        pe.searchUnit();
        pe.searchClassification();
        
        pe.position.Reporting_Unit_CodeNo__c = 'xxx';
        pe.position.Class_Title_CodeNo__c = 'xxxx';
        pe.searchUnit();
        pe.searchClassification();
        
        pe.position.Reporting_Unit_CodeNo__c = '152';
        pe.position.Class_Title_CodeNo__c = '1441';
        pe.position.Serial_Number__c = '909';
        pe.searchUnit();
        pe.searchClassification();
        
        pe.createForm1Onload();
        position_Extension.formatString('0', 4);
    } 
}