force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>Division</description>
    <inlineHelpText>Select the Division</inlineHelpText>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin-Accounting</fullName>
            </value>
            <value>
                <fullName>Admin-Admin Services</fullName>
            </value>
            <value>
                <fullName>Admin-Budgets</fullName>
            </value>
            <value>
                <fullName>Admin-Business Serv</fullName>
            </value>
            <value>
                <fullName>Admin-Human Resources</fullName>
            </value>
            <value>
                <fullName>Admin-OIS</fullName>
            </value>
            <value>
                <fullName>Admin-RTWS</fullName>
            </value>
            <value>
                <fullName>CHSWC</fullName>
            </value>
            <value>
                <fullName>DAS</fullName>
            </value>
            <value>
                <fullName>DLSE</fullName>
            </value>
            <value>
                <fullName>DLSE-IWC</fullName>
            </value>
            <value>
                <fullName>DLSE-PWD/OD-Research</fullName>
            </value>
            <value>
                <fullName>DOSH</fullName>
            </value>
            <value>
                <fullName>DOSH-CFOI/OD-Research</fullName>
            </value>
            <value>
                <fullName>DOSH-OIIS/OD-Research</fullName>
            </value>
            <value>
                <fullName>DWC</fullName>
            </value>
            <value>
                <fullName>DWC-RTW/Claims Mgmt</fullName>
            </value>
            <value>
                <fullName>DWC-RTW/SELSP</fullName>
            </value>
            <value>
                <fullName>OD-Drug Formulary</fullName>
            </value>
            <value>
                <fullName>OD-Legal N</fullName>
            </value>
            <value>
                <fullName>OD-Legal S</fullName>
            </value>
            <value>
                <fullName>OD-PAGA</fullName>
            </value>
            <value>
                <fullName>OD-PIO/Communications</fullName>
            </value>
            <value>
                <fullName>Office of The Director</fullName>
            </value>
            <value>
                <fullName>OIS</fullName>
            </value>
            <value>
                <fullName>OSHAB</fullName>
            </value>
            <value>
                <fullName>OSHSB</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
            <value>
                <fullName>WCAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Reporting_Unit_CodeNo__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Unit_CodeNo__c</fullName>
    <label>Reporting Unit CodeNo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial #</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>HR - Lookup to HR unit names</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin-Accounting</fullName>
            </value>
            <value>
                <fullName>Admin-Admin Services</fullName>
            </value>
            <value>
                <fullName>Admin-Budgets</fullName>
            </value>
            <value>
                <fullName>Admin-Business Serv</fullName>
            </value>
            <value>
                <fullName>Admin-Human Resources</fullName>
            </value>
            <value>
                <fullName>Admin-OIS</fullName>
            </value>
            <value>
                <fullName>Admin-RTWS</fullName>
            </value>
            <value>
                <fullName>CHSWC</fullName>
            </value>
            <value>
                <fullName>DAS</fullName>
            </value>
            <value>
                <fullName>DLSE</fullName>
            </value>
            <value>
                <fullName>DLSE-IWC</fullName>
            </value>
            <value>
                <fullName>DLSE-PWD/OD-Research</fullName>
            </value>
            <value>
                <fullName>DLSR</fullName>
            </value>
            <value>
                <fullName>DOSH</fullName>
            </value>
            <value>
                <fullName>DOSH-CFOI/OD-Research</fullName>
            </value>
            <value>
                <fullName>DOSH-OIIS/OD-Research</fullName>
            </value>
            <value>
                <fullName>DWC</fullName>
            </value>
            <value>
                <fullName>DWC-RTW/Claims Mgmt</fullName>
            </value>
            <value>
                <fullName>DWC-RTW/SELSP</fullName>
            </value>
            <value>
                <fullName>OD-Drug Formulary</fullName>
            </value>
            <value>
                <fullName>OD-Legal N</fullName>
            </value>
            <value>
                <fullName>OD-Legal S</fullName>
            </value>
            <value>
                <fullName>OD-PAGA</fullName>
            </value>
            <value>
                <fullName>OD-PIO/Communications</fullName>
            </value>
            <value>
                <fullName>OD/Anti-Fraud Unit</fullName>
            </value>
            <value>
                <fullName>Office of The Director</fullName>
            </value>
            <value>
                <fullName>OSHAB</fullName>
            </value>
            <value>
                <fullName>OSHSB</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
            <value>
                <fullName>WCAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/position_Methods_Test.cls
@isTest
(SeeAllData = true)
public with sharing class position_Methods_Test {
    public static testMethod void position_Methods_UnitTest() {
        Unit__c unit = new Unit__c();
        unit.Division__c = 'TEST';
        unit.Name = '999';
        insert unit;
        
        Position__c p = new Position__c();
        p.Reporting_Unit_CodeNo__c = unit.Name;
        try {
            p.Serial_Number__c = 'asdf';
            insert p;
            p = new Position__c();
            p.Reporting_Unit_CodeNo__c = unit.Name;
        }
        catch (Exception e) {}
        try {
            p.Serial_Number__c = '123';
            insert p;
            p = new Position__c();
            p.Reporting_Unit_CodeNo__c = unit.Name;
        }
        catch (Exception e) {}
        p.Serial_Number__c = '909';
        p.Reporting_Unit_CodeNo__c = unit.Name;
        insert p;
        
        update p;
    }
}