force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the office that services this case</description>
    <inlineHelpText>Defines the office that will process this case.</inlineHelpText>
    <label>DIR Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Courthouse</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Refer_to_JEU__c.field-meta.xml
<CustomField>
    <fullName>Refer_to_JEU__c</fullName>
    <description>Use this to set the status of the JEU Referral.  Other information may be required based on the selection.</description>
    <inlineHelpText>Use this to set the status of the JEU Referral.  Other information may be required based on the selection.</inlineHelpText>
    <label>Refer to JEU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To populate Region field</description>
    <label>Zip Code</label>
    <referenceTo>Zip_Code__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to the DIR Employee object creating a hierarchial relationship between an employee and his or her manager. Used in code to modify the role hierarchy and dynamically build teams</description>
    <inlineHelpText>Select the employee&#39;s manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Manages these Employees</relationshipLabel>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The office the user is associated to. Related fields are used on output documents</description>
    <inlineHelpText>The office to which the employee is associated.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Internal Employees</relationshipLabel>
    <relationshipName>Internal_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position the employee holds</description>
    <inlineHelpText>Select the position the employee holds</inlineHelpText>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Senior Deputy</fullName>
            </value>
            <value>
                <fullName>Deputy</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>CIU</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Registration_Services</fullName>
                <label>Registration Services</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Inspection__c/DIR_Inspection__c.object-meta.xml
<CustomObject>
    <description>This object contains each inspection (Initial and Follow Up) against a BOFE Case.</description>
    <label>Inspection</label>
    <nameField>
        <displayFormat>INSP-{000000}</displayFormat>
        <label>Inspection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Inspection__c/fields/DIR_Case__c.field-meta.xml
<CustomField>
    <fullName>DIR_Case__c</fullName>
    <description>This field creates a Master-Detail relationship between an Inspection and the Case.  Not reparentable.</description>
    <inlineHelpText>This field creates a Master-Detail relationship between an Inspection and the Case.  Not reparentable.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Key_Value_Store__c/Key_Value_Store__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores keys and associated values for use in code so that changes can be made without modifying code whenever possible.</description>
    <label>Key Value Store</label>
</CustomObject>

force-app/main/default/objects/Key_Value_Store__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value associated with the key ( Name field )</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office_Zip_Code_Map__c/Office_Zip_Code_Map__c.object-meta.xml
<CustomObject>
    <description>Maps zip codes to office locations. Used for assigning records to offices based on zip codes</description>
    <label>Office-Zip Code Map</label>
    <nameField>
        <displayFormat>Map-{00000}</displayFormat>
        <label>Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Office-Zip Code Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Zip_Code_Map__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <description>The office that the zip code is assigned to</description>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Office-Zip Code Maps</relationshipLabel>
    <relationshipName>Office_Zip_Code_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Office_Zip_Code_Map__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>the zip code assigned to the office</description>
    <label>Zip Code</label>
    <referenceTo>Zip_Code__c</referenceTo>
    <relationshipLabel>Office-Zip Code Maps</relationshipLabel>
    <relationshipName>Office_Zip_Code_Maps</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Report_of_Labor_Code_Violation__c/Report_of_Labor_Code_Violation__c.object-meta.xml
<CustomObject>
    <description>This object contains individual reports of labor code violations as populated by the BOFE1 form by a reporting party.  Creation of a Report of Labor Law Violation dictates that a Case is created first.</description>
    <label>Report of Labor Law Violation</label>
    <nameField>
        <displayFormat>RLLV-{000000}</displayFormat>
        <label>RLLV ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reports of Labor Law Violations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_of_Labor_Code_Violation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This creates a Master-Detail relationship between a Report of Labor Code Violation and the Entity this Report of Labor Code Violation is against.  Reparentable.</description>
    <inlineHelpText>This creates a Master-Detail relationship between a Report of Labor Code Violation and the Entity this Report of Labor Code Violation is against.  Reparentable.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Reports_of_Labor_Code_Violations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Report_of_Labor_Code_Violation__c/fields/DIR_Case__c.field-meta.xml
<CustomField>
    <fullName>DIR_Case__c</fullName>
    <description>This establishes a Master-Detail relationship do the DIR Case.  A Case must be created logically before a report of labor code violation may be created.</description>
    <inlineHelpText>This establishes a Master-Detail relationship do the DIR Case.  A Case must be created logically before a report of labor code violation may be created.  Reparentable</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Reports of Labor Law Violations</relationshipLabel>
    <relationshipName>Reports_of_Labor_Code_Violations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DIRCaseAllTest.cls
@isTest
public with sharing class DIRCaseAllTest {
    
    private static testMethod void testUpdateCase(){
        
        Id caseRecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE Intake').getRecordTypeId();
        
        Office__c office = new Office__c();
        office.Name = 'Lucian832474';
        insert office;
        
        Zip_Code__c zip = new Zip_Code__c();
        zip.Name = '234889';
        insert zip;
        
        Office_Zip_Code_Map__c map1 = new Office_Zip_Code_Map__c();
        map1.Zip_Code__c = zip.Id;
        map1.Office__c = office.Id;
        insert map1;
        
        Account acc = new Account();
        acc.Name = 'name';
        acc.ShippingPostalCode = '234889';
        insert acc;
        
        test.startTest();
        
        DIR_Case__c c = new DIR_Case__c();
        c.Employer__c = acc.Id;
        c.RecordTypeId = caseRecordTypeId;
        insert c;
        
        DIR_Case__c c2 = [SELECT Id, Office__c FROM DIR_Case__c WHERE Id =: c.Id];
        system.assertEquals(office.Id, c2.Office__c);
        
        test.stopTest();
    }

    private static testMethod void testUpdateCaseReferToJEU(){
        
        Id caseRecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE Intake').getRecordTypeId();
        
        Office__c office = new Office__c();
        office.Name = 'Lucian832474';
        insert office;
        
        Zip_Code__c zip = new Zip_Code__c();
        zip.Name = '234889';
        insert zip;
        
        Office_Zip_Code_Map__c map1 = new Office_Zip_Code_Map__c();
        map1.Zip_Code__c = zip.Id;
        map1.Office__c = office.Id;
        insert map1;
        
        Account acc = new Account();
        acc.Name = 'name';
        acc.ShippingPostalCode = '234889';
        insert acc;
        
        test.startTest();
        
        DIR_Case__c c = new DIR_Case__c();
        c.Employer__c = acc.Id;
        c.RecordTypeId = caseRecordTypeId;
        c.Refer_to_JEU__c = 'Referred';
        insert c;
        
        DIR_Case__c c2 = [SELECT Id, Office__c FROM DIR_Case__c WHERE Id =: c.Id];
        system.assertEquals(office.Id, c2.Office__c);
        
        test.stopTest();
    }

    private static testMethod void testUpdateCaseExistingEmployer(){
        
        Id caseRecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE Intake').getRecordTypeId();
        
        Office__c office = new Office__c();
        office.Name = 'Lucian832474';
        insert office;
        
        Zip_Code__c zip = new Zip_Code__c();
        zip.Name = '234889';
        insert zip;
        
        Office_Zip_Code_Map__c map1 = new Office_Zip_Code_Map__c();
        map1.Zip_Code__c = zip.Id;
        map1.Office__c = office.Id;
        insert map1;
        
        Account acc1 = new Account();
        acc1.Name = 'name';
        acc1.ShippingPostalCode = '234889';
        insert acc1;
        
        Account acc2 = new Account();
        acc2.Name = 'name2';
        acc2.ShippingPostalCode = '234889';
        insert acc2;
        
        DIR_Case__c existingCase = new DIR_Case__c();
        existingCase.Employer__c = acc1.Id;
        existingCase.RecordTypeId = caseRecordTypeId;
        insert existingCase;
        
        Report_of_Labor_Code_Violation__c rllv = new Report_of_Labor_Code_Violation__c();
        rllv.DIR_Case__c = existingCase.Id;
        rllv.Account__c = acc1.Id;
        insert rllv;

        test.startTest();
        
        existingCase.Employer__c = acc2.Id;
        update existingCase;
        
        rllv.Account__c = acc2.Id;
        update rllv;

        DIR_Case__c newCase = new DIR_Case__c();
        newCase.Employer__c = acc2.Id;
        newCase.RecordTypeId = caseRecordTypeId;
        insert newCase;
        

        existingCase = [SELECT Id, Employer__c, Office__c FROM DIR_Case__c WHERE Id =: existingCase.Id];
        newCase = [SELECT Id, Employer__c, Office__c FROM DIR_Case__c WHERE Id =: newCase.Id];
        
        system.debug('existingCase: ' + existingCase);
        system.debug('newCase: ' + newCase);
        system.assertEquals(existingCase.Employer__c, newCase.Employer__c);
        system.assertEquals(existingCase.Office__c, newCase.Office__c);
        
        test.stopTest();
    }
    
    /*
    private static testMethod void testUpdateCaseOwner(){
                
        Id caseRecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE Intake').getRecordTypeId();
        
        Profile p = [select id from profile where name='Standard User'];
        User u = new User(alias = 'standt', email='alex@vertiba.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p.Id,
                timezonesidkey='America/Los_Angeles', username='alex@testorg.com');
        insert u;
        
        User u2 = new User(alias = 'standt', email='alex@vertiba.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p.Id,
                timezonesidkey='America/Los_Angeles', username='alexa@testorg.com');
        insert u2;
        
        DIR_Employee__c ma = new DIR_Employee__c();
        ma.User__c = UserInfo.getUserId();
        insert ma; 
        
        DIR_Employee__c de = new DIR_Employee__c();
        de.Name = 'name';
        de.Position__c = 'Deputy';
        de.User__c = u.Id;
        de.Manager__c = ma.Id;
        insert de;
        
        DIR_Employee__c de2 = new DIR_Employee__c();
        de2.Name = 'name';
        de2.Position__c = 'Deputy';
        de2.User__c = u2.Id;
        de2.Manager__c = ma.Id;
        insert de2;
        
        DIR_Case__c c = new DIR_Case__c();
        c.RecordTypeId = caseRecordTypeId;
        c.Assigned_Deputy__c = de.Id;
        insert c;
        
        c.Assigned_Deputy__c = de2.Id;
        update c;
        
        //DIR_Case__c c2 = [SELECT Id, OwnerId FROM DIR_Case__c WHERE Id =: c.Id];
        //DIR_Employee__c de3 = [SELECT Id, User__c FROM DIR_Employee__c WHERE Id =: de.Id];
        
        
    }
    */
    
    private static testMethod void testUpdateLaborCodeViolations(){
        
        Id caseRecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE Intake').getRecordTypeId();
        Id caseRecordTypeId2 = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE Investigation').getRecordTypeId();

        Id caseRecordTypeId3 = RecordTypeUtil.getRecordTypeIDByName('DIR_Case__c', 'BOFE Investigation');
        Id caseRecordTypeId4 = RecordTypeUtil.getRecordTypeIDByName('DIR_Case__c', 'Lorem Ipsum');

        
        Key_Value_Store__c kvs = new Key_Value_Store__c();
        kvs.Name = 'BOFE Open Case RT';
        kvs.Value__c = 'BOFE Intake, BOFE Investigation';
        insert kvs;
        
        Profile p = [select id from profile where name='BOFE User'];
        
         User u = new User(alias = 'standt', email='alex@vertiba.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p.Id,
                timezonesidkey='America/Los_Angeles', username='testuser@ca-dir.com');
        insert u;

        DIR_Employee__c ma = new DIR_Employee__c();
        ma.User__c = UserInfo.getUserId();
        insert ma; 
        
        DIR_Employee__c de = new DIR_Employee__c();
        de.Name = 'name';
        de.Position__c = 'Deputy';
        de.User__c = u.Id;
        de.Manager__c = ma.Id;
        
        
        DIR_Employee__c de2 = de.clone();
        insert de2;
        insert de;

        Account acc = new Account();
        acc.Name = 'name';
        Account acc2 = new Account();
        acc2.Name = 'name2';
        Account acc3 = new Account();
        acc3.Name = 'name3';
        insert new List<Account> { acc, acc2, acc3 };
        
        
        DIR_Case__c c1 = new DIR_Case__c();
        c1.RecordTypeId = caseRecordTypeId;
        c1.Employer__c = acc.Id;
        c1.Assigned_Deputy__c = de.Id;
        insert c1;
        
        DIR_Case__c c = new DIR_Case__c();
        c.RecordTypeId = caseRecordTypeId;
        c.Employer__c = acc.Id;
        c.Assigned_Deputy__c = de.Id;
        DIR_Case__c c2 = new DIR_Case__c();
        c2.RecordTypeId = caseRecordTypeId;
        c2.Employer__c = acc2.Id;
        c2.Assigned_Deputy__c = de.Id;
        DIR_Case__c c3 = new DIR_Case__c();
        c3.RecordTypeId = caseRecordTypeId2;
        c3.Employer__c = acc3.Id;
        c3.Assigned_Deputy__c = de.id;
        insert new List<DIR_Case__c> { c, c2, c3 };
        
        
        Report_of_Labor_Code_Violation__c v = new Report_of_Labor_Code_Violation__c();
        v.DIR_Case__c = c.Id;
        v.Account__c = acc.Id;
        v.Source__c = 'Community Group Referral';
        v.Child_Labor_Violations__c = 'No valid work permit(s)';
        v.No_number_of_minors_affected__c = 5;
        Report_of_Labor_Code_Violation__c v2 = new Report_of_Labor_Code_Violation__c();
        v2.DIR_Case__c = c2.Id;
        v2.Account__c = acc2.Id;
        v2.Source__c = 'Community Group Referral';
        v2.Child_Labor_Violations__c = 'No valid work permit(s)';
        v2.No_number_of_minors_affected__c = 5;
        Report_of_Labor_Code_Violation__c v3 = new Report_of_Labor_Code_Violation__c();
        v3.DIR_Case__c = c3.Id;
        v3.Account__c = acc3.Id;
        v3.Source__c = 'Community Group Referral';
        v3.Child_Labor_Violations__c = 'No valid work permit(s)';
        v3.No_number_of_minors_affected__c = 5;
        insert new List<Report_of_Labor_Code_Violation__c> { v, v2, v3 };
        
        test.startTest();
        
        checkRecursive.run2 = true;
        c.Employer__c = acc2.Id;
        update c;
        
        insert new Assignment_History__c(Case_Management__c = c1.id);
        c1.Status__c = 'Closed - No further action';
        update c1;
        
        DIRCaseTriggerHandler.preventDuplicateHistoryCreations = true;
        c1.Status__c = 'Reopened with Senior Approval';
        update c1;

        DIR_Case__c c4 = [SELECT Id FROM DIR_Case__c WHERE Id =: c2.Id];
        Report_of_Labor_Code_Violation__c v4 = [SELECT Id, DIR_Case__c FROM Report_of_Labor_Code_Violation__c WHERE Id =: v.Id];
        //system.assertEquals(v4.DIR_Case__c, c4.Id);

        c3.Employer__c = acc2.Id;
        update c3;
        
        test.stopTest();
    }

    private static testMethod void testUpdateLaborCodeViolations2(){
        
        Id caseRecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE Intake').getRecordTypeId();
        Id caseRecordTypeId2 = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE Investigation').getRecordTypeId();
        
        Key_Value_Store__c kvs = new Key_Value_Store__c();
        kvs.Name = 'BOFE Open Case RT';
        kvs.Value__c = 'BOFE Intake, BOFE Investigation';
        insert kvs;
        
        Profile p = [select id from profile where name='BOFE User'];
        User u = new User(alias = 'standt', email='alex@vertiba.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p.Id,
                timezonesidkey='America/Los_Angeles', username='testuser1@ca-dir.com');
        insert u;

        DIR_Employee__c ma = new DIR_Employee__c();
        ma.User__c = UserInfo.getUserId();
        insert ma; 
        
        DIR_Employee__c de = new DIR_Employee__c();
        de.Name = 'name';
        de.Position__c = 'Deputy';
        de.User__c = u.Id;
        de.Manager__c = ma.Id;
        insert de;
        
        DIR_Employee__c de2 = de.clone();
        insert de2;

        Account acc = new Account();
        acc.Name = 'name';
        Account acc2 = new Account();
        acc2.Name = 'name2';
        Account acc3 = new Account();
        acc3.Name = 'name3';
        insert new List<Account> { acc, acc2, acc3 };
        
        DIR_Case__c c = new DIR_Case__c();
        c.RecordTypeId = caseRecordTypeId;
        c.Employer__c = acc.Id;
        c.Assigned_Deputy__c = de.Id;
        DIR_Case__c c2 = new DIR_Case__c();
        c2.RecordTypeId = caseRecordTypeId2;
        c2.Employer__c = acc2.Id;
        c2.Assigned_Deputy__c = de.id;
        DIR_Case__c c3 = new DIR_Case__c();
        c3.RecordTypeId = caseRecordTypeId2;
        c3.Employer__c = acc3.Id;
        c3.Assigned_Deputy__c = de.id;
        DIRCaseTriggerHandler.preventDuplicateHistoryCreations = true;
        insert new List<DIR_Case__c> { c, c2, c3 };
        
        Report_of_Labor_Code_Violation__c v = new Report_of_Labor_Code_Violation__c();
        v.DIR_Case__c = c.Id;
        v.Account__c = acc.Id;
        v.Source__c = 'Community Group Referral';
        v.Child_Labor_Violations__c = 'No valid work permit(s)';
        v.No_number_of_minors_affected__c = 5;
        Report_of_Labor_Code_Violation__c v2 = new Report_of_Labor_Code_Violation__c();
        v2.DIR_Case__c = c2.Id;
        v2.Account__c = acc2.Id;
        v2.Source__c = 'Community Group Referral';
        v2.Child_Labor_Violations__c = 'No valid work permit(s)';
        v2.No_number_of_minors_affected__c = 5;
        Report_of_Labor_Code_Violation__c v3 = new Report_of_Labor_Code_Violation__c();
        v3.DIR_Case__c = c3.Id;
        v3.Account__c = acc3.Id;
        v3.Source__c = 'Community Group Referral';
        v3.Child_Labor_Violations__c = 'No valid work permit(s)';
        v3.No_number_of_minors_affected__c = 5;
        insert new List<Report_of_Labor_Code_Violation__c> { v, v2, v3 };

        DIR_Inspection__c insp = new DIR_Inspection__c();
        insp.DIR_Case__c = c3.Id;
        insert insp;
        
        test.startTest();
        
        checkRecursive.run2 = true;
        c2.Employer__c = acc3.Id;
        c2.Assigned_Deputy__c = de2.id;
        DIRCaseTriggerHandler.preventDuplicateHistoryCreations = true;
        update c2;
        
        DIR_Case__c c4 = [SELECT Id FROM DIR_Case__c WHERE Id =: c2.Id];
        Report_of_Labor_Code_Violation__c v4 = [SELECT Id, DIR_Case__c FROM Report_of_Labor_Code_Violation__c WHERE Id =: v.Id];
        //system.assertEquals(v4.DIR_Case__c, c4.Id);
        
        
        test.stopTest();
        
        try{
            delete c;
        }
        catch(exception ex){
            
        }
    }
    
    public void testUpdateCaseOwnerManager(){
        
        Profile p = [select id from profile where name='Standard User'];
        User u = new User(alias = 'standt', email='alex@vertiba.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p.Id,
                timezonesidkey='America/Los_Angeles', username='alex@testorg.com');
        insert u;
        User u2 = new User(alias = 'standt', email='alex2@vertiba.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p.Id,
                timezonesidkey='America/Los_Angeles', username='alex2@testorg.com', ManagerId = u.Id);
        insert u2;
        
        Account acc = new Account();
        acc.Name = 'name';
        insert acc;
        
        test.startTest();
        
        DIR_Case__c c = new DIR_Case__c();
        c.Employer__c = acc.Id;
        c.OwnerId = u2.Id;
        insert c;
        
        DIR_Case__c c2 = [SELECT Id, Owner_s_Manager__c FROM DIR_Case__c WHERE Id =: c.Id];
        system.assertEquals(c2.Owner_s_Manager__c, u.Id);
        
        test.stopTest();
    }

}