force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Court_Case_Number_for_PAGA_Case__c.field-meta.xml
<CustomField>
    <fullName>Court_Case_Number_for_PAGA_Case__c</fullName>
    <description>For PAGA Cases, this is the PAGA Case Number.</description>
    <inlineHelpText>For PAGA Cases, this is the PAGA Case Number.</inlineHelpText>
    <label>Court Case Number for PAGA Case</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Court_Filing_Date_for_PAGA_Cases__c.field-meta.xml
<CustomField>
    <fullName>Court_Filing_Date_for_PAGA_Cases__c</fullName>
    <label>Court Filing Date for PAGA Case</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Court_Name__c.field-meta.xml
<CustomField>
    <fullName>Court_Name__c</fullName>
    <inlineHelpText>If selecting Other / Specify, please enter the court name in the Court Name for PAGA Case field.</inlineHelpText>
    <label>Court Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Court_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alameda County Superior Court</fullName>
            </value>
            <value>
                <fullName>Alpine County Superior Court</fullName>
            </value>
            <value>
                <fullName>Amador County Superior Court</fullName>
            </value>
            <value>
                <fullName>Butte County Superior Court</fullName>
            </value>
            <value>
                <fullName>Calaveras County Superior Court</fullName>
            </value>
            <value>
                <fullName>Colusa County Superior Court</fullName>
            </value>
            <value>
                <fullName>Contra Costa County Superior Court</fullName>
            </value>
            <value>
                <fullName>Del Norte County Superior Court</fullName>
            </value>
            <value>
                <fullName>El Dorado County Superior Court</fullName>
            </value>
            <value>
                <fullName>Fresno County Superior Court</fullName>
            </value>
            <value>
                <fullName>Glenn County Superior Court</fullName>
            </value>
            <value>
                <fullName>Humboldt County Superior Court</fullName>
            </value>
            <value>
                <fullName>Imperial County Superior Court</fullName>
            </value>
            <value>
                <fullName>Inyo County Superior Court</fullName>
            </value>
            <value>
                <fullName>Kern County Superior Court</fullName>
            </value>
            <value>
                <fullName>Kings County Superior Court</fullName>
            </value>
            <value>
                <fullName>Lake County Superior Court</fullName>
            </value>
            <value>
                <fullName>Lassen County Superior Court</fullName>
            </value>
            <value>
                <fullName>Los Angeles County Superior Court</fullName>
            </value>
            <value>
                <fullName>Madera County Superior Court</fullName>
            </value>
            <value>
                <fullName>Marin County Superior Court</fullName>
            </value>
            <value>
                <fullName>Mariposa County Superior Court</fullName>
            </value>
            <value>
                <fullName>Mendocino County Superior Court</fullName>
            </value>
            <value>
                <fullName>Merced County Superior Court</fullName>
            </value>
            <value>
                <fullName>Modoc County Superior Court</fullName>
            </value>
            <value>
                <fullName>Mono County Superior Court</fullName>
            </value>
            <value>
                <fullName>Monterey County Superior Court</fullName>
            </value>
            <value>
                <fullName>Napa County Superior Court</fullName>
            </value>
            <value>
                <fullName>Nevada County Superior Court</fullName>
            </value>
            <value>
                <fullName>Orange County Superior Court</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Court_Type__c.field-meta.xml
<CustomField>
    <fullName>Court_Type__c</fullName>
    <label>Court Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>California Appellate Courts</fullName>
            </value>
            <value>
                <fullName>California Superior Courts</fullName>
            </value>
            <value>
                <fullName>Federal Courts</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/LWDA_Number__c.field-meta.xml
<CustomField>
    <fullName>LWDA_Number__c</fullName>
    <description>If PAGA then it will have an LWDA#</description>
    <inlineHelpText>If PAGA then it will have an LWDA number.</inlineHelpText>
    <label>LWDA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/PAGA_Investigation_Decision_Date__c.field-meta.xml
<CustomField>
    <fullName>PAGA_Investigation_Decision_Date__c</fullName>
    <description>Investigation Decision Date - 52203. This is manually set.</description>
    <inlineHelpText>This is the date the certified letter notifying parties of the intent to investigate. This is manually set.</inlineHelpText>
    <label>Date of Notice of Intent to Investigate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Submission_Detail_Type__c.field-meta.xml
<CustomField>
    <fullName>Submission_Detail_Type__c</fullName>
    <label>Submission Detail Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subpoena</fullName>
            </value>
            <value>
                <fullName>OTA</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>L&amp;R/RCI/CIU</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>PAGA Notice</fullName>
            </value>
            <value>
                <fullName>Amended Notice</fullName>
            </value>
            <value>
                <fullName>Employer Response/Cure</fullName>
            </value>
            <value>
                <fullName>Cure Dispute</fullName>
            </value>
            <value>
                <fullName>Court Complaint</fullName>
            </value>
            <value>
                <fullName>Proposed Settlement</fullName>
            </value>
            <value>
                <fullName>Court Order/Judgment</fullName>
            </value>
            <value>
                <fullName>Other PAGA Document</fullName>
            </value>
            <value>
                <fullName>In Forma Pauperis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <label>Violation Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Labor Relations</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Labor Code 3070 – 3098</fullName>
            </value>
            <value>
                <fullName>Child Labor</fullName>
            </value>
            <value>
                <fullName>Classified as Independent Contractor</fullName>
            </value>
            <value>
                <fullName>Improper or Incomplete Wage Statements</fullName>
            </value>
            <value>
                <fullName>Improper payment form incl. NSF check</fullName>
            </value>
            <value>
                <fullName>Industrial Homework</fullName>
            </value>
            <value>
                <fullName>Kickbacks</fullName>
            </value>
            <value>
                <fullName>Lactation Accommodation (LC 1030‐1033)</fullName>
            </value>
            <value>
                <fullName>Licensing, Registration or Permit</fullName>
            </value>
            <value>
                <fullName>Meal and Rest Breaks</fullName>
            </value>
            <value>
                <fullName>Minimum Wage</fullName>
            </value>
            <value>
                <fullName>Nonexempt Classified as Exempt</fullName>
            </value>
            <value>
                <fullName>Not paid for all hours worked</fullName>
            </value>
            <value>
                <fullName>Not Paid Wages Due on Termination</fullName>
            </value>
            <value>
                <fullName>Not providing required time off, other</fullName>
            </value>
            <value>
                <fullName>No Wage Statements</fullName>
            </value>
            <value>
                <fullName>No Workers’ Compensation</fullName>
            </value>
            <value>
                <fullName>Occupational SAFE HLTH (LC 6300 et seq)</fullName>
            </value>
            <value>
                <fullName>Other Notice or Posting or Recordkeeping</fullName>
            </value>
            <value>
                <fullName>Other Unpaid Wages</fullName>
            </value>
            <value>
                <fullName>Overtime</fullName>
            </value>
            <value>
                <fullName>Pay Discrim on basis of sex (LC1197.5)</fullName>
            </value>
            <value>
                <fullName>PMNT Reimbursement of Empl Expenses</fullName>
            </value>
            <value>
                <fullName>Public Works (Labor Code §§ 1720 – 1815)</fullName>
            </value>
            <value>
                <fullName>Retaliation - Protected Status Activity</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Tips or Gratuities</fullName>
            </value>
            <value>
                <fullName>Unfair Immigration Activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Violation_Type__c/Violation_Type__c.object-meta.xml
<CustomObject>
    <description>Holds the types of violations that are used on Case Management cases. Records here become &quot;Case Violation&quot; records when a violation is recorded by a deputy or inspector.</description>
    <label>Violation Type</label>
    <nameField>
        <label>Labor Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Violation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Violation_Type__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <description>Defines the form on which this violation should appear. Used within the violations vfp to group violations into an assessment. All violations created at the same time on a case with the same Citation Form are grouped into a single assessment</description>
    <inlineHelpText>Select the citation form that this violation should appear on. Note that this is for grouping purposes and may not be an actual citation. For example, a NTD would be a citation form even though a penalty may not be levied.</inlineHelpText>
    <label>Citation Form</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BOFE 240A</fullName>
            </value>
            <value>
                <fullName>BOFE 240B</fullName>
            </value>
            <value>
                <fullName>BOFE 335</fullName>
            </value>
            <value>
                <fullName>BOFE 336</fullName>
            </value>
            <value>
                <fullName>BOFE 8</fullName>
            </value>
            <value>
                <fullName>BOFE 812</fullName>
            </value>
            <value>
                <fullName>BOFE 814</fullName>
            </value>
            <value>
                <fullName>BOFE 815</fullName>
            </value>
            <value>
                <fullName>BOFE 816</fullName>
            </value>
            <value>
                <fullName>JEU 238</fullName>
            </value>
            <value>
                <fullName>JEU 238e</fullName>
            </value>
            <value>
                <fullName>LR 240A</fullName>
            </value>
            <value>
                <fullName>Notice to Discontinue - DLSE 84</fullName>
            </value>
            <value>
                <fullName>PW 240A</fullName>
            </value>
            <value>
                <fullName>PW 336</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PAGASearchController.cls
/********************************************************************************************************
Name:  PAGASearchController.cls
Author:  Mirela Chituc (mirela.chituc@vertiba.com)
Date:  08/08/2017
VF Page: PAGASearch.page
Test class: PAGASearchControllerTest.cls


Behavior:
    Filter cases search by case attributes so that it can narrow down to particular cases user is looking for. 
    Case attributes include Date Range of PAGA Notice Filed, employer city, employer zip code, court name, 
    court case number, and the type of violation.
       
********************************************************************************************************/

global class PAGASearchController {
    
    // dummy DIR Case Record
    public DIR_Case__c dummyCase {get; set;}
    
    public String searchString {get; set;}
    public String employeeCity {get; set;}
    public String employeeZipCode {get; set;}
    
    // class constructor, executes first, as soon as the class is invoked
    global PAGASearchController() {
        Id pagaRTId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('PAGA Case').getRecordTypeId();
        if(dummyCase == null) {
            dummyCase = new DIR_Case__c();
            dummyCase.recordTypeId = pagaRTId;
        }
        searchString = '';
    }
    
    // clears all the fields on Search page
    public void ClearFields() {
        dummyCase = new DIR_Case__c();
        searchString = '';
        employeeCity = '';
        employeeZipCode = '';
    } 
    
    
    // sends all inserted values as parameters and rediredcts to PAGASearchResults.page
    public PageReference SearchCases() {
        
        PageReference resultsPage = new PageReference('/apex/PAGASearchResults');
        if(!String.isEmpty(searchString)) 
            resultsPage.getParameters().put('ss', searchString);
        if(!String.isEmpty(dummyCase.LWDA_Number__c)) 
            resultsPage.getParameters().put('lwn', dummyCase.LWDA_Number__c);
        if(dummyCase.PAGA_Investigation_Decision_Date__c != null) 
            resultsPage.getParameters().put('sd', String.valueof(dummyCase.PAGA_Investigation_Decision_Date__c));
        if(dummyCase.Court_Filing_Date_for_PAGA_Cases__c != null)
            resultsPage.getParameters().put('ed', String.valueof(dummyCase.Court_Filing_Date_for_PAGA_Cases__c));
        if(!String.isEmpty(employeeCity)) 
            resultsPage.getParameters().put('ec', employeeCity);
        if(!String.isEmpty(employeeZipCode)) 
            resultsPage.getParameters().put('ezc', employeeZipCode);
        if(!String.isEmpty(dummyCase.Court_Case_Number_for_PAGA_Case__c)) 
            resultsPage.getParameters().put('ccn', dummyCase.Court_Case_Number_for_PAGA_Case__c);
        if(!String.isEmpty(dummyCase.Court_Type__c)) 
            resultsPage.getParameters().put('ct', dummyCase.Court_Type__c);
        if(!String.isEmpty(dummyCase.Court_Name__c)) 
            resultsPage.getParameters().put('cn', dummyCase.Court_Name__c);
        if(!String.isEmpty(dummyCase.Violation_Type__c)) 
            resultsPage.getParameters().put('vt', dummyCase.Violation_Type__c);
        if(!String.isEmpty(dummyCase.Submission_Detail_Type__c)) 
            resultsPage.getParameters().put('st', dummyCase.Submission_Detail_Type__c);
        resultsPage.setRedirect(true);
        return resultsPage;
    }
}