force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Bank_Location__c.field-meta.xml
<CustomField>
    <fullName>Bank_Location__c</fullName>
    <description>For location of bank.</description>
    <label>Bank Location</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Defines if a role is currently active.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to the DIR Employee object creating a hierarchial relationship between an employee and his or her manager. Used in code to modify the role hierarchy and dynamically build teams</description>
    <inlineHelpText>Select the employee&#39;s manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Manages these Employees</relationshipLabel>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position the employee holds</description>
    <inlineHelpText>Select the position the employee holds</inlineHelpText>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Senior Deputy</fullName>
            </value>
            <value>
                <fullName>Deputy</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>CIU</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Registration_Services</fullName>
                <label>Registration Services</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <description>Represents a receivable: an incoming payment, or an advice of incoming funds. [Encompasses the former Payment Log, Payment Group and Receipt objects to 1 single object.]</description>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RCT-{0000000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Add_Deduction__c.field-meta.xml
<CustomField>
    <fullName>Add_Deduction__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Add if the current check has any deductions</description>
    <label>Add Deduction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Bank_Location__c.field-meta.xml
<CustomField>
    <fullName>Bank_Location__c</fullName>
    <description>Picklist field allows users to designate whether the bank is out of state or in CA</description>
    <label>Bank Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA Bank</fullName>
            </value>
            <value>
                <fullName>Out of State Bank</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <description>Required date field that captures the date of receipt on a payment</description>
    <label>Date Received</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Deduction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deduction_Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Deduction amount if any</description>
    <label>Deduction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>Gross_Amount__c</fullName>
    <description>Total Gross Amount</description>
    <label>Gross Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Instrument_Number__c.field-meta.xml
<CustomField>
    <fullName>Instrument_Number__c</fullName>
    <description>Field for capturing the Id number on a check or an instrument.
Old API - Check_Instrument_Number__c</description>
    <label>Instrument Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Office_Unit__c.field-meta.xml
<CustomField>
    <fullName>Office_Unit__c</fullName>
    <description>Picklist field that allows user to designate the Office Unit on the Payment record.</description>
    <label>Office Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCU 32</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>WCA 1</fullName>
            </value>
            <value>
                <fullName>WCA 4</fullName>
            </value>
            <value>
                <fullName>WCA 5</fullName>
            </value>
            <value>
                <fullName>WCA 6</fullName>
            </value>
            <value>
                <fullName>WCA 7</fullName>
            </value>
            <value>
                <fullName>WCA 8</fullName>
            </value>
            <value>
                <fullName>WCA 9</fullName>
            </value>
            <value>
                <fullName>WCA 10</fullName>
            </value>
            <value>
                <fullName>WCA 11</fullName>
            </value>
            <value>
                <fullName>WCA 12</fullName>
            </value>
            <value>
                <fullName>WCA 13</fullName>
            </value>
            <value>
                <fullName>WCA 14</fullName>
            </value>
            <value>
                <fullName>WCA 15</fullName>
            </value>
            <value>
                <fullName>WCA 17</fullName>
            </value>
            <value>
                <fullName>WCA 18</fullName>
            </value>
            <value>
                <fullName>WCA 23</fullName>
            </value>
            <value>
                <fullName>WCA 633</fullName>
            </value>
            <value>
                <fullName>RCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>Required field for capturing the payment amount</description>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Can_Be_Processed__c.field-meta.xml
<CustomField>
    <fullName>Payment_Can_Be_Processed__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Use to hide/unhide the reason fields on ICL. (replacing the field &quot;Can Payment Be Processed?&quot;</description>
    <label>Payment Can Be Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Exchange__c.field-meta.xml
<CustomField>
    <fullName>Payment_Exchange__c</fullName>
    <description>Defines to whom the payment was directed.</description>
    <label>Payment Exchange</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Division Payment</fullName>
            </value>
            <value>
                <fullName>Direct Payment</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
            <value>
                <fullName>Party to Party</fullName>
            </value>
            <value>
                <fullName>Reversal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>Picklist field for designating the payment type</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>EFT</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Cashier&#39;s Check</fullName>
            </value>
            <value>
                <fullName>Money Order</fullName>
            </value>
            <value>
                <fullName>State Warrant</fullName>
            </value>
            <value>
                <fullName>State Warrant - Returned by USPS</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Index__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Index__c</fullName>
    <label>Receipt Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ReceiptsGridControllerTest.cls
@isTest
public class ReceiptsGridControllerTest {
    
    static testmethod void testSaveRctCaseServer(){
        User ADMIN_USER = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];
        
        DIR_Employee__c mgr = new DIR_Employee__c(
            Active__c = true,
            User__c = ADMIN_USER.Id,
            Position__c = 'Cashiering'
        );
        insert mgr;
        
        DIR_Employee__c emp = new DIR_Employee__c(
            Active__c = true,
            User__c = ADMIN_USER.Id,
            Manager__c = mgr.Id
        );
        insert emp;
        
        Account acc = new Account();
        acc.Name = 'name';
        acc.ShippingPostalCode = '234889';
        acc.Bankruptcy_Status_Date__c = Date.today();
        insert acc;
        
        DIR_Case__c c1 = new DIR_Case__c();
        c1.Employer__c = acc.Id;
        c1.Assigned_Deputy__c = emp.Id;
        insert c1;
        
        DIR_Case__c c2 = new DIR_Case__c();
        c2.Employer__c = acc.Id;
        c2.Assigned_Deputy__c = emp.Id;
        insert c2;

        Map<String,Object> receipt1 = new Map<String,Object>();
        receipt1.put('"Receipt_Index__c"', 0);
        receipt1.put('"Payment_Type__c"', '"Check"');
        receipt1.put('"Instrument_Number__c"', '"TestCheck1"');
        receipt1.put('"Date_Received__c"', '"'+String.valueOf(Date.today()).removeEnd(' 00:00:00')+'"');
        receipt1.put('"Bank_Location__c"', '"CA Bank"');
        receipt1.put('"Payment_Exchange__c"', '"Division Payment"');
        receipt1.put('"Payment_Amount__c"', '"250"');
        receipt1.put('"Office_Unit__c"', '"CCU 32"');
        receipt1.put('"Payment_Can_Be_Processed__c"', true);
        System.debug('----------------------------------------receipt1------------------------------------------');
        System.debug(receipt1);
        
        Map<String,Object> receipt2 = new Map<String,Object>();
        receipt2.put('"Receipt_Index__c"', 1);
        receipt2.put('"Payment_Type__c"', '"Check"');
        receipt2.put('"Instrument_Number__c"', '"TestCheck2"');
        receipt2.put('"Date_Received__c"', '"'+String.valueOf(Date.today()).removeEnd(' 00:00:00')+'"');
        receipt2.put('"Bank_Location__c"', '"CA Bank"');
        receipt2.put('"Payment_Exchange__c"', '"Division Payment"');
        //receipt2.put('"Add_Deduction__c"', true);
        //receipt2.put('"Gross_Amount__c"', '"350"');
        receipt2.put('"Payment_Amount__c"', '"250"');
        //receipt2.put('"Deduction_Amount__c"', '"100"');
        receipt2.put('"Office_Unit__c"', '"CCU 32"');
        receipt2.put('"Payment_Can_Be_Processed__c"', true);
        System.debug('----------------------------------------receipt2------------------------------------------');
        System.debug(receipt2);
       
        List<Object> listRct = new List<Object>();
        listRct.add(receipt1);
        listRct.add(receipt2);
        System.debug('----------------------------------------Receipt List-------------------------------');
        System.debug(listRct);
        
        Map<String,Object> casePayment1 = new Map<String,Object>();
        casePayment1.put('"CP_Index__c"', 0);
        casePayment1.put('"Case__c"' , '"'+c1.id+'"'); 
        casePayment1.put('"Payment_Amount__c"', '"150"');
        casePayment1.put('"Receipt__c"', '""');
        casePayment1.put('"Status__c"' , '"New"');
        casePayment1.put('"Deduction_Payment__c"' , '""');
        System.debug('----------------------------------------Case Payment1------------------------------------------');
        System.debug(casePayment1);
        
        List<Object> listCase = new List<Object>();
        listCase.add(casePayment1);
        System.debug('----------------------------------------Case Payment List-------------------------------------');
        System.debug(listCase);
        
        System.runAs(ADMIN_USER){
            String rctList = string.valueOf(listRct).replace('=', ':').replace('(', '[').replace(')',']');
            String caseList = string.valueOf(listCase).replace('=', ':').replace('(', '[').replace(')',']');
            System.debug('----------------------------------------STRING-------------------------------------');
            System.debug(rctList);
            System.debug(caseList);
            
            ReceiptsGridController.saveReceiptCaseServer(rctList, caseList, false);
            ReceiptsGridController.getRecTypeIds();
        }
        
    }
    
}