force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Court_Filing_Date_for_PAGA_Cases__c.field-meta.xml
<CustomField>
    <fullName>Court_Filing_Date_for_PAGA_Cases__c</fullName>
    <label>Court Filing Date for PAGA Case</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Court_Name__c.field-meta.xml
<CustomField>
    <fullName>Court_Name__c</fullName>
    <inlineHelpText>If selecting Other / Specify, please enter the court name in the Court Name for PAGA Case field.</inlineHelpText>
    <label>Court Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Court_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alameda County Superior Court</fullName>
            </value>
            <value>
                <fullName>Alpine County Superior Court</fullName>
            </value>
            <value>
                <fullName>Amador County Superior Court</fullName>
            </value>
            <value>
                <fullName>Butte County Superior Court</fullName>
            </value>
            <value>
                <fullName>Calaveras County Superior Court</fullName>
            </value>
            <value>
                <fullName>Colusa County Superior Court</fullName>
            </value>
            <value>
                <fullName>Contra Costa County Superior Court</fullName>
            </value>
            <value>
                <fullName>Del Norte County Superior Court</fullName>
            </value>
            <value>
                <fullName>El Dorado County Superior Court</fullName>
            </value>
            <value>
                <fullName>Fresno County Superior Court</fullName>
            </value>
            <value>
                <fullName>Glenn County Superior Court</fullName>
            </value>
            <value>
                <fullName>Humboldt County Superior Court</fullName>
            </value>
            <value>
                <fullName>Imperial County Superior Court</fullName>
            </value>
            <value>
                <fullName>Inyo County Superior Court</fullName>
            </value>
            <value>
                <fullName>Kern County Superior Court</fullName>
            </value>
            <value>
                <fullName>Kings County Superior Court</fullName>
            </value>
            <value>
                <fullName>Lake County Superior Court</fullName>
            </value>
            <value>
                <fullName>Lassen County Superior Court</fullName>
            </value>
            <value>
                <fullName>Los Angeles County Superior Court</fullName>
            </value>
            <value>
                <fullName>Madera County Superior Court</fullName>
            </value>
            <value>
                <fullName>Marin County Superior Court</fullName>
            </value>
            <value>
                <fullName>Mariposa County Superior Court</fullName>
            </value>
            <value>
                <fullName>Mendocino County Superior Court</fullName>
            </value>
            <value>
                <fullName>Merced County Superior Court</fullName>
            </value>
            <value>
                <fullName>Modoc County Superior Court</fullName>
            </value>
            <value>
                <fullName>Mono County Superior Court</fullName>
            </value>
            <value>
                <fullName>Monterey County Superior Court</fullName>
            </value>
            <value>
                <fullName>Napa County Superior Court</fullName>
            </value>
            <value>
                <fullName>Nevada County Superior Court</fullName>
            </value>
            <value>
                <fullName>Orange County Superior Court</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Court_Type__c.field-meta.xml
<CustomField>
    <fullName>Court_Type__c</fullName>
    <label>Court Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>California Appellate Courts</fullName>
            </value>
            <value>
                <fullName>California Superior Courts</fullName>
            </value>
            <value>
                <fullName>Federal Courts</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Date_Case_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Case_Received__c</fullName>
    <description>Date Case Received</description>
    <label>Date Case Received</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Notice_Filing_Date__c.field-meta.xml
<CustomField>
    <fullName>Notice_Filing_Date__c</fullName>
    <label>Notice Filing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/PAGA_Court_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>PAGA_Court_Case_Number__c</fullName>
    <description>PAGA Court Case Number</description>
    <inlineHelpText>This is the court case number of the Private Attorney&#39;s civil case under the PAGA L.C. 2698.</inlineHelpText>
    <label>PAGA Court Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <label>Violation Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Labor Relations</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Labor Code 3070 – 3098</fullName>
            </value>
            <value>
                <fullName>Child Labor</fullName>
            </value>
            <value>
                <fullName>Classified as Independent Contractor</fullName>
            </value>
            <value>
                <fullName>Improper or Incomplete Wage Statements</fullName>
            </value>
            <value>
                <fullName>Improper payment form incl. NSF check</fullName>
            </value>
            <value>
                <fullName>Industrial Homework</fullName>
            </value>
            <value>
                <fullName>Kickbacks</fullName>
            </value>
            <value>
                <fullName>Lactation Accommodation (LC 1030‐1033)</fullName>
            </value>
            <value>
                <fullName>Licensing, Registration or Permit</fullName>
            </value>
            <value>
                <fullName>Meal and Rest Breaks</fullName>
            </value>
            <value>
                <fullName>Minimum Wage</fullName>
            </value>
            <value>
                <fullName>Nonexempt Classified as Exempt</fullName>
            </value>
            <value>
                <fullName>Not paid for all hours worked</fullName>
            </value>
            <value>
                <fullName>Not Paid Wages Due on Termination</fullName>
            </value>
            <value>
                <fullName>Not providing required time off, other</fullName>
            </value>
            <value>
                <fullName>No Wage Statements</fullName>
            </value>
            <value>
                <fullName>No Workers’ Compensation</fullName>
            </value>
            <value>
                <fullName>Occupational SAFE HLTH (LC 6300 et seq)</fullName>
            </value>
            <value>
                <fullName>Other Notice or Posting or Recordkeeping</fullName>
            </value>
            <value>
                <fullName>Other Unpaid Wages</fullName>
            </value>
            <value>
                <fullName>Overtime</fullName>
            </value>
            <value>
                <fullName>Pay Discrim on basis of sex (LC1197.5)</fullName>
            </value>
            <value>
                <fullName>PMNT Reimbursement of Empl Expenses</fullName>
            </value>
            <value>
                <fullName>Public Works (Labor Code §§ 1720 – 1815)</fullName>
            </value>
            <value>
                <fullName>Retaliation - Protected Status Activity</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Tips or Gratuities</fullName>
            </value>
            <value>
                <fullName>Unfair Immigration Activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Violation_Type__c/Violation_Type__c.object-meta.xml
<CustomObject>
    <description>Holds the types of violations that are used on Case Management cases. Records here become &quot;Case Violation&quot; records when a violation is recorded by a deputy or inspector.</description>
    <label>Violation Type</label>
    <nameField>
        <label>Labor Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Violation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Violation_Type__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <description>Defines the form on which this violation should appear. Used within the violations vfp to group violations into an assessment. All violations created at the same time on a case with the same Citation Form are grouped into a single assessment</description>
    <inlineHelpText>Select the citation form that this violation should appear on. Note that this is for grouping purposes and may not be an actual citation. For example, a NTD would be a citation form even though a penalty may not be levied.</inlineHelpText>
    <label>Citation Form</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BOFE 240A</fullName>
            </value>
            <value>
                <fullName>BOFE 240B</fullName>
            </value>
            <value>
                <fullName>BOFE 335</fullName>
            </value>
            <value>
                <fullName>BOFE 336</fullName>
            </value>
            <value>
                <fullName>BOFE 8</fullName>
            </value>
            <value>
                <fullName>BOFE 812</fullName>
            </value>
            <value>
                <fullName>BOFE 814</fullName>
            </value>
            <value>
                <fullName>BOFE 815</fullName>
            </value>
            <value>
                <fullName>BOFE 816</fullName>
            </value>
            <value>
                <fullName>JEU 238</fullName>
            </value>
            <value>
                <fullName>JEU 238e</fullName>
            </value>
            <value>
                <fullName>LR 240A</fullName>
            </value>
            <value>
                <fullName>Notice to Discontinue - DLSE 84</fullName>
            </value>
            <value>
                <fullName>PW 240A</fullName>
            </value>
            <value>
                <fullName>PW 336</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PAGASearchControllerTest.cls
@istest
public class PAGASearchControllerTest {

    public static testMethod void testPAGASearch1(){
        Account acc = new Account(
            Name = 'test acct 123',
            ShippingStreet = '123 fake st\r\nBldg A\r\nUnit A',
            ShippingCity = 'Denver',
            ShippingState = 'CO',
            ShippingPostalCode = '80212'
        );
        insert acc;
        
        Id RecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('PAGA Case').getRecordTypeId();
        
        DIR_Case__c dirCase1  = new DIR_Case__c();
        dirCase1.RecordTypeId = RecordTypeId;
        dirCase1.Employer__c = acc.Id;
        dirCase1.PAGA_Court_Case_Number__c = '333';
        dirCase1.Court_Type__c = 'Other';
        dirCase1.Court_Name__c = 'Other';
        dirCase1.Violation_Type__c = 'Child Labor';
        dirCase1.Date_Case_Received__c = Date.Today();
        insert dirCase1;
        
        
        test.startTest();
            PAGASearchController pagaSearch = new PAGASearchController();
            
            pagaSearch.employeeCity = 'Denver';
            pagaSearch.employeeZipCode = '80212';
            pagaSearch.dummyCase.PAGA_Court_Case_Number__c = '3333';
            pagaSearch.dummyCase.Court_Type__c = 'Other';
            pagaSearch.dummyCase.Court_Name__c = 'Other';
            pagaSearch.dummyCase.Violation_Type__c = 'Child Labor;';
            pagaSearch.dummyCase.Notice_Filing_Date__c = Date.Today().addDays(-4);
            pagaSearch.dummyCase.Court_Filing_Date_for_PAGA_Cases__c = Date.Today().addDays(4);
            pagaSearch.SearchCases();
            pagaSearch.ClearFields();
            
            
        test.stopTest();
    }
    
   
}