force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Case Number</description>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Court_Case_Number_for_PAGA_Case__c.field-meta.xml
<CustomField>
    <fullName>Court_Case_Number_for_PAGA_Case__c</fullName>
    <description>For PAGA Cases, this is the PAGA Case Number.</description>
    <inlineHelpText>For PAGA Cases, this is the PAGA Case Number.</inlineHelpText>
    <label>Court Case Number for PAGA Case</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Court_Type__c.field-meta.xml
<CustomField>
    <fullName>Court_Type__c</fullName>
    <label>Court Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>California Appellate Courts</fullName>
            </value>
            <value>
                <fullName>California Superior Courts</fullName>
            </value>
            <value>
                <fullName>Federal Courts</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer_Filer__c.field-meta.xml
<CustomField>
    <fullName>Employer_Filer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employer Filer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Management (Employer Filer)</relationshipLabel>
    <relationshipName>Case_Management3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer_Filer_Firm__c.field-meta.xml
<CustomField>
    <fullName>Employer_Filer_Firm__c</fullName>
    <label>Employer Filer Firm</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Filer_Attorney_for_PAGA_Case__c.field-meta.xml
<CustomField>
    <fullName>Filer_Attorney_for_PAGA_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Attorney for PAGA case</description>
    <inlineHelpText>Attorney for PAGA case</inlineHelpText>
    <label>Filer/Attorney for PAGA Case</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Management (Attorney for PAGA Case)</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Filer_for_Employer__c.field-meta.xml
<CustomField>
    <fullName>Filer_for_Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filer for Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Management (Filer for Employer)</relationshipLabel>
    <relationshipName>Case_Management2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Law_Firm_for_PAGA_Case__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm_for_PAGA_Case__c</fullName>
    <label>Law Firm for PAGA Plaintiff</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Legacy_PAGA_LWDA_Number__c.field-meta.xml
<CustomField>
    <fullName>Legacy_PAGA_LWDA_Number__c</fullName>
    <description>If PAGA then it will have an LWDA#</description>
    <inlineHelpText>If PAGA then it will have an LWDA number.</inlineHelpText>
    <label>Legacy PAGA LWDA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/LWDA_Number__c.field-meta.xml
<CustomField>
    <fullName>LWDA_Number__c</fullName>
    <description>If PAGA then it will have an LWDA#</description>
    <inlineHelpText>If PAGA then it will have an LWDA number.</inlineHelpText>
    <label>LWDA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Notice_Filing_Date__c.field-meta.xml
<CustomField>
    <fullName>Notice_Filing_Date__c</fullName>
    <label>Notice Filing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/PAGA_Court_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>PAGA_Court_Case_Number__c</fullName>
    <description>PAGA Court Case Number</description>
    <inlineHelpText>This is the court case number of the Private Attorney&#39;s civil case under the PAGA L.C. 2698.</inlineHelpText>
    <label>PAGA Court Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/PAGA_LWDA_Number__c.field-meta.xml
<CustomField>
    <fullName>PAGA_LWDA_Number__c</fullName>
    <description>PAGA LWDA Number</description>
    <displayFormat>{0000000}</displayFormat>
    <inlineHelpText>Labor and Workforce Development Agency case number.</inlineHelpText>
    <label>PAGA LWDA Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/PAGA_Status__c.field-meta.xml
<CustomField>
    <fullName>PAGA_Status__c</fullName>
    <label>PAGA Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Settlement Pending</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Plaintiff_for_PAGA__c.field-meta.xml
<CustomField>
    <fullName>Plaintiff_for_PAGA__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Plaintiff on PAGA Case</description>
    <label>Plaintiff for PAGA</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Management (Plaintiff for PAGA)</relationshipLabel>
    <relationshipName>Case_Management1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Plaintiff_for_PAGA_Case_Text__c.field-meta.xml
<CustomField>
    <fullName>Plaintiff_for_PAGA_Case_Text__c</fullName>
    <description>Hidden Field for text of Plaintiff Name.</description>
    <inlineHelpText>Hidden Field for text of Plaintiff Name.</inlineHelpText>
    <label>Plaintiff for PAGA Case</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <label>Violation Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Labor Relations</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Labor Code 3070 – 3098</fullName>
            </value>
            <value>
                <fullName>Child Labor</fullName>
            </value>
            <value>
                <fullName>Classified as Independent Contractor</fullName>
            </value>
            <value>
                <fullName>Improper or Incomplete Wage Statements</fullName>
            </value>
            <value>
                <fullName>Improper payment form incl. NSF check</fullName>
            </value>
            <value>
                <fullName>Industrial Homework</fullName>
            </value>
            <value>
                <fullName>Kickbacks</fullName>
            </value>
            <value>
                <fullName>Lactation Accommodation (LC 1030‐1033)</fullName>
            </value>
            <value>
                <fullName>Licensing, Registration or Permit</fullName>
            </value>
            <value>
                <fullName>Meal and Rest Breaks</fullName>
            </value>
            <value>
                <fullName>Minimum Wage</fullName>
            </value>
            <value>
                <fullName>Nonexempt Classified as Exempt</fullName>
            </value>
            <value>
                <fullName>Not paid for all hours worked</fullName>
            </value>
            <value>
                <fullName>Not Paid Wages Due on Termination</fullName>
            </value>
            <value>
                <fullName>Not providing required time off, other</fullName>
            </value>
            <value>
                <fullName>No Wage Statements</fullName>
            </value>
            <value>
                <fullName>No Workers’ Compensation</fullName>
            </value>
            <value>
                <fullName>Occupational SAFE HLTH (LC 6300 et seq)</fullName>
            </value>
            <value>
                <fullName>Other Notice or Posting or Recordkeeping</fullName>
            </value>
            <value>
                <fullName>Other Unpaid Wages</fullName>
            </value>
            <value>
                <fullName>Overtime</fullName>
            </value>
            <value>
                <fullName>Pay Discrim on basis of sex (LC1197.5)</fullName>
            </value>
            <value>
                <fullName>PMNT Reimbursement of Empl Expenses</fullName>
            </value>
            <value>
                <fullName>Public Works (Labor Code §§ 1720 – 1815)</fullName>
            </value>
            <value>
                <fullName>Retaliation - Protected Status Activity</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Tips or Gratuities</fullName>
            </value>
            <value>
                <fullName>Unfair Immigration Activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Violation_Type__c/Violation_Type__c.object-meta.xml
<CustomObject>
    <description>Holds the types of violations that are used on Case Management cases. Records here become &quot;Case Violation&quot; records when a violation is recorded by a deputy or inspector.</description>
    <label>Violation Type</label>
    <nameField>
        <label>Labor Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Violation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Violation_Type__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <description>Defines the form on which this violation should appear. Used within the violations vfp to group violations into an assessment. All violations created at the same time on a case with the same Citation Form are grouped into a single assessment</description>
    <inlineHelpText>Select the citation form that this violation should appear on. Note that this is for grouping purposes and may not be an actual citation. For example, a NTD would be a citation form even though a penalty may not be levied.</inlineHelpText>
    <label>Citation Form</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BOFE 240A</fullName>
            </value>
            <value>
                <fullName>BOFE 240B</fullName>
            </value>
            <value>
                <fullName>BOFE 335</fullName>
            </value>
            <value>
                <fullName>BOFE 336</fullName>
            </value>
            <value>
                <fullName>BOFE 8</fullName>
            </value>
            <value>
                <fullName>BOFE 812</fullName>
            </value>
            <value>
                <fullName>BOFE 814</fullName>
            </value>
            <value>
                <fullName>BOFE 815</fullName>
            </value>
            <value>
                <fullName>BOFE 816</fullName>
            </value>
            <value>
                <fullName>JEU 238</fullName>
            </value>
            <value>
                <fullName>JEU 238e</fullName>
            </value>
            <value>
                <fullName>LR 240A</fullName>
            </value>
            <value>
                <fullName>Notice to Discontinue - DLSE 84</fullName>
            </value>
            <value>
                <fullName>PW 240A</fullName>
            </value>
            <value>
                <fullName>PW 336</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PAGAPrintController.cls
/********************************************************************************************************
Name:  PAGAPrintController.cls
Author:  Mirela Chituc (mirela.chituc@vertiba.com)
Date:  08/14/2017
VF Page: PAGAPrint.page
Test class: PAGAPrintControllerTest.cls

Behavior:
    Display PAGA Case as pdf (print document)
       
********************************************************************************************************/

public with sharing class PAGAPrintController {
    public DIR_Case__c currentCase {get; set;}
    private String currentCaseId;
    public List<DIR_Case__c> allResultCases {get; set;}
    
     // class constructor, executes first, as soon as the class is invoked
    public PAGAPrintController(){
        // get values from url parameters
        currentCaseId = ApexPages.currentPage().getParameters().get('Id');
        String eSearch = ApexPages.currentPage().getParameters().get('ss');
        String lwNumber = ApexPages.currentPage().getParameters().get('lwn');
        String sDate = ApexPages.currentPage().getParameters().get('sd');
        String eDate = ApexPages.currentPage().getParameters().get('ed');
        String eName = ApexPages.currentPage().getParameters().get('en');
        String eFiler = ApexPages.currentPage().getParameters().get('ef');
        String lawFirm = ApexPages.currentPage().getParameters().get('lf');
        String eCity = ApexPages.currentPage().getParameters().get('city');
        String eZipCode = ApexPages.currentPage().getParameters().get('zip');
        String eCourtCode = ApexPages.currentPage().getParameters().get('cc');
        String eCourtType = ApexPages.currentPage().getParameters().get('ct');
        String eCourtName = ApexPages.currentPage().getParameters().get('cn');
        
        String eViolationType = ApexPages.currentPage().getParameters().get('vt');
        String eSubmissionType = ApexPages.currentPage().getParameters().get('st');
        // calls getCurrentCases() method to retrieve the results (a list of DIR_Case__c records)  
        allResultCases = getCurrentCases(eSearch, lwNumber, sDate, eDate, eName, eFiler, lawFirm, eCity, eZipCode, eCourtCode, eCourtType, eCourtName, eViolationType, eSubmissionType);

    }
    
    public List<DIR_Case__c> getCurrentCases(String sString, String lwNumber, String startDate, String endDate, String eName, String eFiler, String lFirm, String ecity, String ezipCode, String CourtCaseNumber, String CourtType, String CourtName, String ViolationType, String SubmissionType) {

        List<DIR_Case__c> results = new List<DIR_Case__c>();
        
        if(String.isEmpty(sString) && String.isEmpty(lwNumber) && (String.isEmpty(startDate) || String.isEmpty(endDate)) 
        && String.isEmpty(ecity) && String.isEmpty(ezipCode) && String.isEmpty(CourtCaseNumber) && String.isEmpty(CourtType) 
        && String.isEmpty(CourtName) && String.isEmpty(ViolationType) && String.isEmpty(SubmissionType)) {
            // if the all the parameters are empty then don't show any results
        } else {
            // add conditions to the SOQL query to filter the results   
            
            String query = 'SELECT Id, Name, Case_Number__c, PAGA_LWDA_Number__c, Court_Case_Number_for_PAGA_Case__c, Notice_Filing_Date__c, Plaintiff_for_PAGA__c, Plaintiff_for_PAGA__r.Name, LWDA_Number__c, Legacy_PAGA_LWDA_Number__c, PAGA_Court_Case_Number__c, Employer_Filer__c, Employer_Filer__r.Name, Employer_Filer_Firm__c, Filer_for_Employer__c, Filer_for_Employer__r.Name, Law_Firm_for_PAGA_Case__c, Employer__c, Employer__r.Name, Employer__r.ShippingCity, Employer__r.ShippingPostalCode, Violation_Type__c, Plaintiff_for_PAGA_Case_Text__c, Filer_Attorney_for_PAGA_Case__c, Filer_Attorney_for_PAGA_Case__r.Name FROM DIR_Case__c WHERE RecordType.Name = \'PAGA Case\' AND PAGA_Status__c != \'Pending - Incomplete\' ';
            if(!String.isEmpty(sString)) {
                sString = string.escapeSingleQuotes(sString);
                String sn = '%'+sString+'%';
                query += ' AND ((Employer__r.Name LIKE  \'' + sn + '\') OR (Plaintiff_for_PAGA__r.Name LIKE \'' + sn + '\') OR (Plaintiff_for_PAGA_Case_Text__c LIKE \'' + sn + '\') OR (Filer_Attorney_for_PAGA_Case__r.Name LIKE \'' + sn + '\') OR (Law_Firm_for_PAGA_Case__c LIKE \'' + sn + '\') OR (Employer_Filer__r.Name LIKE \'' + sn + '\') OR (Employer_Filer_Firm__c LIKE \'' + sn + '\') OR (Filer_for_Employer__r.Name LIKE \'' + sn + '\') ) ';
            }
            
            if(!String.isEmpty(eName)) { 
                eName = '%' + eName + '%';
                query += ' AND Employer__r.Name LIKE  \'' + eName + '\' ';
            }
            if(!String.isEmpty(eFiler)) {
                eFiler = '%' + eFiler + '%';
                query += ' AND Employer_Filer__r.Name LIKE  \'' + eFiler + '\' ';
            }
            if(!String.isEmpty(lFirm)) {
                lFirm = '%' + lFirm + '%';
                query += ' AND Law_Firm_for_PAGA_Case__c LIKE  \'' + lFirm + '\' ';
            }
            
            if(!String.isEmpty(lwNumber)) {
                String ln = '%'+lwNumber+'%';
                query += ' AND (Name LIKE \'' + ln + '\' OR Case_Number__c LIKE \'' + ln + '\') ';
            }
            if(!String.isEmpty(startDate)) {
                List<String> startStringDate = startDate.split('-');
                String sD = startStringDate[0] + '-' + startStringDate[1] + '-' + startStringDate[2];
                Date sDate = Date.valueOf(sD);
                query += ' AND Notice_Filing_Date__c >= :sDate ';
            }
            if(!String.isEmpty(endDate)) {
                List<String> endStringDate = endDate.split('-');
                String eD = endStringDate[0] + '-' + endStringDate[1] + '-' + endStringDate[2];
                Date eDate = Date.valueOf(eD);
                query += ' AND Notice_Filing_Date__c <= :eDate ';
            }
            if(!String.isEmpty(ecity)) 
                query += ' AND Employer__r.ShippingCity = :ecity ';
            
            if(!String.isEmpty(ezipCode)) {
                ezipCode = ezipCode+'%';
                query += ' AND Employer__r.ShippingPostalCode LIKE \'' + ezipCode + '\'';
            }

            if(!String.isEmpty(CourtCaseNumber)) 
                query += ' AND PAGA_Court_Case_Number__c = :CourtCaseNumber';
            if(!String.isEmpty(CourtType)) 
                query += ' AND Court_Type__c = :CourtType ';
            if(!String.isEmpty(CourtName)) 
                query += ' AND Court_Name__c = :CourtName ';
            
            if(!String.isEmpty(ViolationType)) {
                List<String> allVTypes = ViolationType.split(';');
               
                query += ' AND Violation_Type__c INCLUDES (';
                Integer i = 0;
                for(String s: allVTypes) {
                    if(i < allVTypes.size()-1)
                        query += '\'' + s + '\',';
                    else 
                        query += '\'' + s + '\'';
                    i++;
                }
                query += ' )';
            }
            if(!String.isEmpty(SubmissionType)) {
                List<String> allSTypes = SubmissionType.split(';');
               
                query += ' AND Submission_Detail_Type__c INCLUDES (';
                Integer i = 0;
                for(String s: allSTypes) {
                    if(i < allSTypes.size()-1)
                        query += '\'' + s + '\',';
                    else 
                        query += '\'' + s + '\'';
                    i++;
                }
                query += ' )';
            }
            query += ' ORDER BY Name DESC';
            results = Database.query(query);
        }
        return results;

    }
    
}