force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>BOFE Stay</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Citation or Other Issues</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Unable to Pursue</fullName>
            </value>
            <value>
                <fullName>Returned to Claimant</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Waiting for Litigation</fullName>
            </value>
            <value>
                <fullName>New AutoRefer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/WorkAddressDifferent__c.field-meta.xml
<CustomField>
    <fullName>WorkAddressDifferent__c</fullName>
    <label>Work Address Different?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To populate Region field</description>
    <label>Zip Code</label>
    <referenceTo>Zip_Code__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <description>Vertiba</description>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/Related_Party__c/Related_Party__c.object-meta.xml
<CustomObject>
    <label>Related Party</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Related Party  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Parties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Party__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Related Parties</relationshipLabel>
    <relationshipName>Related_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Party__c/fields/Other_State__c.field-meta.xml
<CustomField>
    <fullName>Other_State__c</fullName>
    <label>Other State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Party__c/fields/Other_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Other_Street_Address__c</fullName>
    <inlineHelpText>Address where you worked, if different from Employer / Business address.</inlineHelpText>
    <label>Other Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Party__c/fields/Other_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Other_Zip_Code__c</fullName>
    <label>Other Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Party__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Agent for Service of Process</fullName>
            </value>
            <value>
                <fullName>Aggrieved</fullName>
            </value>
            <value>
                <fullName>Assignee</fullName>
            </value>
            <value>
                <fullName>Attorney for Defendant</fullName>
            </value>
            <value>
                <fullName>Attorney for Plaintiff</fullName>
            </value>
            <value>
                <fullName>Attorney Representative</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Case Employer</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Chief</fullName>
            </value>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Claimant Advocate</fullName>
            </value>
            <value>
                <fullName>Claimant Attorney</fullName>
            </value>
            <value>
                <fullName>Claimant Guardian</fullName>
            </value>
            <value>
                <fullName>Claimant Minor</fullName>
            </value>
            <value>
                <fullName>Claimant Representative</fullName>
            </value>
            <value>
                <fullName>Client Employer</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>Contractor Successor</fullName>
            </value>
            <value>
                <fullName>Corporate Officer</fullName>
            </value>
            <value>
                <fullName>Court</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
            <value>
                <fullName>Defendant - (Restitution)</fullName>
            </value>
            <value>
                <fullName>Defendant - Agent for Service</fullName>
            </value>
            <value>
                <fullName>Defendant Attorney</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Witness</fullName>
            </value>
            <value>
                <fullName>Employer Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Party__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Party__c/fields/Still_in_business__c.field-meta.xml
<CustomField>
    <fullName>Still_in_business__c</fullName>
    <label>Still in business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Party__c/recordTypes/Advocate.recordType-meta.xml
<RecordType>
    <fullName>Advocate</fullName>
    <active>true</active>
    <label>Advocate</label>
</RecordType>

force-app/main/default/objects/Related_Party__c/recordTypes/Employee.recordType-meta.xml
<RecordType>
    <fullName>Employee</fullName>
    <active>true</active>
    <label>Employee</label>
</RecordType>

force-app/main/default/objects/Related_Party__c/recordTypes/Employer.recordType-meta.xml
<RecordType>
    <fullName>Employer</fullName>
    <active>true</active>
    <label>Employer</label>
</RecordType>

force-app/main/default/objects/Related_Party__c/recordTypes/Witness.recordType-meta.xml
<RecordType>
    <fullName>Witness</fullName>
    <active>true</active>
    <label>Witness</label>
</RecordType>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <description>Holds the zip codes and cities in which a zip code is located and supports the assigning records based on zip codes.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City the zip code is within</description>
    <inlineHelpText>Enter the city that this zip code is in.</inlineHelpText>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>TX</fullName>
    </customValue>
    <description>US State Abbreviations</description>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DIR_RelatedPartyTriggerHandler_Test.cls
//-----------------------------
// @author: Oswin Correa
// @date: 18/4/2018
// @description: Test Class of  DIR_RelatedPartyTriggerHandler
//-----------------------------
// @modified by: Daniel Chu
// @deploy date: 1/31/2019
// @description: As part of the fix to confirming employer related party whose other zip code is out of California
// @note: This test class is a work in progress, and needs to be redesign. It was revised quickly to deploy the fixes for SR-005287.
//-----------------------------
@isTest
private class DIR_RelatedPartyTriggerHandler_Test {

    //Test 1 
    //Testing for 1 Employer, 1 Claimant.
    private static testMethod void test_DIR_RelatedPartyTriggerHandler1() {
 
        Account objAcct1 = new Account(Name = 'Acct1', ShippingCity = 'ShippingCity1', BillingCity = 'BillingCity1');
        Account objAcct2 = new Account(Name = 'Acct2', ShippingCity = 'ShippingCity2', BillingCity = 'BillingCity2');
        insert new List<Account> {objAcct1,objAcct2}; 
         
        DIR_Case__c objCase = new DIR_Case__c(RecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('RCI').getRecordTypeId());
        insert objCase;
    
        Related_Party__c objRL1 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Claimant',
                                                  Street_Address__c = '123 Praire City Drive, Apt B',
                                                  City__c = 'Whittier',
                                                  State__c = 'CA',
                                                  Zip_Code__c = '90607',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employee').getRecordTypeId()
                                                  );
    
        Related_Party__c objRL2 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Case Employer',
                                                  First_Name__c = 'John',
                                                  Last_Name__c = 'Smith',
                                                  Zip_Code__c = '94105',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employer').getRecordTypeId()
                                                  );               
                                                                                          

        insert new List<Related_Party__c> {objRL1,objRL2};
    
        objRL1.Status__c = 'Confirm';  
        update new List<Related_Party__c> {objRL1};
    
        objRL2.Status__c = 'Confirm';
        update new List<Related_Party__c> {objRL2};
    
        system.assertEquals(true, [SELECT Id From Account where Id !=: objAcct1.Id].size() != 0);

  }

    //Test 2
    //Testing for 1 Employer with different work address, 1 Claimant. Account ID found for both claimant and employer.
    private static testMethod void test_DIR_RelatedPartyTriggerHandler2() {
      
    Account objAcct1 = new Account(Name = 'Acct1', ShippingCity = 'ShippingCity1', BillingCity = 'BillingCity1');
    Account objAcct2 = new Account(Name = 'Acct2', ShippingCity = 'ShippingCity2', BillingCity = 'BillingCity2');
    insert new List<Account> {objAcct1,objAcct2}; 
      
    DIR_Case__c objCase = new DIR_Case__c(RecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('RCI').getRecordTypeId());
    objCase.WorkAddressDifferent__c = 'Yes';
    
    insert objCase;

    Related_Party__c objRL1 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Claimant',
                                                  Zip_Code__c = '94105',
                                                  Email__c = 'test@dir.ca.gov.test',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employee').getRecordTypeId()
                                                  );
    
    Related_Party__c objRL2 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Case Employer',
                                                  First_Name__c = 'John',
                                                  Last_Name__c = 'Smith',
                                                  Zip_Code__c = '94105',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employer').getRecordTypeId()
                                                  );               
                                                  
    Related_Party__c objRL3 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Employer Address',
                                                  Other_Zip_Code__c = '78751',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employer DWA').getRecordTypeId()
                                                  );                                              

    Related_Party__c objRL4 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Witness',
                                                  Zip_Code__c = '94134',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Witness').getRecordTypeId()
                                                  );  
                                                  
    Related_Party__c objRL5 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Advocate',
                                                  Zip_Code__c = '94133',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Advocate').getRecordTypeId()
                                                  );                                                   
                                                  

    insert new List<Related_Party__c> {objRL1,objRL2,objRL3,objRL4,objRL5};
   
    objRL1.Status__c = 'Confirm';
    objRL1.Found_Account_ID__c = objAcct1.Id;
    update objRL1;
    
    objRL2.Status__c = 'Confirm';
    objRL2.Found_Account_ID__c = objAcct2.Id;  
    update objRL2; 
 
    objRL5.Status__c = 'Confirm';
    update objRL5;
  
    
    system.assertEquals(true, [SELECT Id From Account where Id !=: objAcct1.Id].size() != 0);
    
  }
  
    //Test 3
    //Testing for 1 Employer, 1 Claimant with invalid Account ID. 
    private static testMethod void test_DIR_RelatedPartyTriggerHandler3() {
 
        Account objAcct1 = new Account(Name = 'Acct1', ShippingCity = 'ShippingCity1', BillingCity = 'BillingCity1');
        Account objAcct2 = new Account(Name = 'Acct2', ShippingCity = 'ShippingCity2', BillingCity = 'BillingCity2');
        insert new List<Account> {objAcct1,objAcct2}; 
         
        DIR_Case__c objCase = new DIR_Case__c(RecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('RCI').getRecordTypeId());
        insert objCase;
    
        Related_Party__c objRL1 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Claimant',
                                                  Zip_Code__c = '95691',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employee').getRecordTypeId()
                                                  );
    
        Related_Party__c objRL2 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Case Employer',
                                                  First_Name__c = 'John',
                                                  Last_Name__c = 'Smith',
                                                  Zip_Code__c = '94105',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employer').getRecordTypeId()
                                                  );               
                                                                                          

        insert new List<Related_Party__c> {objRL1,objRL2};
    

        try
        {
            objRL1.Status__c = objRL2.Status__c = 'Confirm';
            objRL2.Found_Account_ID__c = 'ABC123';
            update new List<Related_Party__c> {objRL1,objRL2};
            
        }
    
        catch(Exception e)
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('Enter valid Account Id in Found_Account_ID field') ? True : False;
            system.assertEquals(expectedExceptionThrown, True);
        } 
    }

    //Test 4
    //Testing for 1 Employer with different work address, 1 Claimant. Account ID found for both claimant and employer.
    private static testMethod void test_DIR_RelatedPartyTriggerHandler4() {

        Map<String,Schema.RecordTypeInfo> accountTRMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        Id recordTypeId_PA = accountTRMapByName.get('Person Account').getRecordTypeId();
        Id recordTypeId_BA = accountTRMapByName.get('Business Account').getRecordTypeId(); 

        Account objAcct1 = new Account(FirstName = 'Joe', 
                                       LastName = 'Smith',
                                       RecordTypeId = recordTypeId_PA,
                                       BillingCity = 'San Francisco',
                                       BillingState = 'CA',
                                       BillingPostalCode = '94105',
                                       BillingStreet = '123 Bay St',
                                       ShippingCity = 'San Francisco',
                                       ShippingState = 'CA',
                                       ShippingPostalCode = '94105',
                                       ShippingStreet = '123 Bay St',
                                       Email__c = 'test@dir.ca.gov.test');
    
        Account objAcct2 = new Account(Name = 'Company XYZ',
                                       RecordTypeId = recordTypeId_BA,
                                       ShippingCity = 'Austin',
                                       ShippingState = 'CA',
                                       ShippingPostalCode = '78751',
                                       ShippingStreet = '321 Industrial Drive'); 
      
        insert new List<Account> {objAcct1,objAcct2}; 
      
        DIR_Case__c objCase = new DIR_Case__c(RecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('RCI').getRecordTypeId());
        objCase.WorkAddressDifferent__c = 'Yes';
    
        insert objCase;

        Related_Party__c objRL1 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Claimant',
                                                  Zip_Code__c = '94105',
                                                  Email__c = 'test@dir.ca.gov.test',
                                                  Status__c = 'Pending',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employee').getRecordTypeId()
                                                  );
    
        Related_Party__c objRL2 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Case Employer',
                                                  Business_Name__c = 'Company XYZ',
                                                  Street_Address__c = '1234 Mission St',
                                                  City__c = 'San Francisco',
                                                  Zip_Code__c = '94105',
                                                  Still_in_business__c = 'Yes',
                                                  Status__c = 'Pending',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employer').getRecordTypeId()
                                                  );               
                                                  
        Related_Party__c objRL3 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Employer Address',
                                                  Other_Street_Address__c = '321 Industrial Drive',
                                                  Other_City__c = 'Austin',
                                                  Other_State__c = 'TX',
                                                  Other_Zip_Code__c = '78751',
                                                  Status__c = 'Pending',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employer DWA').getRecordTypeId()
                                                  );                                              

        Related_Party__c objRL4 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Witness',
                                                  Zip_Code__c = '94134',
                                                  Status__c = 'Pending',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Witness').getRecordTypeId()
                                                  );  
                                                  
        Related_Party__c objRL5 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Advocate',
                                                  Zip_Code__c = '94133',
                                                  Status__c = 'Pending',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Advocate').getRecordTypeId()
                                                  );                                                   
                                                  

        insert new List<Related_Party__c> {objRL1,objRL2,objRL3,objRL4,objRL5};

    
        objRL1.Status__c = objRL2.Status__c = objRL5.Status__c = 'Confirm';

        update new List<Related_Party__c> {objRL1,objRL2,objRL5};
 
        system.assertEquals(true, [SELECT Id From Account where Id !=: objAcct1.Id].size() != 0);

    }
 
    //Test 5
    private static testMethod void test_DIR_RelatedPartyTriggerHandler5() {
    
        Account objAcct1 = new Account(Name = 'Acct1', ShippingCity = 'ShippingCity1', BillingCity = 'BillingCity1');
        Account objAcct2 = new Account(Name = 'Acct2', ShippingCity = 'ShippingCity2', BillingCity = 'BillingCity2');
        insert new List<Account> {objAcct1,objAcct2}; 
   
     
        DIR_Case__c objCase = new DIR_Case__c(RecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('RCI').getRecordTypeId());
        objCase.WorkAddressDifferent__c = 'Yes';
    
        insert objCase;

        Related_Party__c objRL1 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Claimant',
                                                  Zip_Code__c = '94105',
                                                  Email__c = 'test@dir.ca.gov.test',
                                                  Status__c = 'Pending',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employee').getRecordTypeId()
                                                  );
    
        Related_Party__c objRL2 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Case Employer',
                                                  Business_Name__c = 'Company XYZ',
                                                  Street_Address__c = '1234 Mission St',
                                                  City__c = 'San Francisco',
                                                  Zip_Code__c = '94105',
                                                  Still_in_business__c = 'Yes',
                                                  Status__c = 'Pending',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employer').getRecordTypeId()
                                                  );               
                                                  
        Related_Party__c objRL3 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Employer Address',
                                                  Other_Street_Address__c = '321 Industrial Drive',
                                                  Other_City__c = 'Austin',
                                                  Other_State__c = 'TX',
                                                  Other_Zip_Code__c = '78751',
                                                  Status__c = 'Pending',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employer DWA').getRecordTypeId()
                                                  );                                              

        Related_Party__c objRL4 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Witness',
                                                  Zip_Code__c = '94134',
                                                  Status__c = 'Pending',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Witness').getRecordTypeId()
                                                  );  
                                                  
        Related_Party__c objRL5 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Advocate',
                                                  Zip_Code__c = '94133',
                                                  Status__c = 'Pending',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Advocate').getRecordTypeId()
                                                  );                                                   
                                                  

        insert new List<Related_Party__c> {objRL1,objRL2,objRL3,objRL4,objRL5};

    
        objRL1.Status__c = objRL2.Status__c = objRL3.Status__c = objRL5.Status__c = 'Confirm';

        update new List<Related_Party__c> {objRL1,objRL2,objRL3,objRL5};
  
        system.assertEquals(true, [SELECT Id From Account where Id !=: objAcct1.Id].size() != 0);

    }

    //Test 6
    //Testing for 1 Employer, 1 Claimant.
    private static testMethod void test_DIR_RelatedPartyTriggerHandler6() {
 
        Account objAcct1 = new Account(Name = 'Acct1', ShippingCity = 'ShippingCity1', BillingCity = 'BillingCity1');
        Account objAcct2 = new Account(Name = 'Acct2', ShippingCity = 'ShippingCity2', BillingCity = 'BillingCity2');
        insert new List<Account> {objAcct1,objAcct2}; 
         
        DIR_Case__c objCase = new DIR_Case__c(RecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('RCI').getRecordTypeId());
        insert objCase;
    
        Related_Party__c objRL1 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Claimant',
                                                  Street_Address__c = '123 Praire City Drive, Apt B',
                                                  City__c = 'Whittier',
                                                  State__c = 'CA',
                                                  Zip_Code__c = '90607',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employee').getRecordTypeId()
                                                  );
    
        Related_Party__c objRL2 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Case Employer',
                                                  First_Name__c = 'John',
                                                  Last_Name__c = 'Smith',
                                                  Zip_Code__c = '94105',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employer').getRecordTypeId()
                                                  );               

        Related_Party__c objRL5 = new Related_Party__c(Case_Management__c = objCase.Id,
                                                  Role__c = 'Advocate',
                                                  Zip_Code__c = '94133',
                                                  RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Advocate').getRecordTypeId()
                                                  ); 
                                                                                          

        insert new List<Related_Party__c> {objRL1,objRL2,objRL5};
    
        objRL1.Status__c = objRL2.Status__c = objRL5.Status__c = 'Confirm';  
        update new List<Related_Party__c> {objRL1,objRL2,objRL5};
    
    
        system.assertEquals(true, [SELECT Id From Account where Id !=: objAcct1.Id].size() != 0);

    }
  
}