force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Case Number</description>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Total_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Paid__c</fullName>
    <label>Total Amount Paid</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ReceiptCasesDialogController.cls
/**
 * Developer: Sathya Chandrasekar
 * Created: August, 2019
 **/ 

public class ReceiptCasesDialogController {
    @AuraEnabled
    public static List<DIR_Case__c> searchCases(String searchKey){
        
        if(String.isEmpty(searchKey)){            
            return null;
        }else{
            string s = '%'+searchKey+'%';

            return [Select Id, Case_Number__c, Assigned_Deputy__c,Total_Amount_Paid__c, Assigned_Deputy__r.Name, Employer__c, Employer__r.Name, RecordType.Name
                                                     from DIR_Case__c where (Case_Number__c like :s or Employer__r.Name like :s )
                                                     and Assigned_Deputy__r.Name != null order By Case_Number__c Limit 5];
        }
    }
    
    @AuraEnabled
    public static List<EditCases> getgridCases(String ids){
        Set<String> caseIds = new Set<String>();
        for(String s : ids.split(',')){
            caseIds.add(s);
        }
        
        List<DIR_Case__c> caseL = [Select Id, Case_Number__c, RecordType.Name, Employer__c, Employer__r.Name from DIR_Case__c where id in: caseIds];
        Decimal amount = 0;
        
        List<EditCases> eCases = new List<EditCases>();
        for(DIR_Case__c c : caseL){
            EditCases ec = new EditCases(c.Id, c.Case_Number__c, c.RecordType.Name ,c.Employer__r.Name, amount);
            eCases.add(ec);
        }
        
        return eCases;
    }
    
    public class EditCases{
        
        public EditCases(String IdCase, String caseNo, String recType,String employer, Decimal allocatedAmount){
            this.IdCase = IdCase;
            this.caseNo = caseNo;
            this.recType = recType;
            this.employer = employer;
            this.allocatedAmount = allocatedAmount;
        }
        
        @AuraEnabled
        public String IdCase {get;set;}
        @AuraEnabled
        public String caseNo {get;set;}
        @AuraEnabled
        public String recType {get;set;}
        @AuraEnabled
        public String employer {get;set;}
        @AuraEnabled
        public Decimal allocatedAmount {get;set;}
    }
    
}