force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_Required__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attachment Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <inlineHelpText>If this document has an expiration date or will need to be renewed by a certain date, please enter that date here.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <label>Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Number_of_Attachments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Attachments__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Populated via dlrs</description>
    <label>Number of Attachments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Submission Detail</relationshipLabel>
    <relationshipName>Submission_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Litter</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subpoena</fullName>
            </value>
            <value>
                <fullName>OTA</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>L&amp;R/RCI/CIU</fullName>
            </value>
            <value>
                <fullName>Cure Dispute</fullName>
            </value>
            <value>
                <fullName>Court Complaint</fullName>
            </value>
            <value>
                <fullName>Proposed Settlement</fullName>
            </value>
            <value>
                <fullName>PAGA Notice</fullName>
            </value>
            <value>
                <fullName>Other PAGA Document</fullName>
            </value>
            <value>
                <fullName>Employer Response/Cure</fullName>
            </value>
            <value>
                <fullName>Amended Notice</fullName>
            </value>
            <value>
                <fullName>In Forma Pauperis</fullName>
            </value>
            <value>
                <fullName>Court Order/Judgment</fullName>
            </value>
            <value>
                <fullName>Workers Compensation Insurance (WCI)</fullName>
            </value>
            <value>
                <fullName>Bond Collective Bargaining Agreement (CBA)</fullName>
            </value>
            <value>
                <fullName>Sample Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Signed Employee Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Employee Leasing WCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/VIP_Form_Section__c.field-meta.xml
<CustomField>
    <fullName>VIP_Form_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>VIP Form Section</label>
    <referenceTo>VIPForm__VIP_Category__c</referenceTo>
    <relationshipLabel>Submission Detail</relationshipLabel>
    <relationshipName>Submission_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/VIP_Form_Section_Name_Display__c.field-meta.xml
<CustomField>
    <fullName>VIP_Form_Section_Name_Display__c</fullName>
    <description>Used in the form tool for the Attachment widget</description>
    <formula>VIP_Form_Section__r.VIPForm__Name_Displayed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VIP Form Section Name Display</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the License/Registration</description>
    <inlineHelpText>Expiration Date of the License/Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Number_of_Attachments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Attachments__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Populated via DLRS</description>
    <label>Number of Attachments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Attachment_Widget_Controller.cls
public class Attachment_Widget_Controller{
    String Id;
    String sectionId;
    String componentId;
    public License_Registration__c reg;
    public List<AttachmentTable> attTable {get; set;}
    
    public Attachment_Widget_Controller(){
        this.Id = ApexPages.currentPage().getParameters().get('id');
        this.sectionId = ApexPages.currentPage().getParameters().get('sectionId');
        this.componentId = ApexPages.currentPage().getParameters().get('componentId');
        
        if(this.Id != null && this.sectionId != null){
            loadTable();
        }
    }
    
   
    
    public void loadTable(){
        
        VIPForm__VIP_Category__c obj = [SELECT Name, Id,VIPForm__Name_Displayed__c FROM VIPForm__VIP_Category__c WHERE Id=:sectionId ];
                
        reg = [select id, name, (select id, name, Type__c, Description__c, Instructions__c, Expiration_Date__c,VIP_Form_Section__c, Attachment_Required__c from Submission_Detail__r where VIP_Form_Section_Name_Display__c = :obj.VIPForm__Name_Displayed__c ) from License_Registration__c where id = :this.Id];
        if(reg.Submission_Detail__r != null && reg.Submission_Detail__r.size() > 0){
            Map<Id,Attachments_Plus__c> attPMap = new Map<Id,Attachments_Plus__c>([select id, Attachment_Required__c, (select id from Attachments), (select id,ContentDocumentId  from ContentDocumentLinks) from Attachments_Plus__c where Id IN :reg.Submission_Detail__r]);
            Set<Id> contentDocumentIdSet = new Set<Id>();
            Map<Id,ContentVersion> contentDocVersionMap = new Map<Id,ContentVersion>();
            attTable = new List<AttachmentTable>();
            
            for(Attachments_Plus__c attP : reg.Submission_Detail__r){
                if(attPMap.containsKey(attP.id) && attPMap.get(attP.id).ContentDocumentLinks != null && attPMap.get(attP.id).ContentDocumentLinks.size() > 0){
                    for(ContentDocumentLink cdl : attPMap.get(attP.id).ContentDocumentLinks){
                        contentDocumentIdSet.add(cdl.ContentDocumentId);
                    }
                }
            }
            
            if(contentDocumentIdSet.size() > 0){
                for(ContentVersion cv : [select id, ContentDocumentId from ContentVersion WHERE ContentDocumentId IN :contentDocumentIdSet AND IsLatest = true]){
                    contentDocVersionMap.put(cv.ContentDocumentId, cv);
                }
            }
            
            for(Attachments_Plus__c attP : reg.Submission_Detail__r){
                system.debug('***SubmissionDetails.size() =' + reg.Submission_Detail__r.size());
                if(attPMap.containsKey(attP.id) && attPMap.get(attP.id).ContentDocumentLinks != null && attPMap.get(attP.id).ContentDocumentLinks.size() > 0){
                    attTable.add(new AttachmentTable(true, attp, attPMap.get(attP.id).ContentDocumentLinks[0].ContentDocumentId, contentDocVersionMap.get(attPMap.get(attP.id).ContentDocumentLinks[0].ContentDocumentId).id));
                    system.debug('***' + attP.id + '***ContentDocumentId****' + attPMap.get(attP.id).ContentDocumentLinks[0].ContentDocumentId);
                }else{
                    attTable.add(new AttachmentTable(false, attp, null, null));
                }
            }
        }
        
    }
    
    public class AttachmentTable{
        public Boolean hasAttachment {get; set;}
        public Attachments_Plus__c attP {get; set;}
        public Attachment att {get; set;}
        public string ContentDocumentId {get; set;}
        public string ContentVersionId {get; set;}
        
        public attachmentTable(Boolean hasAttachment, Attachments_Plus__c attP, Id ContentDocumentId, Id ContentVersionId){
            this.hasAttachment = hasAttachment;
            this.attP = attP;
            this.att = new Attachment();
            this.ContentDocumentId = ContentDocumentId;
            this.ContentVersionId = ContentVersionId;
        }
    }
    
    public void attachPDF(){
        Logger.push('loadTable','Attachment_Widget_Controller');
        try{
            List<Attachments_Plus__c> attPlus = new List<Attachments_Plus__c>();
            for(AttachmentTable attTab : attTable){
                if(attTab.att.body != null){
                    if(!attTab.att.Name.containsIgnoreCase('.pdf') && !attTab.att.Name.containsIgnoreCase('.jpg') && !attTab.att.Name.containsIgnoreCase('.tif') && !attTab.att.Name.containsIgnoreCase('.doc') && !attTab.att.Name.containsIgnoreCase('.docx') && !attTab.att.Name.containsIgnoreCase('.png') && !attTab.att.Name.containsIgnoreCase('.gif')){
                        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'You can only upload files with .pdf, .jpg, .tif, png, .doc, .docx, .gif types.');
                        ApexPages.addMessage(myMsg);
                        attTab.att = new Attachment();
                        return;
                    }
                    ContentVersion conVer = new ContentVersion();
                    conVer.ContentLocation = 'S';
                    conVer.PathOnClient = attTab.att.Name;
                    conVer.Title = attTab.att.Name;
                    conVer.VersionData = attTab.att.body;
                    conVer.Origin = 'C';
                    insert conVer;
                    
                    ContentDocumentLink cDe = new ContentDocumentLink();
                    cDe.ContentDocumentId = [select id, ContentDocumentId from ContentVersion where id = :conVer.id].ContentDocumentId;
                    cDe.LinkedEntityId = attTab.attP.id;
                    cDe.ShareType = 'I';
                    cDe.Visibility = 'AllUsers';
                    insert cDe;
                    system.debug('entering inside**');
                    attTab.hasAttachment = true;
                    attTab.ContentDocumentId = cDe.ContentDocumentId;
                    attTab.attP.Number_of_Attachments__c = 1;
                    system.debug('attTab.attP.Number_of_Attachments__c***'+attTab.attP.Number_of_Attachments__c);
                }
                attPlus.add(attTab.attP);
                            system.debug('attTab.attP*****'+attTab.attP);

            }
            system.debug('attPlus*****'+attPlus);
            update attPlus;
            attTable.clear();
            loadTable();
        }catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage());
            ApexPages.addMessage(myMsg);
            return;
        }
        Logger.pop();
    }
    
    
    public void deleteAttachment(){
        Logger.push('loadTable','Attachment_Widget_Controller');
        String delID = ApexPages.CurrentPage().getParameters().get('delID');
        system.debug('***delete attachment id***' + delID);
        Attachments_Plus__c attP = [select id, (select id,ContentDocumentId from ContentDocumentLinks) from Attachments_Plus__c where id = :delID];
        list<Attachments_Plus__c> attPlus = new list<Attachments_Plus__c>();
        if(attP.ContentDocumentLinks != null && attP.ContentDocumentLinks.size() > 0){
            for(AttachmentTable attTab : attTable){
                if(delID == attTab.attP.id){
                    String conDocId = attP.ContentDocumentLinks[0].ContentDocumentId;
                    delete attP.ContentDocumentLinks[0];
                    delete new ContentDocument(id = conDocId);
                    attTab.hasAttachment = false;
                    //attTab.attP.Number_of_Attachments__c = 0;
                    attPlus.add(attTab.attP);
                    break;
                    
                }
            }
            update attPlus;
        }
        Logger.pop();
    }
    
    public void updateAttTable(){
        Logger.push('loadTable','Attachment_Widget_Controller');
        List<Attachments_Plus__c> attPlus = new List<Attachments_Plus__c>();
        for(AttachmentTable attTab : attTable){
            attPlus.add(attTab.attP);
        }
        update attPlus;
        Logger.pop();
    }
}