force-app/main/default/objects/Affiliation__c/Affiliation__c.object-meta.xml
<CustomObject>
    <description>Defines the relationship between two accounts, person accounts or business accounts either one, or between accounts and contacts.</description>
    <label>Affiliation</label>
    <nameField>
        <label>Affiliation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliation__c/fields/Affiliated_Account__c.field-meta.xml
<CustomField>
    <fullName>Affiliated_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account that is chosen to be related to an account when creating an affiliation.</description>
    <label>Affiliated Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliations (Affiliated Business/Person)</relationshipLabel>
    <relationshipName>Additional_Affiliations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affiliation__c/fields/Affiliation_Type__c.field-meta.xml
<CustomField>
    <fullName>Affiliation_Type__c</fullName>
    <description>The affiliation pairing that was selected when creating the affilitation</description>
    <inlineHelpText>The &quot;Affiliated Account&quot; or &quot;Affiliated Contact&quot; has this type of relationship to the &quot;Main Account&quot; or &quot;Main Contact&quot;</inlineHelpText>
    <label>Affiliation Type</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affiliation__c/fields/Main_Account__c.field-meta.xml
<CustomField>
    <fullName>Main_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The &quot;source&quot; account that an affiliation is created FROM</description>
    <inlineHelpText>The &quot;source&quot; account that an affiliation is created FROM. When reading the affiliation, the relationship should read:
[Affiliated Account/contact] is a [Affiliation Type] of [Main Account/contact].</inlineHelpText>
    <label>Main Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliations (Main Account)</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appeal__c/Appeal__c.object-meta.xml
<CustomObject>
    <description>This is used for a Request for Citation Appeal Hearing associated with a DIR BOFE Case.  This may be repurposed for specific purposes.</description>
    <label>Appeal</label>
    <nameField>
        <displayFormat>APL-{000000}</displayFormat>
        <label>Appeal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appeals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appeal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Appeals</relationshipLabel>
    <relationshipName>Appeals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appeal__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Liability</label>
    <referenceTo>Liability__c</referenceTo>
    <relationshipLabel>Appeals</relationshipLabel>
    <relationshipName>Appeals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appeal__c/recordTypes/BOFE.recordType-meta.xml
<RecordType>
    <fullName>BOFE</fullName>
    <active>true</active>
    <description>Used for BOFE Appeals</description>
    <label>BOFE</label>
</RecordType>

force-app/main/default/objects/Appeal__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/DIR_Appeal_Party__c/DIR_Appeal_Party__c.object-meta.xml
<CustomObject>
    <description>One of the individuals that needs to be notified of this Appeal. (DIR BOFE)</description>
    <label>Appeal Party</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Appeal Party ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appeal Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Appeal_Party__c/fields/Appeal__c.field-meta.xml
<CustomField>
    <fullName>Appeal__c</fullName>
    <description>The appeal these parties are related to</description>
    <label>Appeal</label>
    <referenceTo>Appeal__c</referenceTo>
    <relationshipLabel>Appeal Parties</relationshipLabel>
    <relationshipName>Appeal_Parties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Appeal_Party__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>The entity (person or business) this appeal is related to</description>
    <label>Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Appeal Parties</relationshipLabel>
    <relationshipName>Appeal_Parties_Entity</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Citation_Number__c.field-meta.xml
<CustomField>
    <fullName>Citation_Number__c</fullName>
    <label>Citation Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <description>Vertiba</description>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/DIR_Violation__c/DIR_Violation__c.object-meta.xml
<CustomObject>
    <description>This objects contains a Violation tied to a Case.</description>
    <label>Case Issue</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Case Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Violation__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Violations are tied together as an assessment.</description>
    <label>Assessment</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipName>Case_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This creates a master detail relationship between a Violation and the Case that it is against.</description>
    <inlineHelpText>This creates a master detail relationship between a Violation and the Case that it is against.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Issues</relationshipLabel>
    <relationshipName>DIR_Violations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Citation_Number__c.field-meta.xml
<CustomField>
    <fullName>Citation_Number__c</fullName>
    <formula>Assessment__r.Citation_Number__c</formula>
    <label>Citation Number(s)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/Liability__c/Liability__c.object-meta.xml
<CustomObject>
    <description>This objects contains the Liability against an Assessment.</description>
    <label>Liability</label>
    <nameField>
        <displayFormat>LIA-{000000}</displayFormat>
        <label>Liability ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability__c/fields/Appeal_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Appeal_Deadline__c</fullName>
    <description>Set via workflow rule when liability is created based on the Appeal Deadline (Days) from the assessment</description>
    <inlineHelpText>The default appeal deadline based on the Appeal Deadline (Days) from the parent assessment</inlineHelpText>
    <label>Appeal Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Liability__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <description>This creates a lookup relationship between a Liability and an Assessment.  This field is required.</description>
    <inlineHelpText>This creates a lookup relationship between a Liability and an Assessment.  This field is required.</inlineHelpText>
    <label>Assessment</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipLabel>Liabilities</relationshipLabel>
    <relationshipName>Liability</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liability__c/fields/Citation_Number__c.field-meta.xml
<CustomField>
    <fullName>Citation_Number__c</fullName>
    <description>Sets the citation number for display on output documents using the required prefixes based on the citation type. Required for use by BOFE AR.</description>
    <formula>IF( !ISBLANK ( Manual_Citation_Number__c ), Manual_Citation_Number__c, 
Case(   Citation_Form_Assessment_Conga__c ,
&#39;BOFE 240A&#39;, &#39;PA &#39;,
&#39;BOFE 240B&#39;, &#39;WA &#39;,
&#39;BOFE 335&#39;, &#39;WC &#39;,
&#39;BOFE 336&#39;, &#39;SO &#39;,
&#39;BOFE 815&#39;, &#39;HC &#39;, 
&#39;BOFE 816&#39;, &#39;HR &#39;,
&#39;BOFE 812&#39;, &#39;C &#39;,
&#39;BOFE 814&#39;, &#39;JL &#39;,
&#39;JEU 238e&#39;, &#39;JS &#39;,
&#39;JEU 238&#39;, &#39;J &#39;,
&#39;LR 240A&#39;, &#39;LR &#39;,
&#39;PW 336&#39;, &#39;PW SO &#39;,
&#39;PW 240A&#39;, &#39;PW PA &#39;, 
&#39;&#39;)
+ 
Right (  Name , 6)
)</formula>
    <label>Citation Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Liability__c/recordTypes/BOFE.recordType-meta.xml
<RecordType>
    <fullName>BOFE</fullName>
    <active>true</active>
    <description>Liabilities from BOFE Cases</description>
    <label>BOFE</label>
</RecordType>

force-app/main/default/objects/Liability__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/Liability_Appeal__c/Liability_Appeal__c.object-meta.xml
<CustomObject>
    <description>Junction object between liablities and appeals. Allows a liability to have multiple appeals where necessary.</description>
    <label>Liability Appeal</label>
    <nameField>
        <displayFormat>LA-{000000}</displayFormat>
        <label>Liability Appeal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability Appeals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Appeal__c/fields/Appeal__c.field-meta.xml
<CustomField>
    <fullName>Appeal__c</fullName>
    <inlineHelpText>Relationship to the appeal for this liability</inlineHelpText>
    <label>Appeal</label>
    <referenceTo>Appeal__c</referenceTo>
    <relationshipLabel>Liability Appeals</relationshipLabel>
    <relationshipName>Liability_Appeals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liability_Appeal__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <inlineHelpText>Relationship to the Liability for this appeal</inlineHelpText>
    <label>Liability</label>
    <referenceTo>Liability__c</referenceTo>
    <relationshipLabel>Liability Appeals</relationshipLabel>
    <relationshipName>Liability_Appeals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/Liable_Party__c.object-meta.xml
<CustomObject>
    <label>Liable Party</label>
    <nameField>
        <displayFormat>LP-{000000}</displayFormat>
        <label>Liable Party ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liable Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liable_Party__c/fields/Appeal_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Appeal_Deadline__c</fullName>
    <label>Appeal Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>This is a link to the Entity that is a Liable Party for a Liability.</description>
    <label>Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Liable Party to Assessments</relationshipLabel>
    <relationshipName>Liable_Parties</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <description>This ties the Liability to One or Many Liable Parties for a specific Assessment. Not-Reparentable</description>
    <inlineHelpText>This ties the Liability to One or Many Liable Parties for a specific Assessment. Not-Reparentable</inlineHelpText>
    <label>Liability</label>
    <referenceTo>Liability__c</referenceTo>
    <relationshipLabel>Liable Parties</relationshipLabel>
    <relationshipName>Liable_Parties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/recordTypes/BOFE.recordType-meta.xml
<RecordType>
    <fullName>BOFE</fullName>
    <active>true</active>
    <description>Used for BOFE Liable Parties</description>
    <label>BOFE</label>
</RecordType>

force-app/main/default/objects/Liable_Party__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/classes/AddAppeal.cls
public with sharing class AddAppeal {

    Id appealRecTypeId_RCI = Schema.SObjectType.Appeal__c.getRecordTypeInfosByName().get('RCI').getRecordTypeId();
    Id appealRecTypeId_BOFE = Schema.SObjectType.Appeal__c.getRecordTypeInfosByName().get('BOFE').getRecordTypeId(); 
    Id appealRecTypeId_DeNovo = Schema.SObjectType.Appeal__c.getRecordTypeInfosByName().get('De Novo').getRecordTypeId(); 
        
    Id caseRecTypeId_RCI = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('RCI').getRecordTypeId();
    Id caseRecTypeId_BOFEIntake = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE Intake').getRecordTypeId();
    Id caseRecTypeId_BOFEInvesg = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE Investigation').getRecordTypeId();

    public DIR_Case__c cs { get; set; } 
    public Appeal__c appeal { get; set; }
    
    
    public AddAppeal(ApexPages.StandardController sc) {
        cs = [SELECT Id, Employer__c, Employer__r.Name, Employer__r.Phone, RecordTypeId FROM DIR_Case__c WHERE Id = :sc.getId()];
        
        LoadAccounts();
        LoadCitations();
        InitAppeal();
    }
    
    public void InitAppeal() {  

        appeal = new Appeal__c();
        appeal.Case__c = cs.Id;
    }
        
   
    public List<AccountWrapper> Accounts { get; set; }
    public void LoadAccounts() {
        List<Affiliation__c> affs = [SELECT Id, Affiliated_Account__c, Affiliated_Account__r.Name, Affiliation_Type__c, Affiliated_Account__r.Phone FROM Affiliation__c WHERE Main_Account__c = :cs.Employer__c];
        Accounts = new List<AccountWrapper>();
        Accounts.add(new AccountWrapper(new Affiliation__c(Affiliated_Account__c = cs.Employer__c,Affiliated_Account__r = cs.Employer__r, Affiliation_Type__c = 'Employer')));
        for (Affiliation__c aff : affs) {
            Accounts.add(new AccountWrapper(aff));
        }
        if (Accounts.size() > 0) {
            Accounts[0].selected = true;
        }
    }
 
    public List<CitationWrapper> Citations { get; set; }
    public void LoadCitations() {
        Id selAccId = null;
        for (AccountWrapper aw : Accounts)
            if (aw.selected)
                selAccId = aw.acc.Affiliated_Account__c;
        List<Liability__c> liabs = [SELECT Id, Citation_Number__c, CreatedDate, Appeal_Deadline__c, Assessment__c, (SELECT Id FROM Liable_Parties__r WHERE Entity__c = :selAccId) FROM Liability__c WHERE (Status__c = 'new' OR Status__c = 'Appeal Withdrawn') AND Case_Management__c = :cs.Id];
        Citations = new List<CitationWrapper>();
        Map<Id, String> assIds = new Map<Id, String>();
        for (Liability__c liab : liabs) {
            Citations.add(new CitationWrapper(liab, liab.Liable_Parties__r.size() > 0));
            assIds.put(liab.Assessment__c, '');
        }
        List<DIR_Violation__c> viols = [SELECT Assessment__c, Violation_Type__r.Name FROM DIR_Violation__c WHERE Assessment__c IN :assIds.keyset()];
        for (DIR_Violation__c viol : viols) {
            assIds.put(viol.Assessment__c, assIds.get(viol.Assessment__c) + viol.Violation_Type__r.Name + '\n');
        }
        for (CitationWrapper cw : Citations) {
            if (assIds.containsKey(cw.liab.Assessment__c)) {
                cw.violations = assIds.get(cw.liab.Assessment__c);
            }
         }
    }  
    
    public PageReference SaveAppeal() {
        
        
        Savepoint sp = Database.setSavepoint();
        try {
            for (AccountWrapper aw : Accounts) {
                if (aw.selected)
                    appeal.Appeal_Request_Entity__c = aw.acc.Affiliated_Account__c; 
            }
            for (CitationWrapper cw : Citations) {
                if (cw.selected)
                    appeal.Citation_Selected__c=true;  
            }
            
            if (cs.RecordTypeId == caseRecTypeId_RCI){
                appeal.RecordTypeId = appealRecTypeId_RCI;
            }
            else if (cs.RecordTypeId == caseRecTypeId_BOFEIntake){
                appeal.RecordTypeId = appealRecTypeId_BOFE;
            }
            else if (cs.RecordTypeId == caseRecTypeId_BOFEInvesg){
                appeal.RecordTypeId = appealRecTypeId_BOFE;
            }
           
            insert appeal;
            
 
            List<Liability_Appeal__c> las = new List<Liability_Appeal__c>();
            for (CitationWrapper cw : Citations) {
                if (cw.selected) {
                    Liability_Appeal__c la = new Liability_Appeal__c();
                    la.Appeal__c = appeal.Id;
                    la.Liability__c = cw.liab.Id;
                    las.add(la);
                }
            }
            insert las;
            
            List<DIR_Appeal_Party__c> aps = new List<DIR_Appeal_Party__c>();
            for (AccountWrapper aw : Accounts) {
                if (aw.selected2) {
                    DIR_Appeal_Party__c ap = aw.party;
                    ap.Appeal__c = appeal.Id;
                    aps.add(ap);
                }
            }
            insert aps;
            update appeal;
        } catch (Exception ex) {
            ApexPages.addMessages(ex);
            Database.rollback(sp);
            return null;
        }
        
        return new PageReference('/' + appeal.Id);
    }
    
    public class AccountWrapper { 
        public Affiliation__c acc { get; set; }
        public boolean selected { get; set; }
        public DIR_Appeal_Party__c party { get; set; }
        public boolean selected2 { get; set; }
        public AccountWrapper(Affiliation__c a) {
            acc = a;
            if (Test.isRunningTest())
                selected = true;
            else
                selected = false;
            
            party = new DIR_Appeal_Party__c();
            party.Entity__c = acc.Affiliated_Account__c;
            
            if (Test.isRunningTest())
                selected2 = true;
            else
                selected2 = false;
        }
    }
    
    public class CitationWrapper { 
        public Liability__c liab { get; set; }
        public boolean selected { get; set; }
        public boolean highlight { get; set; }
        public string lastDay {
            get {
                return Date.today() > liab.Appeal_Deadline__c ? 'No' : 'Yes';
            }
        }
        public string violations { get; set; }
        public CitationWrapper(Liability__c l, boolean h) {
            liab = l;
            if (Test.isRunningTest())
                selected = true;
            else
                selected = false;
            highlight = h;
            violations = '';
        }
    }
    
}