force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>This object is to store a One-To-Many relationship between Accounts and the Addresses they may have</description>
    <label>Location</label>
    <nameField>
        <displayFormat>ADDR-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Active_Location__c.field-meta.xml
<CustomField>
    <fullName>Active_Location__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to track previous addresses for an entity</description>
    <inlineHelpText>Check if this location is believed to be active for the company</inlineHelpText>
    <label>Active Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_2__c.field-meta.xml
<CustomField>
    <fullName>Address_2__c</fullName>
    <description>Address Line 2</description>
    <inlineHelpText>Address Line 2</inlineHelpText>
    <label>Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_3__c.field-meta.xml
<CustomField>
    <fullName>Address_3__c</fullName>
    <description>Address Line 3</description>
    <inlineHelpText>Address Line 3</inlineHelpText>
    <label>Address 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address Line 1</description>
    <inlineHelpText>Address Line 1</inlineHelpText>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/DBA__c.field-meta.xml
<CustomField>
    <fullName>DBA__c</fullName>
    <inlineHelpText>If different than legal entity and primary DBA</inlineHelpText>
    <label>DBA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>This is the master-entity for this address.  Not-Reparentable</description>
    <inlineHelpText>This is the master-entity for this address.  Not-Reparentable</inlineHelpText>
    <label>Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Fax__c.field-meta.xml
<CustomField>
    <fullName>Fax__c</fullName>
    <description>The Fax Number at this location.</description>
    <inlineHelpText>The Fax Number at this location.</inlineHelpText>
    <label>Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>The Telephone number at this address.</description>
    <inlineHelpText>The Telephone number at this address.</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
                <default>true</default>
                <label>CA</label>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Select the type of location at this address</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Business Location</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Job Site</fullName>
            </value>
            <value>
                <fullName>Location of Records</fullName>
            </value>
            <value>
                <fullName>PO Box</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Mailing Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appeal_Party__c/Appeal_Party__c.object-meta.xml
<CustomObject>
    <description>WCA - Parties invloved in a citation claim</description>
    <label>Citation Appeal Party</label>
    <nameField>
        <label>Appeal Parties Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Citation Appeal Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appeal_Party__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Appeal_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appeal_Party__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Appellant</fullName>
            </value>
            <value>
                <fullName>Appellant Attorney</fullName>
            </value>
            <value>
                <fullName>Appellant Representative</fullName>
            </value>
            <value>
                <fullName>Agent for Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BOFE_Low_Wage_Industry__c/BOFE_Low_Wage_Industry__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>holds settings for determining if an account is a low wage industry. Used by the Account_Methods class called by Account_Trigger to set the Low_Wage_Industry_Selection__c field on the account record. The Name field holds the NAICS code prefix and the industry field is the industry related to the NAICS code. The Industry value is returned and set on the Low Wage Industry selection field.</description>
    <label>BOFE Low Wage Industry</label>
</CustomObject>

force-app/main/default/objects/BOFE_Low_Wage_Industry__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allows an administrator to activate or deactivate a NAICS Code/Industry type relationship. On by default, deactivating will prevent the lookup of a NAICS code to result in the selection of an industry type</description>
    <inlineHelpText>Activates this lookup</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BOFE_Low_Wage_Industry__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>Holds the industry value associated with the NAICS code stored as the record name</description>
    <inlineHelpText>Enter the industry to be associated with the NAICS code prefix in the name field.</inlineHelpText>
    <label>Industry</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DBA__c/DBA__c.object-meta.xml
<CustomObject>
    <label>DBA</label>
    <nameField>
        <label>DBA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DBAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DBA__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DBAs</relationshipLabel>
    <relationshipName>DBAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DBA__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <inlineHelpText>Is this DBA currently active or in use?</inlineHelpText>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAICS_Code__c/NAICS_Code__c.object-meta.xml
<CustomObject>
    <description>WCA - 2012 North American Industry Classification System</description>
    <label>NAICS Code</label>
    <nameField>
        <label>NAICS Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAICS Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wage_Claim_Party__c/Wage_Claim_Party__c.object-meta.xml
<CustomObject>
    <description>WCA - Parties involved in a Wage Clainm</description>
    <label>Wage Claim Party</label>
    <nameField>
        <label>Wage Claim Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wage Claim Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wage_Claim_Party__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wage Claim Parties</relationshipLabel>
    <relationshipName>Wage_Claim_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wage_Claim_Party__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>if(NOT(ISBLANK(Contact__c)), Contact__r.Phone &amp; IF(NOT(ISBLANK(Contact__r.Phone_Ext__c)), &#39; x&#39; &amp; Contact__r.Phone_Ext__c, &#39;&#39;), IF(NOT(ISBlANK(Account__c)), Account__r.Phone &amp; IF(NOT(ISBLANK(Account__r.Phone_Ext__c)), &#39; x&#39; &amp; Account__r.Phone_Ext__c, &#39;&#39;), &#39;&#39;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wage_Claim_Party__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Claimant Attorney</fullName>
            </value>
            <value>
                <fullName>Claimant Representative</fullName>
            </value>
            <value>
                <fullName>Claimant Advocate</fullName>
            </value>
            <value>
                <fullName>Claimant Other</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
            <value>
                <fullName>Defendant Attorney</fullName>
            </value>
            <value>
                <fullName>Defendant Representative</fullName>
            </value>
            <value>
                <fullName>Merchant</fullName>
            </value>
            <value>
                <fullName>Agent for Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <description>Holds the zip codes and cities in which a zip code is located and supports the assigning records based on zip codes.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City the zip code is within</description>
    <inlineHelpText>Enter the city that this zip code is in.</inlineHelpText>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Account_Methods.cls
public class Account_Methods {
    
    
    public static void beforeInsert(list<Account> newList){
        //after insert method calls
        // Update the Low Wage Industry selection
        updateIndustrySelection(newList);
    }
    
    // after insert method calls
    public static void afterInsert(list<Account> newList){
        addPrimaryAddress(newList);
    }
    
    public static void beforeUpdate(list<Account> newList, Map<Id, Account> oldList){
        //after insert method calls
        // Update the Low Wage Industry selection
        updateIndustrySelection(newList);
        updatePrimaryAddress(newList, oldList);
    }
    
    
    public static void afterUpdate(List<Account> newList, Map<Id, Account> oldMap) {
        
        Set<Id> accountIds = new Set<Id>();
        for(Account acct : newList) {
            if(acct.Name != oldMap.get(acct.Id).Name) {
                accountIds.add(acct.Id);
            }
        }
        
        //List<Wage_Claim_Party__c> wcpToUpdate = [Select Id From Wage_Claim_Party__c Where Account__c IN :accountIds];
        //if(wcpToUpdate.size() > 0) {
            //update wcpToUpdate;
       // }
        
        List<Appeal_Party__c> apToUpdate = [Select Id From Appeal_Party__c Where Account__c IN :accountIds];
        if(apToUpdate.size() > 0) {
            update apToUpdate;
        }
    }
    
    // Uses the Naics code and the BOFE Low Wage Industry custom setting to set the low wage industry on the account
    public static void updateIndustrySelection(list<Account> acctList){
        list<string> Naics = new list<string>();
        map<Id, string> naicsMap = new map<Id, string>();
        Map<Id, Id> accMap = new Map<Id, Id>();
        
        system.debug('pe aici3');
        Set<Id> NaicsSet = new Set<Id>();
        for (Account acc : acctList){
            if (acc.Naics_code__c != null){
                NaicsSet.add(acc.Naics_code__c);
                accMap.put(acc.Id, acc.Naics_code__c);
            }
        }
        
        List<NAICS_Code__c> NaicsList = new List<NAICS_Code__c>();
        NaicsList = [SELECT Id, Name FROM NAICS_Code__c WHERE Id IN : NaicsSet];
        for (NAICS_Code__c nc : NaicsList)
            naicsMap.put(nc.Id, nc.Name);
        
        Map<String, BOFE_Low_Wage_Industry__c> Industry_Selection = new Map<String, BOFE_Low_Wage_Industry__c>();
        //get all the NAICS Code >> industry matches into map
        BOFE_Low_Wage_Industry__c Industry = BOFE_Low_Wage_Industry__c.getInstance();
        Industry_Selection = BOFE_Low_Wage_Industry__c.getAll();
        
        for(Account a : acctList){
            if(a.Naics_code__c != null){
                //Naics.add(a.NAICS_Code__r.name);
                //naicsMap.add(a, a.NAICS_Code__r.name);
            //}
            //if(Naics.size() > 0){
                system.debug('NAICS Code set on record');
                //list<Account> accountToUpdate = new list<account>();
                
                String resultIndustry = null;
                // first lookup of map value   
                if ((accMap.containsKey(a.Id)) && (naicsMap.containsKey(accMap.get(a.Id)))){             
                    String naicsCode = naicsMap.get(accMap.get(a.Id));
                    String helpvar;
                    if ((Industry_Selection.containsKey(naicsCode)) && (Industry_Selection.get(naicsCode).Active__c == true))
                        resultIndustry = Industry_Selection.get(naicsCode).Industry__c;
                    //system.debug('****** resultIndustry: ' + resultIndustry);
                    else{
                        helpvar = naicsCode.Left(5);
                        if ((Industry_Selection.containsKey(helpvar)) && (Industry_Selection.get(helpvar).Active__c == true)){
                            system.debug('First industry lookup failed, attempting lookup on 5 characters');
                            resultIndustry = Industry_Selection.get(helpvar).Industry__c;
                        }
                        else{
                            helpvar = naicsCode.Left(4);
                            if ((Industry_Selection.containsKey(helpvar)) && (Industry_Selection.get(helpvar).Active__c == true)){
                                system.debug('First industry lookup failed, attempting lookup on 4 characters');
                                resultIndustry = Industry_Selection.get(helpvar).Industry__c;
                            }
                            else{
                                helpvar = naicsCode.Left(3);
                                if ((Industry_Selection.containsKey(helpvar)) && (Industry_Selection.get(helpvar).Active__c == true)){
                                    system.debug('First industry lookup failed, attempting lookup on 3 characters');
                                    resultIndustry = Industry_Selection.get(helpvar).Industry__c;
                                }
                                else{
                                    helpvar = naicsCode.Left(2);
                                    if ((Industry_Selection.containsKey(helpvar)) && (Industry_Selection.get(helpvar).Active__c == true)){
                                        system.debug('First industry lookup failed, attempting lookup on 2 characters');
                                        resultIndustry = Industry_Selection.get(helpvar).Industry__c;
                                    }
                                    else resultIndustry = 'Other';
                                }
                            }
                        }
                    }
                    
                }
                
                a.Low_wage_industry_selection__c = resultIndustry;
                
            }
            
        }
    }
    
    public static void addPrimaryAddress(list<Account> acctList){
        // create primary address from the address entered on the account
         
        string personRt = Schema.sObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeID();
        
        list<Address__c> loc = new list<Address__c>();
        for (Account a : acctList){
            Address__c addr = new Address__c();
            Address__c addr1 = new Address__c();
            addr1.Entity__c = a.Id;
            addr.entity__c = a.ID;
            if( a.RecordTypeId != personRt){
                system.debug('##### begin building business primary address');
                if( a.ShippingCity == NULL && a.ShippingState == null && a.ShippingPostalCode == null ){
                    system.debug('##### address details blank for buisness account. Skipping');
                    continue;
                }
                
                if(a.ShippingStreet != null && a.ShippingStreet != ''){
                    //parse address field
                    list<String> addString = new list<String>();
                    addString = a.ShippingStreet.split('\r\n');
                    if (addString.size() > 0){ 
                        addr.address__c = addString.get(0);
                    }
                    if (addString.size() > 1){ 
                        addr.address_2__c = addString.get(1);
                    }
                    if (addString.size() == 3){ 
                        addr.address_3__c = addString.get(2);
                    } 
                }
                addr.City__c = a.ShippingCity;
                addr.State__c = a.ShippingState;
                addr.Zip_Code__c = a.ShippingPostalCode;
                addr.Phone__c = a.Phone;
                addr.Fax__c = a.Fax;
                addr.Active_Location__c = true;
                addr.Type__c = 'Primary';
                system.debug('##### Adding business address: ' + addr);
                loc.add(addr);
            }
                        
            else{
                // add addresses for person accounts
                system.debug('##### begin building person account address');
                if( a.PersonMailingCity != NULL && a.PersonMailingState != NULL && a.PersonMailingPostalCode != NULL){
                    system.debug('##### building home address for person account');
                    if( a.PersonMailingStreet != null && a.PersonMailingStreet != '' ){
                        //parse address field
                        list<String> addString = new list<String>();
                        addString = a.PersonMailingStreet.split('\r\n');
                        if (addString.size() > 0){ 
                            addr.address__c = addString.get(0);
                        }
                        if (addString.size() > 1){ 
                            addr.address_2__c = addString.get(1);
                        }
                        if (addString.size() == 3){ 
                            addr.address_3__c = addString.get(2);
                        } 
                        addr.City__c = a.PersonMailingCity;
                        addr.State__c = a.PersonMailingState;
                        addr.Zip_Code__c = a.PersonMailingPostalCode;
                        addr.Phone__c = a.Phone;
                       // addr.Fax__c = a.Fax;
                        addr.Active_Location__c = true;
                        addr.Type__c = 'Home';
                       // addr.DBA__c = a.DBA__c;
                       system.debug('##### Adding home address for person account ' + addr);
                       loc.add(addr);
                    }                       
                }
                // build primary address for person account
                if( a.ShippingCity != NULL && a.ShippingState != NULL && a.ShippingPostalCode != NULL){
                    system.debug('##### building home address for person account');
                    if( a.ShippingStreet != null && a.ShippingStreet != '' ){
                        //parse address field
                        list<String> addString = new list<String>();
                        addString = a.ShippingStreet.split('\r\n');
                        if (addString.size() > 0){ 
                            addr1.address__c = addString.get(0);
                        }
                        if (addString.size() > 1){ 
                            addr1.address_2__c = addString.get(1);
                        }
                        if (addString.size() == 3){ 
                            addr1.address_3__c = addString.get(2);
                        } 
                        addr1.City__c = a.ShippingCity;
                        addr1.State__c = a.ShippingState;
                        addr1.Zip_Code__c = a.ShippingPostalCode;
                        addr1.Phone__c = a.Phone;
                       // addr.Fax__c = a.Fax;
                        addr1.Active_Location__c = true;
                        addr1.Type__c = 'Primary';
                       // addr.DBA__c = a.DBA__c;
                       system.debug('##### Adding primary address for person account ' + addr);
                       loc.add(addr1);
                    }                       
                }
                 
            }
        }
        if(loc.size() > 0){
            insert loc;
        }
        
    }
    
    //update the primary address when the address changes on an account
    public static void updatePrimaryAddress(list<account> newList, Map<ID, Account> oldMap){
        list<Account> addChanged = new list<Account>();
        // check to see if the address has changed
        for(Account a : newList){
            if(a.ShippingStreet != oldmap.get(a.id).ShippingStreet
               || a.ShippingCity != oldmap.get(a.id).ShippingCity
               || a.ShippingState != oldmap.get(a.id).ShippingState
               || a.ShippingPostalCode != oldmap.get(a.id).ShippingPostalCode
               || a.PersonMailingPostalCode != oldmap.get(a.id).PersonMailingPostalCode
               || a.PersonMailingState != oldmap.get(a.id).PersonMailingState
               || a.PersonMailingCity != oldmap.get(a.id).PersonMailingCity
               || a.PersonMailingStreet != oldmap.get(a.id).PersonMailingStreet
              ){
                system.debug('##### address changed for account ' + a.Id);  
                addChanged.add(a);
            }
        }
        
        if (!addChanged.isEmpty()){
            //get list of active headquarters addresses
            list<Address__c> addList = [Select ID, Address__c, Address_2__c, Address_3__c, City__c, State__c, Zip_code__c, Type__c, Active_Location__c FROM Address__c where Entity__c in :newList and (Type__c = 'Primary' OR Type__c = 'Home') AND Active_Location__C = true];
            
            // Deactivate the previous headquarters location
            if (!addList.isEmpty()){
                for(Address__c a : addList){
                    a.Active_Location__c = false;
                }
                update addList;
            }
            // add the changed address as the new headquarters address
            addPrimaryAddress(addChanged);
        }
    }
}