force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>This object is to store a One-To-Many relationship between Accounts and the Addresses they may have</description>
    <label>Location</label>
    <nameField>
        <displayFormat>ADDR-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Active_Location__c.field-meta.xml
<CustomField>
    <fullName>Active_Location__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to track previous addresses for an entity</description>
    <inlineHelpText>Check if this location is believed to be active for the company</inlineHelpText>
    <label>Active Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address Line 1</description>
    <inlineHelpText>Address Line 1</inlineHelpText>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>This is the master-entity for this address.  Not-Reparentable</description>
    <inlineHelpText>This is the master-entity for this address.  Not-Reparentable</inlineHelpText>
    <label>Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Select the type of location at this address</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Business Location</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Job Site</fullName>
            </value>
            <value>
                <fullName>Location of Records</fullName>
            </value>
            <value>
                <fullName>PO Box</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Mailing Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Role__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This field maintains the relationship between the Case Role and the Case.  Reparentable.</description>
    <inlineHelpText>This field maintains the relationship between the Case Role and the Case.  Reparentable.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Role</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Case_Role_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Role_Status__c</fullName>
    <description>For requirement 33146; allows users to quickly view the status of related case roles to a given case record.</description>
    <label>Case Role Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>ODA - Defendant</fullName>
            </value>
            <value>
                <fullName>ODA - Plaintiff</fullName>
            </value>
            <value>
                <fullName>ODA by Settlement</fullName>
            </value>
            <value>
                <fullName>Dismissal - Claimant</fullName>
            </value>
            <value>
                <fullName>Dismissal - Deputy</fullName>
            </value>
            <value>
                <fullName>Dismissal - Ineffective service</fullName>
            </value>
            <value>
                <fullName>No Longer Active On Case</fullName>
            </value>
            <value>
                <fullName>De Novo Appeal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</description>
    <inlineHelpText>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Roles</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Provides ability to tie the location to a case role</description>
    <inlineHelpText>Select the location for the related account</inlineHelpText>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Entity__c</field>
            <operation>equals</operation>
            <valueField>Address__c.Entity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Case Roles</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Roles that related accounts have on a case</description>
    <inlineHelpText>Select the role played by this related account</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Agent for Service of Process</fullName>
            </value>
            <value>
                <fullName>Aggrieved</fullName>
            </value>
            <value>
                <fullName>Assignee</fullName>
            </value>
            <value>
                <fullName>Attorney for Defendant</fullName>
            </value>
            <value>
                <fullName>Attorney for Plaintiff</fullName>
            </value>
            <value>
                <fullName>Attorney Representative</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Case Employer</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Chief</fullName>
            </value>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Claimant Advocate</fullName>
            </value>
            <value>
                <fullName>Claimant Assignee</fullName>
            </value>
            <value>
                <fullName>Claimant Attorney</fullName>
            </value>
            <value>
                <fullName>Claimant Guardian</fullName>
            </value>
            <value>
                <fullName>Claimant Minor</fullName>
            </value>
            <value>
                <fullName>Claimant Other</fullName>
            </value>
            <value>
                <fullName>Claimant Representative</fullName>
            </value>
            <value>
                <fullName>Client Employer</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>Contractor Successor</fullName>
            </value>
            <value>
                <fullName>Corporate Officer</fullName>
            </value>
            <value>
                <fullName>Court</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
            <value>
                <fullName>Defendant - (Restitution)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Number_of_Employer_s__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Employer_s__c</fullName>
    <label>Number of Employer(s)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/caseRollMethods.cls
public class caseRollMethods {
// methods for triggers on case role


//on insert  - before  trigger.
    //set the location on the case role to be the primary location of the account
    public static void applyLocation(list<Case_Role__c> newList){
        system.debug('Setting location on case role');
        //get the accounts on each case role
        set<ID> acctIDs = new set<ID>();
        for (Case_Role__c cr : newList){
            acctIDs.add(cr.Entity__c);
            system.debug('Added entity: ' + cr.Entity__c + ' to account set');
        }
     
        list<Address__c> locList = new list<Address__c>([SELECT ID, Entity__c from Address__c Where Active_Location__c = true AND Type__c = 'Primary' AND Entity__c in :acctIDs]);
        system.debug('locList::: ' + locList);
        
        Map<ID, Address__c> locMap = new Map<ID, Address__c>();
        for(Address__c a : locList){
            locMap.put(a.Entity__c, a);
        }
        
      
        if(locMap.size() > 0){
            for (Case_Role__c cr : newList){
                if (locMap.containsKey(cr.Entity__c)){
                    Address__c addr = locMap.get(cr.Entity__c);
                    system.debug('Address to add as location:::' + addr);
                    cr.location__c = addr.id;
                }
                
            }
      
        } 
  
      
  }
        public static void countDefs(list<Case_Role__c> newList){
            String[] crType = new String[]{'Defendant','Case Employer'};
            set<ID> CaseIDs = new set<ID>();
            for(Case_Role__c cr: newList ){
                    CaseIDs.add(cr.Case__c); 
            }
            list<Case_Role__c> defCRs = new list<Case_Role__c>([SELECT ID, Role__c, Case__c FROM Case_Role__c WHERE Case_Role_Status__c != 'No Longer Active On Case' AND Case__c IN :CaseIDs AND Role__c IN :crType]);
//            system.debug('Number of defendant case roles found is:: ' + defCRs.size() + ' on case :: ' + CaseIDs + ' list of case roles is :: ' + defCRs );
			list<DIR_Case__c> cases = new list<DIR_Case__c>([SELECT ID, Number_of_Employer_s__c FROM DIR_Case__c Where ID IN :CaseIDs ]);
            for(DIR_Case__c defCase : cases){
                defCase.Number_of_Employer_s__c = defCRs.size();
                update defCase;
            }
         }


    
}