force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>This object is to store a One-To-Many relationship between Accounts and the Addresses they may have</description>
    <label>Location</label>
    <nameField>
        <displayFormat>ADDR-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address Line 1</description>
    <inlineHelpText>Address Line 1</inlineHelpText>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>This is the master-entity for this address.  Not-Reparentable</description>
    <inlineHelpText>This is the master-entity for this address.  Not-Reparentable</inlineHelpText>
    <label>Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
                <default>true</default>
                <label>CA</label>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BOFE_Low_Wage_Industry__c/BOFE_Low_Wage_Industry__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>holds settings for determining if an account is a low wage industry. Used by the Account_Methods class called by Account_Trigger to set the Low_Wage_Industry_Selection__c field on the account record. The Name field holds the NAICS code prefix and the industry field is the industry related to the NAICS code. The Industry value is returned and set on the Low Wage Industry selection field.</description>
    <label>BOFE Low Wage Industry</label>
</CustomObject>

force-app/main/default/objects/BOFE_Low_Wage_Industry__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allows an administrator to activate or deactivate a NAICS Code/Industry type relationship. On by default, deactivating will prevent the lookup of a NAICS code to result in the selection of an industry type</description>
    <inlineHelpText>Activates this lookup</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BOFE_Low_Wage_Industry__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>Holds the industry value associated with the NAICS code stored as the record name</description>
    <inlineHelpText>Enter the industry to be associated with the NAICS code prefix in the name field.</inlineHelpText>
    <label>Industry</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAICS_Code__c/NAICS_Code__c.object-meta.xml
<CustomObject>
    <description>WCA - 2012 North American Industry Classification System</description>
    <label>NAICS Code</label>
    <nameField>
        <label>NAICS Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAICS Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NAICS_Code__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
            </value>
            <value>
                <fullName>Level 4</fullName>
            </value>
            <value>
                <fullName>Level 5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAICS_Code__c/fields/NAICS_Title__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Title__c</fullName>
    <label>NAICS Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAICS_Code__c/fields/Supersector__c.field-meta.xml
<CustomField>
    <fullName>Supersector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supersector</label>
    <referenceTo>NAICS_Code__c</referenceTo>
    <relationshipLabel>Subsectors</relationshipLabel>
    <relationshipName>Subsector</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <description>Holds the zip codes and cities in which a zip code is located and supports the assigning records based on zip codes.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City the zip code is within</description>
    <inlineHelpText>Enter the city that this zip code is in.</inlineHelpText>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/account_MethodsTest.cls
@istest
public class account_MethodsTest {

    public static testMethod void testUpdateIndustrySelection(){
        
        NAICS_Code__c other = new NAICS_Code__c();
        other.Name = '2';
        other.NAICS_Title__c = 'other';
        other.Level__c = 'Level 1';
        insert other;
        
        NAICS_Code__c level1 = new NAICS_Code__c();
        level1.Name = '11';
        level1.NAICS_Title__c = 'TEST1';
        level1.Level__c = 'Level 1';
        insert level1;
        
        NAICS_Code__c level2 = new NAICS_Code__c();
        level2.Name = '111';
        level2.NAICS_Title__c = 'TEST2';
        level2.Level__c = 'Level 2';
        level2.Supersector__c = level1.Id;
        insert level2;
        
        NAICS_Code__c level3 = new NAICS_Code__c();
        level3.Name = '1111';
        level3.NAICS_Title__c = 'TEST3';
        level3.Level__c = 'Level 3';
        level3.Supersector__c = level2.Id;
        insert level3;
        
        NAICS_Code__c level4 = new NAICS_Code__c();
        level4.Name = '11111';
        level4.NAICS_Title__c = 'TEST4';
        level4.Level__c = 'Level 4';
        level4.Supersector__c = level3.Id;
        insert level4;
        
        NAICS_Code__c level5 = new NAICS_Code__c();
        level5.Name = '111111';
        level5.NAICS_Title__c = 'TEST5';
        level5.Level__c = 'Level 5';
        level5.Supersector__c = level4.Id;
        insert level5;
        
        BOFE_Low_Wage_Industry__c Industry = new BOFE_Low_Wage_Industry__c();
        Industry.name = '111111';
        Industry.Industry__c = 'retail';
        Industry.active__c = true;
        insert Industry;
        
        BOFE_Low_Wage_Industry__c Industry1 = new BOFE_Low_Wage_Industry__c();
        Industry1.name = '11111';
        Industry1.Industry__c = 'Construction';
        Industry1.active__c = true;
        insert Industry1;
        
        BOFE_Low_Wage_Industry__c Industry2 = new BOFE_Low_Wage_Industry__c();
        Industry2.name = '1111';
        Industry2.Industry__c = 'Garment';
        Industry2.active__c = true;
        insert Industry2;
        
        BOFE_Low_Wage_Industry__c Industry3 = new BOFE_Low_Wage_Industry__c();
        Industry3.name = '111';
        Industry3.Industry__c = 'Warehouse';
        Industry3.active__c = true;
        insert Industry3;
        
        BOFE_Low_Wage_Industry__c Industry4 = new BOFE_Low_Wage_Industry__c();
        Industry4.name = '11';
        Industry4.Industry__c = 'Janitorial';
        Industry4.active__c = true;
        insert Industry4;
        
        Account a = new Account();
        a.Name = 'Lucian395274';
        
        insert a;
        
        test.startTest();
        a.Naics_code__c = level5.id;
        update a;
        //system.assert(a.Low_wage_Industry_Selection__c == 'retail');
        
        a.NAICS_Code__c = level4.Id;
        update a;
        //system.assert(a.Low_wage_Industry_Selection__c == 'Construction');
        
        a.NAICS_Code__c = level3.Id;
        update a;
        //system.assert(a.Low_wage_Industry_Selection__c == 'Garment');
        
        a.NAICS_Code__c = level2.Id;
        update a;
        //system.assert(a.Low_wage_Industry_Selection__c == 'Warehouse');
        
        a.NAICS_Code__c = level1.Id;
        update a;
        //system.assert(a.Low_wage_Industry_Selection__c == 'Janitorial');
        
        a.NAICS_Code__c = other.Id;
        update a;
        //system.assert(a.Low_wage_Industry_Selection__c == 'Other');
        test.stopTest();
    }
    
    @isTest static void testAddPrimaryAddress(){
        
        Account a1 = new Account(
            Name = 'test acct'
        );
        insert a1;
        
        List<Address__c> locations1 = new List<Address__c>([
            SELECT Id, City__c, State__c, Zip_Code__c FROM Address__c WHERE entity__c =: a1.Id
        ]);
        
        system.assertEquals(0, locations1.size());
        
        Account a2 = new Account(
            Name = 'test acct 123',
            ShippingStreet = '123 fake st\r\nBldg A\r\nUnit A',
            ShippingCity = 'Denver',
            ShippingState = 'CO',
            ShippingPostalCode = '80212'
        );
        insert a2;
        
        List<Address__c> locations2 = new List<Address__c>([
            SELECT Id, City__c, State__c, Zip_Code__c FROM Address__c WHERE entity__c =: a2.Id
        ]);
        
        system.assertEquals(1, locations2.size());
        
        Address__c loc = locations2[0];
        
        system.assertEquals(a2.ShippingCity, loc.City__c);
        
        system.assertEquals(a2.ShippingState, loc.State__c);
        
        system.assertEquals(a2.ShippingPostalCode, loc.Zip_Code__c);
        
        insert new List<Account>{new Account(RecordTypeId =  Schema.sObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeID(), lastName = 'test',FirstName = 'test',
                            PersonMailingCity = 'test',PersonMailingState = 'test',PersonMailingPostalCode = 'test',
                            PersonMailingStreet = 'test'),
                            
                            new Account(RecordTypeId =  Schema.sObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeID(), lastName = 'test',FirstName = 'test',
                            PersonMailingCity = 'test',PersonMailingState = 'test',PersonMailingPostalCode = 'test',
                            shippingCity = 'test',shippingState = 'test',shippingPostalCode = 'test',shippingStreet = 'test')
        };
                            
                            
    }
}