force-app/main/default/objects/Case_Payment__c/Case_Payment__c.object-meta.xml
<CustomObject>
    <description>Receipt applied to a Case. May have zero or more Liability Payments and zero or more Judgment Payments.</description>
    <label>Case Payment</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Payment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <inlineHelpText>Case that this Payment has been applied to</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Payments</relationshipLabel>
    <relationshipName>Case_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Allocations Recommended</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>ITEM insert</fullName>
                <isActive>false</isActive>
                <label>ITEM insert</label>
            </value>
            <value>
                <fullName>same</fullName>
                <isActive>false</isActive>
                <label>same</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Payment__c/fields/Transmittal__c.field-meta.xml
<CustomField>
    <fullName>Transmittal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The transmittal that this check is a part of. Set via batch apex that runs nightly to collect all payments generated since the last transmittal into a new transmittal.</description>
    <inlineHelpText>The transmittal this payment is a part of.</inlineHelpText>
    <label>Transmittal</label>
    <referenceTo>Transmittal__c</referenceTo>
    <relationshipLabel>Case Payments</relationshipLabel>
    <relationshipName>Case_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Payment__c/fields/Transmittal_Unit__c.field-meta.xml
<CustomField>
    <fullName>Transmittal_Unit__c</fullName>
    <formula>TEXT(Receipt__r.Office_Unit__c)</formula>
    <inlineHelpText>aka &quot;Office Unit&quot;</inlineHelpText>
    <label>Transmittal Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Payment__c/recordTypes/BOFE.recordType-meta.xml
<RecordType>
    <fullName>BOFE</fullName>
    <active>true</active>
    <description>BOFE Case Payments</description>
    <label>BOFE</label>
</RecordType>

force-app/main/default/objects/Case_Payment__c/recordTypes/Posted.recordType-meta.xml
<RecordType>
    <fullName>Posted</fullName>
    <active>true</active>
    <description>Prevents editing of a Case Payment that has been applied (or posted).</description>
    <label>Posted</label>
</RecordType>

force-app/main/default/objects/Case_Payment__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>BOFE Stay</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Citation or Other Issues</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Unable to Pursue</fullName>
            </value>
            <value>
                <fullName>Returned to Claimant</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Waiting for Litigation</fullName>
            </value>
            <value>
                <fullName>New AutoRefer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/JEU.recordType-meta.xml
<RecordType>
    <fullName>JEU</fullName>
    <active>true</active>
    <description>JEU Cases, may or may not be affiliated with BOFE, WCA or RCI cases.</description>
    <label>JEU</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/recordTypes/PASS.recordType-meta.xml
<RecordType>
    <fullName>PASS</fullName>
    <active>true</active>
    <description>Wage Pass Through Records</description>
    <label>PASS</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <description>Vertiba</description>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/Transmittal__c/Transmittal__c.object-meta.xml
<CustomObject>
    <description>Used for the batching of payments into daily transmittals to AR</description>
    <label>Transmittal</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Transmittal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transmittals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transmittal__c/recordTypes/BOFE.recordType-meta.xml
<RecordType>
    <fullName>BOFE</fullName>
    <active>true</active>
    <description>Used for BOFE transmittals of checks to BOFE AR</description>
    <label>BOFE</label>
</RecordType>

force-app/main/default/classes/TransmittalBatch.cls
global without sharing class TransmittalBatch implements Database.Batchable<sObject>, Database.Stateful {
    public Id transmittalId;
    
    public String cpsEligible = '';
    
    
    public TransmittalBatch(Id transId) {
        transmittalId = transId;
    }
    
    global Database.QueryLocator start(Database.BatchableContext info){ 

        //TODO: verify these filters, clean up extraneous filters
        return Database.getQueryLocator(
            'SELECT Id, Transmittal__c, Transmittal_Unit__c, Status__c, Case__c, Case__r.Id '
                + 'FROM Case_Payment__c '
                + 'WHERE RecordType.Name = \'Posted\' '
                    + 'AND Status__c = \'Posted\' '
                    + 'AND Transmittal__c = null '
                    + 'AND (Transmittal_Unit__c = \'CCU 32\' '
                        + 'OR Transmittal_Unit__c = \'JEU\' '
                        + 'OR Transmittal_Unit__c = \'RCI\') '
                    + 'AND (Case__r.RecordType.Name LIKE \'%BOFE%\' '
                        + 'OR Case__r.RecordType.Name LIKE \'%PASS%\' '
                        + 'OR Case__r.RecordType.Name LIKE \'%RCI%\' '
                        + 'OR Case__r.RecordType.Name LIKE \'%JEU%\')'
        );
        
    }
    
    global void execute(Database.BatchableContext info, List<sObject> scopeX){
        List<Case_Payment__c> scope = (List<Case_Payment__c>)scopeX;
        
        if(scope.isEmpty()){
            cpsEligible = '<br>There were no unbatched Case Payments that fit the criteria for Transmittal batching. This Transmittal has zero Case Payments.';
        }else{
            for(Case_Payment__c cp : scope) {
                cp.Transmittal__c = transmittalId;
            }
            update scope; 
        }
    }
    
    global void finish(Database.BatchableContext info) {
        AsyncApexJob job = [SELECT Id, ApexClassId, CompletedDate, CreatedBy.Email, CreatedBy.Name,
                                CreatedDate, JobItemsProcessed, JobType, NumberOfErrors, Status, TotalJobItems
                            FROM AsyncApexJob
                            WHERE Id = :info.getJobId()];
        
        sendJobCompleteEmail(job);
    }
    
    private void sendJobCompleteEmail(AsyncApexJob job) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {job.CreatedBy.Email};
        String transURL = URL.getSalesforceBaseUrl().toExternalForm() + '/' + transmittalId;
        string html = ''
            + '<div style="font: bold 16px Arial; margin: 10px 0;">The transmittal you requested is now complete. You can now run the transmittal report to see the results.</div><br/>'
            + '<div style="font: bold 16px Arial; margin: 10px 0;">If there was at least one item in the batch, click <a href="'+ transURL + '">here</a> to view the Transmittal record, or copy and paste this link into your browser: <a href="'+ transURL + '">' + transURL + '</a><br/><br/></div>'
            + '<div style="font: bold 16px Arial; margin: 10px 0;">AsyncApexJob:</div>'
            + '<table style="font: normal 12px verdana;" border="1" cellpadding="5" cellspacing="0" width="100%">'
            + '<tr style="font-weight: bold">'
            + '<td>Total Job Items</td>'
            + '<td>Job Items Processed</td>'
            + '<td>Number of Errors</td>'
            + '<td>Status</td>'
            //+ '<td>Apex Class Id</td>'
            + '<td>Job Type</td>'
            + '<td>Created By</td>'
            + '<td>Created Date</td>'
            + '<td>Completed Date</td>'
            + '</tr>'
            + '<tr>'
            + '<td>' + job.TotalJobItems + '</td>'
            + '<td>' + job.JobItemsProcessed + '</td>'
            + '<td>' + job.NumberOfErrors + '</td>'
            + '<td>' + job.Status + cpsEligible + '</td>'
            //+ '<td><a href="https://login.salesforce.com/' + job.ApexClassId + '">' + job.ApexClassId + '</a></td>'
            + '<td>' + job.JobType + '</td>'
            + '<td>' + job.CreatedBy.Name + '</td>'
            + '<td>' + job.CreatedDate + '</td>'
            + '<td>' + job.CompletedDate + '</td>'
            + '</tr>'
            + '</table>'
            + '<br/>';
        mail.setToAddresses(toAddresses);
        mail.setCcAddresses(new List<String>{'mteixeira@dir.ca.gov'});
        mail.setSubject('Transmittal Batch - ' + job.Status);
        mail.setHtmlBody(html);
        if (!Test.isRunningTest()) {
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }
}