force-app/main/default/objects/Case_Payment__c/Case_Payment__c.object-meta.xml
<CustomObject>
    <description>Receipt applied to a Case. May have zero or more Liability Payments and zero or more Judgment Payments.</description>
    <label>Case Payment</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Payment__c/fields/CP_Index__c.field-meta.xml
<CustomField>
    <fullName>CP_Index__c</fullName>
    <description>Used solely by the Incoming Check Log code. No need to be on any page layout or report type.</description>
    <label>CP Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case_Payment__c/fields/Deduction_Payment__c.field-meta.xml
<CustomField>
    <fullName>Deduction_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Signifies that this CP record is a deduction payment, i.e., Payment Amount - Net Amount</description>
    <label>Deduction Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Payment__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Case Payments</relationshipLabel>
    <relationshipName>Case_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Payment__c/recordTypes/PAGA.recordType-meta.xml
<RecordType>
    <fullName>PAGA</fullName>
    <active>true</active>
    <description>PAGA Case Payments</description>
    <label>PAGA</label>
</RecordType>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position the employee holds</description>
    <inlineHelpText>Select the position the employee holds</inlineHelpText>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Senior Deputy</fullName>
            </value>
            <value>
                <fullName>Deputy</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>CIU</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Registration_Services</fullName>
                <label>Registration Services</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <description>Represents a receivable: an incoming payment, or an advice of incoming funds. [Encompasses the former Payment Log, Payment Group and Receipt objects to 1 single object.]</description>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RCT-{0000000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Deduction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deduction_Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Deduction amount if any</description>
    <label>Deduction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Index__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Index__c</fullName>
    <label>Receipt Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ReceiptsGridController.cls
public class ReceiptsGridController {
    
    @AuraEnabled
    public static List<RecordType> getRecTypeIds(){
        List<RecordType> recTypeList = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Case_Payment__c'];
        return recTypeList;
    }
   
    @AuraEnabled
    public static Map<Id, Id> saveReceiptCaseServer(String receipts, String casePmts, Boolean isEdited) { 
        System.debug('In Save Receipts Controller apxc');
        //List receiptId = '';
        Map<Id, Id> receiptCaseId = new Map<Id, Id>();
        
        DIR_Employee__c dirEmpl = new DIR_Employee__c();
        try {
            dirEmpl = [Select Id, Name FROM DIR_Employee__c WHERE Position__c = 'Cashiering' AND User__c = :UserInfo.getUserId() Limit 1];
        } catch(Exception e) {
            dirEmpl = null;
        }
        
        //String jsonStr = '\''+receipts+'\'';
        System.debug(receipts);
        List<Receipt__c> deserializedPayment = (List<Receipt__c>) JSON.deserialize(receipts, List<Receipt__c>.class);
        System.debug('________________________________________________deserializedPayment____________________________________________');
       	System.debug(deserializedPayment);
        List<Case_Payment__c> deserializedCases = (List<Case_Payment__c>) JSON.deserialize(casePmts, List<Case_Payment__c>.class);
        System.debug('________________________________________________deserializedCases____________________________________________');
       	System.debug(deserializedCases);
        
        if (deserializedPayment != null && deserializedPayment.size() > 0) {
            receiptCaseId = createRctCaseRecord(deserializedPayment, deserializedCases, isEdited);
        }
        return receiptCaseId;
    }
    
    private static Map<Id, Id> createRctCaseRecord(List<Receipt__c> receipts, List<Case_Payment__c> casePmts, Boolean isEdited) {
        Integer rctIndex;
        Integer caseIndex; 
        ID newRctId;
        Boolean deducVal;
        Map<Integer, Id> receiptMap = new Map<Integer, Id>();
        Map<Id, Id> rctCaseMap = new Map<Id, Id>();
        
        if (!isEdited) {
            //System.debug('insert Receipt');
            List<Receipt__c> receiptList = new List<Receipt__c> ();
            List<Case_Payment__c> caseList = new List<Case_Payment__c> ();
            for (Receipt__c eachReceipt : receipts) {
                receiptList.add(eachReceipt);
            }
            insert receiptList;
            
            for(Receipt__c receipt : receiptList){
                newRctId = receipt.Id;
                
                rctIndex = receipt.Receipt_Index__c.intValue();
                if(receipt.Deduction_Amount__c != 0 || receipt.Deduction_Amount__c != 0.0){
                    deducVal = true;
                }
                else{
                    deducVal = false;
                }
                receiptMap.put(rctIndex, newRctId);
                if(newRctId != null){
                    for(Case_Payment__c eachCase : casePmts){
                        caseIndex = eachCase.CP_Index__c.intValue();
                        //Id recTyp = Schema.SObjectType.Case_Payment__c.getRecordTypeInfosByName().get('PAGA').getRecordTypeId();
                        if(rctIndex == caseIndex){
                            eachCase.Receipt__c = newRctId;
                            eachCase.Deduction_Payment__c = deducVal;
                            caseList.add(eachCase);
                        }
                    }
                }
            }
            System.debug('Case List  ==== '+caseList);
            insert caseList;
            
            Id newMapCaseId;
            Id rctIdOfCase;
            Integer total = 1;
            
            for(Case_Payment__c casePmt : caseList){
                newMapCaseId = casePmt.Id;
                rctIdOfCase = casePmt.Receipt__c;
                System.debug('S.No: '+total+' , Case_Payment ID: '+newMapCaseId+' , Receipt Id'+rctIdOfCase);
                total = total + 1;
                rctCaseMap.put(newMapCaseId,rctIdOfCase);
            }
        }
        return rctCaseMap;
    }
  
}