force-app/main/default/objects/Case_Payment__c/Case_Payment__c.object-meta.xml
<CustomObject>
    <description>Receipt applied to a Case. May have zero or more Liability Payments and zero or more Judgment Payments.</description>
    <label>Case Payment</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Payment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <inlineHelpText>Case that this Payment has been applied to</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Payments</relationshipLabel>
    <relationshipName>Case_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Payment__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+Receipt__r.Payee__r.Id,Receipt__r.Payee__r.Name)</formula>
    <label>Payee</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Allocations Recommended</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>ITEM insert</fullName>
                <isActive>false</isActive>
                <label>ITEM insert</label>
            </value>
            <value>
                <fullName>same</fullName>
                <isActive>false</isActive>
                <label>same</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Check__c/Check__c.object-meta.xml
<CustomObject>
    <description>Check object for capturing relevant check data</description>
    <label>Check</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Case Managment object</description>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Payee to whom the check is written</inlineHelpText>
    <label>Payee</label>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Secondary Approval Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Void Requested</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
            <value>
                <fullName>Uncleared</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>UWF Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Check__c/recordTypes/Check.recordType-meta.xml
<RecordType>
    <fullName>Check</fullName>
    <active>true</active>
    <description>Normal page layout for check record type</description>
    <label>Check</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Funds_Drawn_on_Deposits__c.field-meta.xml
<CustomField>
    <fullName>Funds_Drawn_on_Deposits__c</fullName>
    <description>Sum of all the Payment Records with Checks issued disbursed on this Case. Populated by apex: PaymentRecordTrigger, then PaymentRecordMethods</description>
    <inlineHelpText>Sum of all disbursements on this Case.</inlineHelpText>
    <label>Funds Drawn on Deposits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>BOFE Stay</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Citation or Other Issues</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Unable to Pursue</fullName>
            </value>
            <value>
                <fullName>Returned to Claimant</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Waiting for Litigation</fullName>
            </value>
            <value>
                <fullName>New AutoRefer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/Judgment_Payment__c.object-meta.xml
<CustomObject>
    <description>Records payments made against Judgments and their related interests, filing fees, and attorney fees.</description>
    <label>Judgment Payment</label>
    <nameField>
        <displayFormat>JP-{000000}</displayFormat>
        <label>Judgment Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgment Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment_Payment__c/fields/Case_Payment__c.field-meta.xml
<CustomField>
    <fullName>Case_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Payment</description>
    <label>Case Payment</label>
    <referenceTo>Case_Payment__c</referenceTo>
    <relationshipLabel>Judgment Payments</relationshipLabel>
    <relationshipName>Judgment_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability_Payment__c/Liability_Payment__c.object-meta.xml
<CustomObject>
    <description>DIR BOFE Payments against Liabilities.</description>
    <label>Liability Payment</label>
    <nameField>
        <displayFormat>LP-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Liability Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Payment__c/fields/Case_Payment__c.field-meta.xml
<CustomField>
    <fullName>Case_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Payment</label>
    <referenceTo>Case_Payment__c</referenceTo>
    <relationshipLabel>Liability Payments</relationshipLabel>
    <relationshipName>Liability_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <inlineHelpText>Amount actually posted from the Case Payment to this payment type.</inlineHelpText>
    <label>Payment Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <description>Used to capture data for Payee information related to a case and liability</description>
    <label>Payee</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payee__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <description>M/D to the Case Management object</description>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Payees</relationshipLabel>
    <relationshipName>Payees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/Payment_Record__c.object-meta.xml
<CustomObject>
    <label>Payment Record</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Payment Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Record__c/fields/Check__c.field-meta.xml
<CustomField>
    <fullName>Check__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check</label>
    <referenceTo>Check__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Check_Issued__c.field-meta.xml
<CustomField>
    <fullName>Check_Issued__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for rollup summary on payees then to case. Populated by flow that when a check is associated with the payment and when the status of the check changes.</description>
    <label>Check Issued</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Judgment_Payment__c.field-meta.xml
<CustomField>
    <fullName>Judgment_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Judgment Payment</label>
    <referenceTo>Judgment_Payment__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Liability_Payment__c.field-meta.xml
<CustomField>
    <fullName>Liability_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Liability Payment</label>
    <referenceTo>Liability_Payment__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <label>Payee</label>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PaymentRecordMethods.cls
/*********************************************************************

Author  :   DIR Salesforce Support Team 
Date    :   May 2018

Usage   :   This class is used to provide various methods on the Payment Record object.
                Triggered by PaymentRecordTrigger.cls

Comment :   As of this date, for other Apex code that messes with the Payment Records,
                see "requestChecks_Controller" and "CreateUWFCheckController" classes

*********************************************************************/
//TODO: Cashiering Rearchitecting Tier 2: Consider rolling up to CM.Funds_Drawn_on_Deposits__c through combined LP/JP object. Or not.
public class PaymentRecordMethods {
    
    public static void afterUpdateOrInsert(List<Payment_Record__c> triggerNew){
        /***********
        Sums up the Payment Amounts on the PRs on a Case where the PRs have had a check issued from them.
        Updates the DIR_Case__c.Funds_Drawn_on_Deposits__c field with this amount.
        ***********/
        
        //Set<Id> LPidSet = new Set<Id>();
        //Set<Id> JPidSet = new Set<Id>();
        Set<Id> payeeIdSet = new Set<Id>();
        //List<Liability_Payment__c> LPlist = new List<Liability_Payment__c>();
        //List<Judgment_Payment__c> JPlist = new List<Judgment_Payment__c>();
        List<Payee__c> payeeList = new List<Payee__c>();
        Set<Id> CMidSet = new Set<Id>();
        List<DIR_Case__c> CMlist = new List<DIR_Case__c>();
        List<Payment_Record__c> PRlist = new List<Payment_Record__c>();
        
        //System.debug('PRM.triggerNew: '+triggerNew);
        //query the greatgrandparent CMs for each PR in triggerNew
        for(Payment_Record__c PR : triggerNew) {
            System.debug('PRM.PR: '+PR);
            /*Rolling up funds from PRs through Payee records to CM.Funds_Drawn_on_Deposits__c, instead of through LPs/JPs, then CPs, to CM.Funds_Drawn_on_Deposits__c. Temporary fix for "parentless" PRs created for buybacks, until Cashiering Rearchitecting Tier 2*/
            if(PR.Payee__c != NULL){
                //System.debug('PRM.PR.Payee__r.Id: '+PR.Payee__r.Id);
                //System.debug('PRM.PR.Payee__c: '+PR.Payee__c);
                payeeIdSet.add(PR.Payee__c);
            }
            /* 
            if(PR.Liability_Payment__c != NULL){
                LPidSet.add(PR.Liability_Payment__c);
            }else if(PR.Judgment_Payment__c != NULL){
                JPidSet.add(PR.Judgment_Payment__c);
            }else{
                System.debug(System.LoggingLevel.ERROR, 'PaymentRecordMethods class: PR has no parent LP nor JP');
            }*/
        }
        //System.debug('PRM.payeeIdSet: '+payeeIdSet);
        
        /*LPlist = [SELECT Id, Case_Payment__c, Case_Payment__r.Case__c FROM Liability_Payment__c WHERE Id IN :LPidSet];
        JPlist = [SELECT Id, Case_Payment__c, Case_Payment__r.Case__c FROM Judgment_Payment__c WHERE Id IN :JPidSet];*/
        
        payeeList = [SELECT Id, Case_Management__c FROM Payee__c WHERE Id IN :payeeIdSet];
        //System.debug('PRM.payeeList: '+payeeList);
        /*
        for(Liability_Payment__c LP : LPlist){
            CMidSet.add(LP.Case_Payment__r.Case__c);
        }
        
        for(Judgment_Payment__c JP : JPlist){
            CMidSet.add(JP.Case_Payment__r.Case__c);
        }*/
        
        for(Payee__c payee : payeeList){
            CMidSet.add(payee.Case_Management__c);
        }
        
        CMlist = [SELECT Id, Funds_Drawn_on_Deposits__c FROM DIR_Case__c WHERE Id IN :CMidSet];
        
        //query ALL PRs under these CMs (triggerNew will not have all eligible PRs)
        PRlist = [SELECT Id, Check_Issued__c, Payment_Amount__c, Check__c, Check__r.Status__c,
                        Payee__c, Payee__r.Case_Management__c,
                        Liability_Payment__c, Liability_Payment__r.Case_Payment__r.Case__c,
                        Judgment_Payment__c, Judgment_Payment__r.Case_Payment__r.Case__c
                            FROM Payment_Record__c
                            WHERE Check__c != NULL
                                AND Payment_Amount__c != NULL
                                AND (
                                    Check__r.Status__c = 'Approved'
                                    OR Check__r.Status__c = 'Printed'
                                    OR Check__r.Status__c = 'UWF Allocation'
                                    //OR Check__r.Status__c = 'Uncleared' //'Cleared' and 'Uncleared' statuses never used per cashiering SMEs
                                    //OR Check__r.Status__c = 'Cleared'
                                    )
                                //AND ((Liability_Payment__c != NULL
                                //        AND Liability_Payment__r.Case_Payment__r.Case__c IN :CMidSet)
                                //    OR (Judgment_Payment__c != NULL
                                //        AND Judgment_Payment__r.Case_Payment__r.Case__c IN :CMidSet))
                                AND (Payee__c != NULL
                                    AND Payee__r.Case_Management__c IN :CMidSet)
                    ];
        
        //for each CM, sum it's PRs
        for(DIR_Case__c CM : CMlist){
            Decimal sumOfPRamounts = 0;
            
            for(Payment_Record__c PR : PRlist){
                if(PR.Payee__r.Case_Management__c == CM.Id){
                    sumOfPRamounts += PR.Payment_Amount__c;
                }
                /*
                if((PR.Liability_Payment__c != NULL && PR.Liability_Payment__r.Case_Payment__r.Case__c == CM.Id) ||
                    (PR.Judgment_Payment__c != NULL && PR.Judgment_Payment__r.Case_Payment__r.Case__c == CM.Id)){
                        sumOfPRamounts += PR.Payment_Amount__c;
                }*/
            }
            CM.Funds_Drawn_on_Deposits__c = sumOfPRamounts;
        }
        update CMlist;
    }
    
    public static void afterDelete(List<Payment_Record__c> triggerOld){
        /***********
        Sums up the Payment Amounts on the remaining PRs on a Case where the PRs have had a check issued from them.
        Updates the DIR_Case__c.Funds_Drawn_on_Deposits__c field with this amount.
        ***********/
        
        Set<Id> payeeIdSet = new Set<Id>();
        List<Payee__c> payeeList = new List<Payee__c>();
        Set<Id> CMidSet = new Set<Id>();
        List<DIR_Case__c> CMlist = new List<DIR_Case__c>();
        List<Payment_Record__c> PRlist = new List<Payment_Record__c>();
        
        //System.debug('PRM.triggerNew: '+triggerNew);
        //query the greatgrandparent CMs for each PR in triggerOld
        for(Payment_Record__c PR : triggerOld) {
            System.debug('PRM.PR: '+PR);
            /*Rolling up funds from PRs through Payee records to CM.Funds_Drawn_on_Deposits__c, instead of through LPs/JPs, then CPs, to CM.Funds_Drawn_on_Deposits__c. Temporary fix for "parentless" PRs created for buybacks, until Cashiering Rearchitecting Tier 2*/
            if(PR.Payee__c != NULL){
                //System.debug('PRM.PR.Payee__r.Id: '+PR.Payee__r.Id);
                //System.debug('PRM.PR.Payee__c: '+PR.Payee__c);
                payeeIdSet.add(PR.Payee__c);
            }
        }
        //System.debug('PRM.payeeIdSet: '+payeeIdSet);
        
        payeeList = [SELECT Id, Case_Management__c FROM Payee__c WHERE Id IN :payeeIdSet];
        //System.debug('PRM.payeeList: '+payeeList);
        
        for(Payee__c payee : payeeList){
            CMidSet.add(payee.Case_Management__c);
        }
        
        CMlist = [SELECT Id, Funds_Drawn_on_Deposits__c FROM DIR_Case__c WHERE Id IN :CMidSet];
        
        //query ALL PRs under these CMs (triggerOld will only have the PRs that have been deleted, not all the other remaining PRs on each case)
        PRlist = [SELECT Id, Check_Issued__c, Payment_Amount__c, Check__c, Check__r.Status__c,
                        Payee__c, Payee__r.Case_Management__c,
                        Liability_Payment__c, Liability_Payment__r.Case_Payment__r.Case__c,
                        Judgment_Payment__c, Judgment_Payment__r.Case_Payment__r.Case__c
                            FROM Payment_Record__c
                            WHERE Check__c != NULL
                                AND Payment_Amount__c != NULL
                                AND (
                                    Check__r.Status__c = 'Approved'
                                    OR Check__r.Status__c = 'Printed'
                                    OR Check__r.Status__c = 'UWF Allocation'
                                    //OR Check__r.Status__c = 'Uncleared' //'Cleared' and 'Uncleared' statuses never used per cashiering SMEs
                                    //OR Check__r.Status__c = 'Cleared'
                                )
                                AND (Payee__c != NULL
                                    AND Payee__r.Case_Management__c IN :CMidSet)
                    ];
        
        //for each CM, sum it's PRs
        for(DIR_Case__c CM : CMlist){
            Decimal sumOfPRamounts = 0;
            
            for(Payment_Record__c PR : PRlist){
                if(PR.Payee__r.Case_Management__c == CM.Id){
                    sumOfPRamounts += PR.Payment_Amount__c;
                }
            }
            CM.Funds_Drawn_on_Deposits__c = sumOfPRamounts;
        }
        update CMlist;
    }
}