force-app/main/default/objects/Assessments__c/Assessments__c.object-meta.xml
<CustomObject>
    <description>Penalty Assessment, Wage Assessments, Non-Citable Violations, Stop Orders, Notice To Discontinues are all stored in this object, which is tied to a Violation.</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AST-{000000}</displayFormat>
        <label>Assessments ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessments__c/fields/Appeal_Deadline_Days__c.field-meta.xml
<CustomField>
    <fullName>Appeal_Deadline_Days__c</fullName>
    <description>Set as max of appeal deadline from child case violation records via trigger on case violation object</description>
    <label>Appeal Deadline (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Appeal_Deadline_Selector__c.field-meta.xml
<CustomField>
    <fullName>Appeal_Deadline_Selector__c</fullName>
    <label>Appeal Deadline Selector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Days</fullName>
            </value>
            <value>
                <fullName>Calendar Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <description>The case is a parent of the assessment. This field specifies the case for which the assessment is a child.</description>
    <inlineHelpText>The case is a parent of the assessment. This field specifies the case for which the assessment is a child.</inlineHelpText>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <label>Violation Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Labor Relations</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Labor Code 3070 – 3098</fullName>
            </value>
            <value>
                <fullName>Child Labor</fullName>
            </value>
            <value>
                <fullName>Classified as Independent Contractor</fullName>
            </value>
            <value>
                <fullName>Improper or Incomplete Wage Statements</fullName>
            </value>
            <value>
                <fullName>Improper payment form incl. NSF check</fullName>
            </value>
            <value>
                <fullName>Industrial Homework</fullName>
            </value>
            <value>
                <fullName>Kickbacks</fullName>
            </value>
            <value>
                <fullName>Lactation Accommodation (LC 1030‐1033)</fullName>
            </value>
            <value>
                <fullName>Licensing, Registration or Permit</fullName>
            </value>
            <value>
                <fullName>Meal and Rest Breaks</fullName>
            </value>
            <value>
                <fullName>Minimum Wage</fullName>
            </value>
            <value>
                <fullName>Nonexempt Classified as Exempt</fullName>
            </value>
            <value>
                <fullName>Not paid for all hours worked</fullName>
            </value>
            <value>
                <fullName>Not Paid Wages Due on Termination</fullName>
            </value>
            <value>
                <fullName>Not providing required time off, other</fullName>
            </value>
            <value>
                <fullName>No Wage Statements</fullName>
            </value>
            <value>
                <fullName>No Workers’ Compensation</fullName>
            </value>
            <value>
                <fullName>Occupational SAFE HLTH (LC 6300 et seq)</fullName>
            </value>
            <value>
                <fullName>Other Notice or Posting or Recordkeeping</fullName>
            </value>
            <value>
                <fullName>Other Unpaid Wages</fullName>
            </value>
            <value>
                <fullName>Overtime</fullName>
            </value>
            <value>
                <fullName>Pay Discrim on basis of sex (LC1197.5)</fullName>
            </value>
            <value>
                <fullName>PMNT Reimbursement of Empl Expenses</fullName>
            </value>
            <value>
                <fullName>Public Works (Labor Code §§ 1720 – 1815)</fullName>
            </value>
            <value>
                <fullName>Retaliation - Protected Status Activity</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Tips or Gratuities</fullName>
            </value>
            <value>
                <fullName>Unfair Immigration Activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Defines if a role is currently active.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to the DIR Employee object creating a hierarchial relationship between an employee and his or her manager. Used in code to modify the role hierarchy and dynamically build teams</description>
    <inlineHelpText>Select the employee&#39;s manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Manages these Employees</relationshipLabel>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/DIR_Violation__c.object-meta.xml
<CustomObject>
    <description>This objects contains a Violation tied to a Case.</description>
    <label>Case Issue</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Case Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Violation__c/fields/Appeal_Deadline_Days__c.field-meta.xml
<CustomField>
    <fullName>Appeal_Deadline_Days__c</fullName>
    <description>Appeal deadline in days from the violation type</description>
    <formula>Violation_Type__r.Appeal_Deadline_Days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Appeal Deadline (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Violations are tied together as an assessment.</description>
    <label>Assessment</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipName>Case_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This creates a master detail relationship between a Violation and the Case that it is against.</description>
    <inlineHelpText>This creates a master detail relationship between a Violation and the Case that it is against.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Issues</relationshipLabel>
    <relationshipName>DIR_Violations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/DIR_Employee__c.field-meta.xml
<CustomField>
    <fullName>DIR_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issuing Deputy</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipName>DIR_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the type of violation from the list of available violations</description>
    <label>Case Issue Type</label>
    <referenceTo>Violation_Type__c</referenceTo>
    <relationshipLabel>Case Issues</relationshipLabel>
    <relationshipName>Case_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Violation_Type__c/Violation_Type__c.object-meta.xml
<CustomObject>
    <description>Holds the types of violations that are used on Case Management cases. Records here become &quot;Case Violation&quot; records when a violation is recorded by a deputy or inspector.</description>
    <label>Violation Type</label>
    <nameField>
        <label>Labor Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Violation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Violation_Type__c/fields/Appeal_Deadline_Days__c.field-meta.xml
<CustomField>
    <fullName>Appeal_Deadline_Days__c</fullName>
    <defaultValue>15</defaultValue>
    <description>Number of days from the issuance of the violatoin that the appeal is due</description>
    <inlineHelpText>Enter the number of days from the issue of the violation that an appeal is due.</inlineHelpText>
    <label>Appeal Deadline (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Violation_Type__c/fields/Appeal_Deadline_Selector__c.field-meta.xml
<CustomField>
    <fullName>Appeal_Deadline_Selector__c</fullName>
    <description>Used to define if the appeal deadline is in calendar days or business days</description>
    <inlineHelpText>Select Business Days or Calendar Days to define the appeal deadline</inlineHelpText>
    <label>Appeal Deadline Selector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Days</fullName>
            </value>
            <value>
                <fullName>Calendar Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Violation_Type__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <description>Defines the form on which this violation should appear. Used within the violations vfp to group violations into an assessment. All violations created at the same time on a case with the same Citation Form are grouped into a single assessment</description>
    <inlineHelpText>Select the citation form that this violation should appear on. Note that this is for grouping purposes and may not be an actual citation. For example, a NTD would be a citation form even though a penalty may not be levied.</inlineHelpText>
    <label>Citation Form</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BOFE 240A</fullName>
            </value>
            <value>
                <fullName>BOFE 240B</fullName>
            </value>
            <value>
                <fullName>BOFE 335</fullName>
            </value>
            <value>
                <fullName>BOFE 336</fullName>
            </value>
            <value>
                <fullName>BOFE 8</fullName>
            </value>
            <value>
                <fullName>BOFE 812</fullName>
            </value>
            <value>
                <fullName>BOFE 814</fullName>
            </value>
            <value>
                <fullName>BOFE 815</fullName>
            </value>
            <value>
                <fullName>BOFE 816</fullName>
            </value>
            <value>
                <fullName>JEU 238</fullName>
            </value>
            <value>
                <fullName>JEU 238e</fullName>
            </value>
            <value>
                <fullName>LR 240A</fullName>
            </value>
            <value>
                <fullName>Notice to Discontinue - DLSE 84</fullName>
            </value>
            <value>
                <fullName>PW 240A</fullName>
            </value>
            <value>
                <fullName>PW 336</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseViolationAllTest.cls
@isTest
public with sharing class CaseViolationAllTest {

    public static testMethod void TestSetAppealDeadline() {
        User ADMIN_USER = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1 ];
        
        DIR_Employee__c employee1 = new DIR_Employee__c(
            Active__c = true,
            User__c = ADMIN_USER.Id
        );
        insert employee1;
        
        DIR_Employee__c employee2 = new DIR_Employee__c(
            Active__c = true,
            User__c = ADMIN_USER.Id,
            Manager__c = employee1.Id
        );
        insert employee2;
        
        DIR_Case__c cm = new DIR_Case__c();
        cm.Assigned_Deputy__c = employee2.Id;
        insert cm;
        
        Assessments__c assess = new Assessments__c();
        assess.Case_Management__c = cm.Id;
        insert assess;
        
        Violation_Type__c vt = new Violation_Type__c();
        vt.RecordTypeId = Schema.SObjectType.Violation_Type__c.getRecordTypeInfosByName().get('BOFE Violations').getRecordTypeId();
        vt.Appeal_Deadline_Days__c = 12;
        vt.Active__c = true;
        vt.Appeal_Deadline_Selector__c = 'Business Days';
        insert vt;
        
        DIR_Violation__c viol = new DIR_Violation__c();
        viol.Violation_Type__c = vt.Id;
        viol.Case__c = cm.Id;
        viol.Assessment__c = assess.Id;
        insert viol;
        
        assess = [SELECT Appeal_Deadline_Days__c FROM Assessments__c WHERE Id = :assess.Id];
        System.AssertEquals(12, assess.Appeal_Deadline_Days__c);
        
    }

}