force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <description>Represents a receivable: an incoming payment, or an advice of incoming funds. [Encompasses the former Payment Log, Payment Group and Receipt objects to 1 single object.]</description>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RCT-{0000000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Bank_Location__c.field-meta.xml
<CustomField>
    <fullName>Bank_Location__c</fullName>
    <description>Picklist field allows users to designate whether the bank is out of state or in CA</description>
    <label>Bank Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA Bank</fullName>
            </value>
            <value>
                <fullName>Out of State Bank</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Deposit_Date__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Date__c</fullName>
    <formula>Transaction__r.Deposit_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deposit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Hold_Date__c.field-meta.xml
<CustomField>
    <fullName>Hold_Date__c</fullName>
    <description>Used to capture the Hold Date. Hold date populated from Trigger from Receipt</description>
    <label>Hold Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>Picklist field for designating the payment type</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>EFT</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Cashier&#39;s Check</fullName>
            </value>
            <value>
                <fullName>Money Order</fullName>
            </value>
            <value>
                <fullName>State Warrant</fullName>
            </value>
            <value>
                <fullName>State Warrant - Returned by USPS</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt_Log_Setting__mdt/Receipt_Log_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Receipt Log Setting</label>
    <pluralLabel>Receipt Log Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Receipt_Log_Setting__mdt/fields/Bank_Location__c.field-meta.xml
<CustomField>
    <fullName>Bank_Location__c</fullName>
    <label>Bank Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA Bank</fullName>
            </value>
            <value>
                <fullName>Out of state bank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt_Log_Setting__mdt/fields/Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days__c</fullName>
    <label>Number of Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt_Log_Setting__mdt/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>Payment Type picklist from Receipt Log</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Check</fullName>
                <default>true</default>
                <label>Check</label>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>EFT</fullName>
            </value>
            <value>
                <fullName>Cashier&#39;s Check</fullName>
            </value>
            <value>
                <fullName>Money Order</fullName>
            </value>
            <value>
                <fullName>State Warrant</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/receiptLogHoldDateAction.cls
/*************************************************************************************************
Class     :  receiptLogHoldDateAction.cls
Developer :  Sathya Chandrasekar
Created   :  June 2019
Modified  :  June 2019
Objective :  This class provides methods for receiptLog_Trigger.apxt
*************************************************************************************************/
public class receiptLogHoldDateAction extends TriggerAction {
   
    public boolean shouldRun;
    public Map<Id, Receipt_Log_Setting__mdt> logSettingMap = new Map<Id, Receipt_Log_Setting__mdt>();
    
    List<Receipt__c> receiptLogs = new List<Receipt__c>();
    public receiptLogHoldDateAction(Map<Id, sObject> triggerNewMap, Map<Id, sObject> triggerOldMap){ //is update
        super(triggerNewMap, triggerOldMap);
        
        for(sObject sObj : triggerNewMap.values()){
            Receipt__c rl = (Receipt__c)sObj;
            receiptLogs.add(rl);
            
        }
        
    }
    
    List<Receipt__c> updateReceiptLogs = new List<Receipt__c>();
    public receiptLogHoldDateAction(List<Receipt__c> triggerList){ //is insert
        super(triggerList);
        
        for (Receipt__c result: triggerList) {
            
            receiptLogs.add(result);
            
        }
        
    }
    
    public override boolean shouldRunOnInsert() { return true; }
     
    public override boolean shouldRunOnDelete() { return false; } 
    
    public override boolean shouldRunOnUpdate() { return true; }
        
    public override void doAction() {   

        calculateBusinessHours cbh = new calculateBusinessHours();
        
        List<Receipt_Log_Setting__mdt> rls = [SELECT Bank_Location__c,Id,Number_of_Days__c,Payment_Type__c FROM Receipt_Log_Setting__mdt];
        
        for(Receipt_Log_Setting__mdt r : rls){
            logSettingMap.put(r.id, r);
            
        }

        
        for(Receipt__c rl : receiptLogs){
            
            for(Id r : logSettingMap.keySet()){
                Receipt_Log_Setting__mdt rlData = logSettingMap.get(r);
                
                if(rlData.Payment_Type__c == rl.Payment_Type__c && (rlData.Bank_Location__c == rl.Bank_Location__c || rlData.Bank_Location__c == null)){
                    
                    Integer numDaysInt = Integer.valueOf(rlData.Number_of_Days__c);

                    if(rl.Deposit_Date__c != null)
                        rl.Hold_Date__c = cbh.addBusinessDays(rl.Deposit_Date__c, numDaysInt);
                    
                }
            }
        }
    }
    
    public static void runHandler() {  
        
        if (trigger.isAfter){
            return;
        }
        if (trigger.isUpdate) {
            system.debug('Trigger Update');
            receiptLogHoldDateAction action = new receiptLogHoldDateAction(trigger.newMap, trigger.oldMap);
            if(action.shouldRunOnUpdate()){
                action.doAction();
            }
        }

        if (trigger.isInsert){
            system.debug('Trigger Insert');
            receiptLogHoldDateAction action = new receiptLogHoldDateAction(trigger.new);
            if(action.shouldRunOnUpdate()){
                action.doAction();
            }
        }
    }
    
}