force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the License/Registration</description>
    <inlineHelpText>Expiration Date of the License/Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Type__c</fullName>
    <label>License/Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>Agricultural Employers of Minors</fullName>
            </value>
            <value>
                <fullName>Agricultural Produce Unloaders</fullName>
            </value>
            <value>
                <fullName>BOE/Seller’s Permit</fullName>
            </value>
            <value>
                <fullName>Bureau of Automotive Repair</fullName>
            </value>
            <value>
                <fullName>Business License</fullName>
            </value>
            <value>
                <fullName>Car Wash</fullName>
            </value>
            <value>
                <fullName>Child Performer Services</fullName>
            </value>
            <value>
                <fullName>CSLB</fullName>
            </value>
            <value>
                <fullName>DOL</fullName>
            </value>
            <value>
                <fullName>DSS Facility</fullName>
            </value>
            <value>
                <fullName>Electricians and electrician trainees</fullName>
            </value>
            <value>
                <fullName>FBNS</fullName>
            </value>
            <value>
                <fullName>FLC</fullName>
            </value>
            <value>
                <fullName>Garment Registration</fullName>
            </value>
            <value>
                <fullName>Health Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworker Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworkers</fullName>
            </value>
            <value>
                <fullName>Industrial Homework License</fullName>
            </value>
            <value>
                <fullName>Janitorial</fullName>
            </value>
            <value>
                <fullName>Secretary of State Number</fullName>
            </value>
            <value>
                <fullName>SEIN</fullName>
            </value>
            <value>
                <fullName>Sheltered Workshops (non‐profit)</fullName>
            </value>
            <value>
                <fullName>Special Minimum Wage</fullName>
            </value>
            <value>
                <fullName>Studio Teacher Certification</fullName>
            </value>
            <value>
                <fullName>Talent Agency</fullName>
            </value>
            <value>
                <fullName>Work Permits for Child Performers</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>BSIS</fullName>
            </value>
            <value>
                <fullName>Public Works</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <label>Middle Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Registration_Account__c.field-meta.xml
<CustomField>
    <fullName>Registration_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the registration account that became the account on this registration. Used for matching during renewal</description>
    <label>Registration Account</label>
    <referenceTo>Registration_Account__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations_Key_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Fee Calculation Ready</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending / Defect</fullName>
            </value>
            <value>
                <fullName>Referred for Investigation</fullName>
            </value>
            <value>
                <fullName>Referred to Legal</fullName>
            </value>
            <value>
                <fullName>In Violation</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed_Suspended</fullName>
                <label>Closed - Suspended</label>
            </value>
            <value>
                <fullName>Closed - Revoked</fullName>
            </value>
            <value>
                <fullName>Closed - Denied</fullName>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Closed - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Renewed</fullName>
                <label>Renewed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Pending Recertification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/recordTypes/Janitorial.recordType-meta.xml
<RecordType>
    <fullName>Janitorial</fullName>
    <active>true</active>
    <description>Registration for janitorial owners.</description>
    <label>Janitorial</label>
</RecordType>

force-app/main/default/objects/Registration_Account__c/Registration_Account__c.object-meta.xml
<CustomObject>
    <description>Staging object used to collect Company/Account information on Registration forms.</description>
    <label>Registration Account</label>
    <nameField>
        <displayFormat>RA-{000000000}</displayFormat>
        <label>Registration Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Account__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Registration Accounts</relationshipLabel>
    <relationshipName>Registration_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Stage_Name__c</fullName>
    <label>Professional Name (Stage Name)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RegistrationEWPResultsController.cls
/********************************************************************************************************
Name:  RegistrationResultsController.cls
Author:  Mirela Chituc (mirela.chituc@vertiba.com)
Date:  11/01/2017

VF Page: RegistrationSearchResults.page
Test class: RegistrationResultsControllerTest.cls

Behavior:
Filter Registration search by attributes so that it can narrow down to particular Registrations user is looking for. 

Changes
Touk Ken 06/27/2018 - add car wash and janitorial as parameters      
********************************************************************************************************/

global class RegistrationEWPResultsController {

    public String searchString {get; set;}
    public License_Registration__c dummyLicenseRegistration {get; set;}
    public RegistrationEWPSearchController.searchClass searchClassObj {get; set;}
    public String selectedRecordType {get; set;}

    // class constructor, executes first, as soon as the class is invoked
    global RegistrationEWPResultsController() {      

        searchClassObj = new RegistrationEWPSearchController.searchClass();
        searchClassObj.selectedRecordType = ApexPages.currentPage().getParameters().get('selectedRecordType');
        searchClassObj.registrationNumberStr = ApexPages.currentPage().getParameters().get('registrationNumberStr');
        searchClassObj.locationZipStr  = ApexPages.currentPage().getParameters().get('locationZipStr'); 
    }
    
    // Remote action called from RegistrationEWPResults.page via javascript function getAllRegistrations()
    @RemoteAction
    global static List<wrapRegistrationAccounts> getAllRegistrations(String registrationNumberStr, String selectedRecordType, String locationZipStr) {
        List<Registration_Account__c> allReg = new List<Registration_Account__c>();
        List<wrapRegistrationAccounts> wrapRALists = new List<wrapRegistrationAccounts>();
        
        if(String.isEmpty(registrationNumberStr) && String.isEmpty(selectedRecordType) && String.isEmpty(locationZipStr) ) {
            
        } else {
            Date todaydate = Date.Today();
            String query = 'SELECT'
                + ' Id'
                + ' ,  First_Name__c'
                + ' ,  Middle_Name__c'
                + ' ,  Last_Name__c'
                + ' ,  Stage_Name__c'
                + ' ,  RecordType.Name'
                + ' ,  Registration__r.License_Registration_Number__c'
                + ' ,  Registration__r.Effective_Date__c'
                + ' ,  Registration__r.Expiration_Date__c'
                + ' ,  Registration__r.Status__c'
                + ' FROM Registration_Account__c'
                + ' WHERE ( (Registration__r.Status__c = \'Approved\')'
                + '  OR ( Registration__r.Status__c = \'Closed - Renewed\')' 
                + '  OR ( Registration__r.Status__c = \'Renewed\' ) )'
                + ' AND Registration__r.License_Registration_Number__c like ' + '\'%' + registrationNumberStr + '\''
                + ' AND Residential_Zip_Code__c = ' + '\'' + locationZipStr + '\''
                + ' AND RecordType.Name = \'Individual Permit\''
                + ' AND Registration__r.Expiration_Date__c >=: todaydate ';

            //System.debug('*********selectedRecordType:' + selectedRecordType);
            if(!String.isEmpty(selectedRecordType)) {
                //System.debug('*********selectedRecordType:' + selectedRecordType);
                query += ' AND Registration__r.License_Registration_Type__c = \'' + selectedRecordType + '\' ';
            }
            
            query += ' ORDER BY Name DESC';
            System.debug('Query=======>'+query);
                allReg = Database.query(query);
        }

        String RegistrationNum = '';
        String Status = '';
        String MinorNm = '';
        String StageNm = '';
        Date EffectiveDate = NULL;
        Date ExpirationDate = NULL;

        for(Registration_Account__c eachRegistration: allReg){
            RegistrationNum = eachRegistration.Registration__r.License_Registration_Number__c;
            Status = eachRegistration.Registration__r.Status__c;
            EffectiveDate  = eachRegistration.Registration__r.Effective_Date__c;
            ExpirationDate = eachRegistration.Registration__r.Expiration_Date__c;

            if(eachRegistration.RecordType.Name == 'Individual Permit'){
                eachRegistration.First_Name__c = eachRegistration.First_Name__c == NULL ? '' : eachRegistration.First_Name__c;
                eachRegistration.Middle_Name__c = eachRegistration.Middle_Name__c == NULL ? '' : eachRegistration.Middle_Name__c;
                eachRegistration.Last_Name__c = eachRegistration.Last_Name__c == NULL ? '' : eachRegistration.Last_Name__c;
                StageNm = eachRegistration.Stage_Name__c == NULL ? '' : eachRegistration.Stage_Name__c;
                MinorNm = eachRegistration.First_Name__c + ' ' + eachRegistration.Middle_Name__c + ' ' + eachRegistration.Last_Name__c;
            }
            wrapRALists.add(new wrapRegistrationAccounts(RegistrationNum, Status, MinorNm, StageNm, EffectiveDate, ExpirationDate));
        }
        return wrapRALists;
    }
    
    // action called from "Return to Search" btn (RegistrationEWPResults.page)
    public PageReference BackToSearch() {
        PageReference searchPage = new PageReference('/apex/RegistrationEWPSearch');
        searchPage.setRedirect(true);
        return searchPage;
    }

    global class wrapRegistrationAccounts{
        public String RegistrationNum {get;set;}
        public String Status {get;set;}
        public String MinorName {get;set;}
        public String StageName {get;set;}
        public Date EffectiveDte {get;set;}
        public Date ExpirationDte {get;set;}
        
        public wrapRegistrationAccounts(String sRegistrationNum, String sStatus, String sMinorName, String sStageName, Date sEffectiveDte, Date sExpirationDte){
            RegistrationNum = sRegistrationNum;
            Status = sStatus;
            MinorName = sMinorName;
            StageName = sStageName;
            EffectiveDte = sEffectiveDte;
            ExpirationDte = sExpirationDte;
        }
    }
}