force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Account_Email__c.field-meta.xml
<CustomField>
    <fullName>Account_Email__c</fullName>
    <inlineHelpText>This is a required field if you are submitting online.</inlineHelpText>
    <label>Business Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Submitter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <description>Mapped to Entity_Type__c Account field.</description>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>LLC</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Sole Proprietorship</fullName>
            </value>
            <value>
                <fullName>LLP LP</fullName>
            </value>
            <value>
                <fullName>Public Entity</fullName>
            </value>
            <value>
                <fullName>Professional Corporation</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
            <value>
                <fullName>Joint Venture</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Advocate Organization</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>General Partnership</fullName>
            </value>
            <value>
                <fullName>Individual Permit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Corp_or_LLC_ID__c.field-meta.xml
<CustomField>
    <fullName>Corp_or_LLC_ID__c</fullName>
    <label>Corp or LLC ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Date_Formed__c.field-meta.xml
<CustomField>
    <fullName>Date_Formed__c</fullName>
    <inlineHelpText>Date format: mm/dd/yyyy or select the downward arrow to select a date from a calendar view.</inlineHelpText>
    <label>Date Formed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Daytime_Phone__c.field-meta.xml
<CustomField>
    <fullName>Daytime_Phone__c</fullName>
    <inlineHelpText>Phone number must be 10 numbers (no dashes or spaces.)</inlineHelpText>
    <label>Daytime Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Daytime_Phone_Ext__c.field-meta.xml
<CustomField>
    <fullName>Daytime_Phone_Ext__c</fullName>
    <inlineHelpText>If there is an extension #, please enter that here.</inlineHelpText>
    <label>Daytime Phone Ext.</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Federal_Employer_Identification_Number__c.field-meta.xml
<CustomField>
    <fullName>Federal_Employer_Identification_Number__c</fullName>
    <inlineHelpText>Please enter your 9-digit FEIN using only numbers.</inlineHelpText>
    <label>Federal Employer Identification Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Good_standing_with_CA_Secretary_of_State__c.field-meta.xml
<CustomField>
    <fullName>Good_standing_with_CA_Secretary_of_State__c</fullName>
    <label>Good standing with CA Secretary of State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <inlineHelpText>Please enter the same business name as is registered with the CA Secretary of State. For sole proprietorship the Contractor Legal Name must match the full name on driver’s license.</inlineHelpText>
    <label>Legal Entity Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address_Line_1__c</fullName>
    <label>Mailing Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address_Line_2__c</fullName>
    <label>Mailing Address Line 2</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City / Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country__c</fullName>
    <label>Mailing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Global_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Postal_Code__c</fullName>
    <inlineHelpText>U.S. Zip codes must have 5 digits or 9 digits with a dash between the 5th and 6th digit.</inlineHelpText>
    <label>Mailing Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <label>Mailing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Physical_Business_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_Address_Line_1__c</fullName>
    <inlineHelpText>Please enter your physical business address.  P.O. Box address is not allowed.</inlineHelpText>
    <label>Physical Business Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Registration_Account__c.field-meta.xml
<CustomField>
    <fullName>Registration_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the registration account that became the account on this registration. Used for matching during renewal</description>
    <label>Registration Account</label>
    <referenceTo>Registration_Account__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations_Key_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Sole_prop_for_myself__c.field-meta.xml
<CustomField>
    <fullName>Sole_prop_for_myself__c</fullName>
    <description>indicates that the applicant is creating the sole proprietorship for themselves or on behalf of another</description>
    <inlineHelpText>Please indicate if you are creating this sole proprietorship for yourself. If so, select yes, if you are are creating it on behalf of someone else, select no.</inlineHelpText>
    <label>I am creating this sole prop for myself</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/recordTypes/Entertainment_Work.recordType-meta.xml
<RecordType>
    <fullName>Entertainment_Work</fullName>
    <active>true</active>
    <description>Registration for Entertainment Work Permit</description>
    <label>Entertainment Work</label>
</RecordType>

force-app/main/default/objects/Registration_Account__c/Registration_Account__c.object-meta.xml
<CustomObject>
    <description>Staging object used to collect Company/Account information on Registration forms.</description>
    <label>Registration Account</label>
    <nameField>
        <displayFormat>RA-{000000000}</displayFormat>
        <label>Registration Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registration Accounts</relationshipLabel>
    <relationshipName>Registration_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Business_Phone__c.field-meta.xml
<CustomField>
    <fullName>Business_Phone__c</fullName>
    <description>Map to Phone on Account</description>
    <inlineHelpText>Phone number must be 10 numbers (no dashes or spaces.)</inlineHelpText>
    <label>Daytime Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Corp_or_LLC_ID__c.field-meta.xml
<CustomField>
    <fullName>Corp_or_LLC_ID__c</fullName>
    <description>Mapped to Corp_or_LLC_ID__c Account field.</description>
    <label>Corp or LLC ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Date_Formed__c.field-meta.xml
<CustomField>
    <fullName>Date_Formed__c</fullName>
    <description>Mapped to Date_Formed__c Account field.</description>
    <inlineHelpText>Date format: mm/dd/yyyy or select the downward arrow to select a date from a calendar view.</inlineHelpText>
    <label>Date Formed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>Map to Email__c on Account</description>
    <inlineHelpText>DLSE uses this to communicate with Applicant.</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Good_standing_with_CA_Secretary_of_State__c.field-meta.xml
<CustomField>
    <fullName>Good_standing_with_CA_Secretary_of_State__c</fullName>
    <description>Mapped to Good_standing_with_CA_Secretary_of_State__c Account field.</description>
    <label>Good standing with CA Secretary of State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <description>Mapped to Legal_Entity_Name__c Account field.</description>
    <inlineHelpText>Employer</inlineHelpText>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <description>Map to standard ShippingAddress field on Account</description>
    <label>Mailing City / Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <description>Map to standard ShippingAddress field on Account</description>
    <label>Mailing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Mailing_Street__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Street__c</fullName>
    <description>Map to standard ShippingAddress field on Account</description>
    <label>Mailing Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Mailing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip_Code__c</fullName>
    <description>Map to standard ShippingAddress field on Account</description>
    <inlineHelpText>U.S. Zip codes must have 5 digits or 9 digits with a dash between the 5th and 6th digit.</inlineHelpText>
    <label>Mailing Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone__c</fullName>
    <inlineHelpText>Phone number must be 10 numbers (no dashes or spaces.)</inlineHelpText>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Physical_Business_Street__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_Street__c</fullName>
    <description>Map to Primary_Street_Placeholder__c	 on Account</description>
    <label>Physical Business Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Registration Accounts</relationshipLabel>
    <relationshipName>Registration_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Global_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei Darussalam</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi</fullName>
    </customValue>
    <customValue>
        <fullName>Cabo Verde</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <masterLabel>Global Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/State_Abbreviations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <default>true</default>
        <label>CA</label>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <masterLabel>State Abbreviations</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LRHandlerHelper.cls
/******************************************************************************
* @author         Sapient
* @date           December 2018
* @description    
********************************************************************************************************/
@SuppressWarnings('sf:ClassWithOnlyPrivateConstructorsShouldBeFinal')
public without sharing class LRHandlerHelper {
    private static LRHandlerHelper classInstance = null;
    private LRHandlerHelper() {
        
    }
    
    public static LRHandlerHelper getInstance(){
        if (null == classInstance) {
            classInstance = new LRHandlerHelper();
        }
        return classInstance;
    }
    
    public Registration_Account__c initiateRegAccount(License_Registration__c lr, Registration_Account__c regAccount) {
        //       if ( lr.Company_type__c == 'Sole Proprietorship' && lr.Sole_prop_for_myself__c == 'Yes')
        if ( lr.Company_type__c == 'Sole Proprietorship')
            regAccount.Account__c = lr.Applicant__r.AccountId;
        //regAccount.Registration__c = lr.Id;
        regAccount.Email_Address__c = lr.Account_Email__c;
        regAccount.Corp_or_LLC_ID__c = lr.Corp_or_LLC_ID__c;
        regAccount.Date_Formed__c = lr.Date_Formed__c;          
        regAccount.Business_Phone__c = lr.Daytime_Phone__c;                
        regAccount.Daytime_Phone_Ext__c = lr.Daytime_Phone_Ext__c;                
        regAccount.Federal_Employer_Identification_Number__c = lr.Federal_Employer_Identification_Number__c;               
        regAccount.Good_standing_with_CA_Secretary_of_State__c = lr.Good_standing_with_CA_Secretary_of_State__c;               
        regAccount.Legal_Entity_Name__c = lr.Legal_Entity_Name__c;             
        regAccount.Mailing_Street__c = lr.Mailing_Address_Line_1__c;                
        regAccount.Mailing_Address_Line_2__c = lr.Mailing_Address_Line_2__c;               
        regAccount.Mailing_City__c = lr.Mailing_City__c;                
        regAccount.Mailing_Country__c = lr.Mailing_Country__c;               
        regAccount.Mailing_Zip_Code__c = lr.Mailing_Postal_Code__c;                
        regAccount.Mailing_State__c = lr.Mailing_State__c;                
        regAccount.Mobile_Phone__c = lr.Mobile_Phone__c;                
        regAccount.Physical_Business_Street__c = lr.Physical_Business_Address_Line_1__c;                
        regAccount.Physical_Business_Line_2__c = lr.Physical_Business_Address_Line_2__c;                
        regAccount.Physical_Business_City__c = lr.Physical_Business_City__c;               
        regAccount.Physical_Business_Country__c = lr.Physical_Business_Country__c;                
        regAccount.Physical_Business_Zip_Code__c = lr.Physical_Business_Postal_Code__c;                
        regAccount.Physical_Business_State__c = lr.Physical_Business_State__c;                
        regAccount.State_Employer_Identification_Number_c__c = lr.State_Employer_Identification_Number__c;                
        regAccount.State_of_Incorporation__c = lr.State_of_Incorporation__c;
        Logger.debug('######## LRHandlerHelper regAccount:' + regAccount);
        return regAccount;
        
    }
    
    public Boolean isDuplicateRegAccount( License_Registration__c newLic, ID rTypeID){
        Logger.push('isDuplicateRegAccount','LicenseRegistrationAllHandler');
        List<Registration_Account__c> currentRegs = [ SELECT RecordTypeId
                                                     , Registration__c
                                                     , Email_Address__c
                                                     , Corp_or_LLC_ID__c
                                                     , Date_Formed__c        
                                                     , Business_Phone__c          
                                                     , Daytime_Phone_Ext__c              
                                                     , Federal_Employer_Identification_Number__c          
                                                     , Good_standing_with_CA_Secretary_of_State__c             
                                                     , Legal_Entity_Name__c        
                                                     , Mailing_Street__c           
                                                     , Mailing_Address_Line_2__c          
                                                     , Mailing_City__c             
                                                     , Mailing_Country__c           
                                                     , Mailing_Zip_Code__c              
                                                     , Mailing_State__c             
                                                     , Mobile_Phone__c            
                                                     , Physical_Business_Street__c              
                                                     , Physical_Business_Line_2__c               
                                                     , Physical_Business_City__c             
                                                     , Physical_Business_Country__c              
                                                     , Physical_Business_Zip_Code__c               
                                                     , Physical_Business_State__c             
                                                     , State_Employer_Identification_Number_c__c              
                                                     , State_of_Incorporation__c 
                                                     from Registration_Account__c 
                                                     where Registration__c =: newLic.Id];
        
        for(Registration_Account__c eachReg: currentRegs)
        {
            if( eachReg.RecordTypeId == rTypeID &&
               eachReg.Registration__c == newLic.Id && 
               eachReg.Email_Address__c == newLic.Account_Email__c && 
               //eachReg.Corp_or_LLC_ID__c == newLic.Corp_or_LLC_ID__c && 
               eachReg.Date_Formed__c == newLic.Date_Formed__c &&           
               eachReg.Business_Phone__c == newLic.Daytime_Phone__c &&                 
               //eachReg.Daytime_Phone_Ext__c == newLic.Daytime_Phone_Ext__c &&                 
               eachReg.Federal_Employer_Identification_Number__c == newLic.Federal_Employer_Identification_Number__c &&                
               //eachReg.Good_standing_with_CA_Secretary_of_State__c == newLic.Good_standing_with_CA_Secretary_of_State__c &&                
               eachReg.Legal_Entity_Name__c == newLic.Legal_Entity_Name__c &&              
               eachReg.Mailing_Street__c == newLic.Mailing_Address_Line_1__c &&                 
               //eachReg.Mailing_Address_Line_2__c == newLic.Mailing_Address_Line_2__c &&                
               eachReg.Mailing_City__c == newLic.Mailing_City__c &&                 
               //eachReg.Mailing_Country__c == newLic.Mailing_Country__c &&                
               eachReg.Mailing_Zip_Code__c == newLic.Mailing_Postal_Code__c &&                 
               eachReg.Mailing_State__c == newLic.Mailing_State__c &&                 
               //eachReg.Mobile_Phone__c == newLic.Mobile_Phone__c &&                 
               eachReg.Physical_Business_Street__c == newLic.Physical_Business_Address_Line_1__c &&                 
               //eachReg.Physical_Business_Line_2__c == newLic.Physical_Business_Address_Line_2__c &&                 
               eachReg.Physical_Business_City__c == newLic.Physical_Business_City__c &&                
               //eachReg.Physical_Business_Country__c == newLic.Physical_Business_Country__c &&                 
               eachReg.Physical_Business_Zip_Code__c == newLic.Physical_Business_Postal_Code__c &&                 
               eachReg.Physical_Business_State__c == newLic.Physical_Business_State__c &&                 
               eachReg.State_Employer_Identification_Number_c__c == newLic.State_Employer_Identification_Number__c &&                 
               eachReg.State_of_Incorporation__c == newLic.State_of_Incorporation__c){
                   return false;
               }
        }
        return true;
    }
    
    public void isExistingPermitHolder(List<License_Registration__c> newList, Map<Id, License_Registration__c> oldMap){
        //Logger.push('checkExistingPermitHolder','RegistrationAccountAllHandler');
        //Logger.debug('Entering isExistingTempPermitHolder' + newList);
        //System.debug('#############Entering isExistingPermitHolder RegistrationAccountAllHandler' + newList);
        
        
        if(!newList.isEmpty()){
            if(newList[0].Record_Type_Name__c == 'Entertainment_Work'){
                
                Id recTypeIdEWP = Schema.SObjectType.License_Registration__c.getRecordTypeInfosByName().get('Entertainment Work').getRecordTypeId();
                Id recTypeIdIndvPermit = Schema.SObjectType.Registration_Account__c.getRecordTypeInfosByName().get('Individual Permit').getRecordTypeId();
                
                // check if the current ra matches any existing temp ra
                if(newList[0].Record_Type_Name__c == 'Entertainment_Work' && newList[0].Registration_Duration__c == '10 Days - Temporary Permit'){
                    //List<Registration_Account__c> ra = new List<Registration_Account__c>();
                    //for(License_Registration__c lr :newList){
                    List<Registration_Account__c> ra = [SELECT Id
                                                        , First_Name__c
                                                        , Last_Name__c
                                                        , Birth_Date__c
                                                        , Registration__r.Id
                                                        , Registration__r.Registration_Duration__c
                                                        , RecordTypeId
                                                        , Registration__r.RecordTypeId 
                                                        FROM Registration_Account__c 
                                                        WHERE Registration__r.Id =: newList[0].Id
                                                        AND RecordTypeId =: recTypeIdIndvPermit
                                                        AND Registration__r.RecordTypeId =: recTypeIdEWP];
                    
                    List<Registration_Account__c> existingRA = [ SELECT Id
                                                                , RecordTypeId
                                                                , Registration__r.RecordTypeId
                                                                , Registration__r.Service_Type__c
                                                                , Registration__r.License_Registration_Number__c
                                                                , Registration__r.Registration_Duration__c
                                                                , Registration__r.Status__c
                                                                , Registration__r.Approved__c
                                                                , First_Name__c
                                                                , Last_Name__c
                                                                , Birth_Date__c
                                                                
                                                                FROM Registration_Account__c
                                                                //WHERE Registration__r.Service_Type__c = 'Temporary'
                                                                WHERE Registration__r.Registration_Duration__c = '10 Days - Temporary Permit'
                                                                AND Registration__r.Id !=: newList[0].Id
                                                                AND RecordTypeId =: recTypeIdIndvPermit
                                                                AND Registration__r.RecordTypeId =: recTypeIdEWP
                                                                AND Registration__r.Status__c = 'Approved'
                                                                AND Registration__r.Approved__c= TRUE
                                                               ];  
                    
                    for(Registration_Account__c eachRA: ra)
                    {
                        for(Registration_Account__c eachExistingTempRA: existingRA)
                        {
                            
                            if(eachExistingTempRA.First_Name__c == eachRA.First_Name__c 
                               && eachExistingTempRA.Last_Name__c == eachRA.Last_Name__c
                               && eachExistingTempRA.Birth_Date__c == eachRA.Birth_Date__c)
                            {        
                                newList[0].Registration_Duration__c.addError('The applicant cannot be added because another temporary permit has already been granted to this minor.');
                                //return true ;
                            }
                        }
                    }        
                }
            }
        }
    }
    
    public void CheckValidRegistrationAge(List<License_Registration__c> newList, Map<Id, License_Registration__c> oldMap){
        //Logger.push('checkExistingPermitHolder','RegistrationAccountAllHandler');
        //Logger.debug('Entering isExistingTempPermitHolder' + newList);
        //System.debug('#############Entering isExistingTempPermitHolder RegistrationAccountAllHandler' + newList);
        
        if(newList.isEmpty() 
           || newList[0].Record_Type_Name__c != 'Entertainment_Work' 
           || newList[0].Registration_Duration__c != '10 Days - Temporary Permit') 
        { return; }
        
        Id recTypeIdEWP = Schema.SObjectType.License_Registration__c.getRecordTypeInfosByName().get('Entertainment Work').getRecordTypeId();
        Id recTypeIdIndvPermit = Schema.SObjectType.Registration_Account__c.getRecordTypeInfosByName().get('Individual Permit').getRecordTypeId();
        
        // check if the current ra matches any existing temp ra
        
        
        List<Registration_Account__c> ra = new List<Registration_Account__c>();
        //for(License_Registration__c lr :newList){
        ra = [SELECT Id
              , First_Name__c
              , Last_Name__c
              , Birth_Date__c
              , Registration__r.Id
              , Registration__r.Registration_Duration__c
              , RecordTypeId
              , Registration__r.RecordTypeId 
              FROM Registration_Account__c 
              WHERE Registration__r.Id =: newList[0].Id
              AND RecordTypeId =: recTypeIdIndvPermit
              AND Registration__r.RecordTypeId =: recTypeIdEWP];
        
        if(ra.isEmpty()) { return; }
        
        if(ra[0].Birth_Date__c != NULL){
            if(validateAgeForTempEWP(ra[0].Birth_Date__c))
            {        
                newList[0].Registration_Duration__c.addError('Minor must be between the ages of 15 days to 15 years to receive a temporary work permit.  Minors aged 16 and 17 years old must apply for the 6-months permit' + 
                                                             'Change your answer to --None-- and return to the Minor Information section to correct the minors age.');
            }
        }
    }
    
    public Boolean validateAgeForTempEWP(Date dBday)
    {
        // 'Minor must be between the ages of 15 days to 16 years to receive a temporary work permit.'
        if(Date.Today() < dBday.addDays(15) || Date.Today() >= dBday.addYears(16)){
            return true;
        }
        return false; 
    }
    
}