force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Account_Email__c.field-meta.xml
<CustomField>
    <fullName>Account_Email__c</fullName>
    <inlineHelpText>This is a required field if you are submitting online.</inlineHelpText>
    <label>Business Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <description>Populated via DLRS from Fee Summary</description>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Amount_Paid_Manually__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid_Manually__c</fullName>
    <description>Total amount paid by physical check/money order. Populated via DLRS rollup.</description>
    <label>Amount Paid Manually</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Amount_Paid_Online__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid_Online__c</fullName>
    <description>Total Amount paid via Chargent. Populated via DLRS rollup.</description>
    <label>Amount Paid Online</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Submitter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Ready_to_Submit__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Submit__c</fullName>
    <label>Ready to Complete Payment?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RevokeChargentLicenseBatchTest.cls
@istest
public class RevokeChargentLicenseBatchTest {

    
    static testMethod void testRevokeChargentLicenseBatch() {
        //BEGIN: some setup items
        Profile commProfile = [SELECT Id FROM Profile WHERE Name = 'Community Registrations User' LIMIT 1];
        
        Id personAccountRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
       
        account a = new Account(
          RecordTypeID=personAccountRTId,
          FirstName='Test FName',
          LastName='Test LName',
          PersonMailingStreet='test@yahoo.com',
          PersonMailingPostalCode='12345',
          PersonMailingCity='SFO',
          PersonEmail='test@yahoo.com',
          PersonHomePhone='1234567',
          PersonMobilePhone='12345678' 
        );
        insert a;
               
        //system.debug('##### A: ' + a);
        Account acc = [Select PersonContactId From Account Where Id = :a.Id];
        
        User u = new User(contactId = acc.PersonContactId, Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = commProfile.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        system.debug('##### u: ' + u);
        insert u;
        
        
        List<User> newUsers = [SELECT Id FROM User WHERE Id=: u.Id AND ProfileId =: commProfile.Id AND isActive = true LIMIT 1];
        //END: some setup items
        //validate the initial contact information
        newUsers[0].Street = 'aaaaa\nbbbbb';
        
        License_Registration__c lr = new License_Registration__c();
        lr.Account__c = a.id;
        lr.Applicant__c = acc.PersonContactId;
        lr.RecordtypeId = Schema.SObjectType.License_Registration__c.getRecordTypeInfosByName().get('Car Wash').getRecordTypeId();
        lr.Account_Email__c = 'standarduser@testorg.com';
        lr.Amount_Due__c = 100;
        lr.Amount_Paid_Manually__c = 0;
        lr.Amount_Paid_Online__c  = 0;
        
        
        insert lr;
        
        lr.Ready_to_Submit__c = 'Yes';
        update lr;
        
        Test.startTest();
        System.runAs ( new User(Id = newUsers[0].Id) ) { //runAs in order to avoid MIXED_DML_OPERATION error
        
            // CommunitiesLandingController controller = new CommunitiesLandingController();
           //  PageReference pageRef = controller.forwardToStartPage();
            CommunityLoginController controller = new CommunityLoginController();
           controller.username = 'test@tesrtest.com';
           controller.login();
           controller.SignIn();
           controller.forwardToCustomAuthPage();   
        
            RevokeChargentLicenseBatch obj = new RevokeChargentLicenseBatch();
            obj.selectedTime = system.now();
            DataBase.executeBatch(obj,2000);

            RevokeChargentLicenseScheduler obj2 = new RevokeChargentLicenseScheduler();
            String sch = '0 0 2 * * ?';
            system.schedule('Test purgeChargentOrderScheduler', sch, obj2);   
        }
        Test.stopTest();
        //validate that it worked as intended
        
    }
    // static testMethod void testRevokeChargentLicenseBatch1() {
    //     //BEGIN: some setup items
    //     Profile commProfile = [SELECT Id FROM Profile WHERE Name = 'Community Registrations User' LIMIT 1];
        
    //     Id personAccountRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
       
    //     account a = new Account(
    //       RecordTypeID=personAccountRTId,
    //       FirstName='Test FName',
    //       LastName='Test LName',
    //       PersonMailingStreet='test@yahoo.com',
    //       PersonMailingPostalCode='12345',
    //       PersonMailingCity='SFO',
    //       PersonEmail='test@yahoo.com',
    //       PersonHomePhone='1234567',
    //       PersonMobilePhone='12345678' 
    //     );
    //     insert a;
               
    //     //system.debug('##### A: ' + a);
    //     Account acc = [Select PersonContactId From Account Where Id = :a.Id];
        
    //     User u = new User(contactId = acc.PersonContactId, Alias = 'standt', Email='standarduser@testorg.com', 
    //         EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    //         LocaleSidKey='en_US', ProfileId = commProfile.Id, 
    //         TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
    //     system.debug('##### u: ' + u);
    //     insert u;
        
        
    //     List<User> newUsers = [SELECT Id FROM User WHERE Id=: u.Id AND ProfileId =: commProfile.Id AND isActive = true LIMIT 1];
    //     //END: some setup items
    //     //validate the initial contact information
    //     newUsers[0].Street = 'aaaaa\nbbbbb';
        
    //     License_Registration__c lr = new License_Registration__c();
    //     lr.Account__c = a.id;
    //     lr.Applicant__c = acc.PersonContactId;
    //     lr.RecordtypeId = Schema.SObjectType.License_Registration__c.getRecordTypeInfosByName().get('Car Wash').getRecordTypeId();
    //     lr.Account_Email__c = 'standarduser@testorg.com';
    //     lr.Amount_Due__c = 100;
    //     lr.Amount_Paid_Manually__c = 0;
    //     lr.Amount_Paid_Online__c  = 0;
        
        
    //     insert lr;
        
    //     lr.Ready_to_Submit__c = 'Yes';
    //     update lr;
        
    //     Test.startTest();
    //     System.runAs ( new User(Id = newUsers[0].Id) ) { //runAs in order to avoid MIXED_DML_OPERATION error
        
          
    //       CommunityLoginController controller = new CommunityLoginController();
    //       controller.username = 'test@tesrtest.com';
    //       controller.login();
    //       controller.SignIn();
    //       controller.forwardToCustomAuthPage();   
        
    //         RevokeChargentLicenseScheduler obj = new RevokeChargentLicenseScheduler();
    //         String sch = '0 0 2 * * ?';
    //         system.schedule('Test purgeChargentOrderScheduler', sch, obj);        
    //     }
    //     Test.stopTest();
    //     //validate that it worked as intended
        
    // }
}