force-app/main/default/objects/Purge_Settings__mdt/Purge_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Purge Setting</label>
    <pluralLabel>Purge Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Purge_Settings__mdt/fields/Age_of_Records_to_Purge__c.field-meta.xml
<CustomField>
    <fullName>Age_of_Records_to_Purge__c</fullName>
    <inlineHelpText>Enter number of days it must age with no activity. Activity is evaluating against Last Modified Date of Record.</inlineHelpText>
    <label>Age of Records to Purge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purge_Settings__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Purge_Settings</relationshipLabel>
    <relationshipName>Purge_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Purge_Settings__mdt/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <inlineHelpText>Add a Comma &quot;,&quot; to separate the API name of the Record type.</inlineHelpText>
    <label>Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purge_Settings__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Add a Comma &quot;,&quot; to separate multuple Status to be evaluated</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PurgeIterable.cls
public with sharing class PurgeIterable implements Iterable<SObject> {
    public Iterator<SObject> iterator() {
        List<SObject> sobjects = new List<SObject>();
        Map<String, List<String>> recordTypesByObject = new Map<String, List<String>>();
        Map<String, List<String>> statusesByObject = new Map<String, List<String>>();
        Map<String, Decimal> daysByObject = new Map<String, Decimal>();

        for (Purge_Settings__mdt setting : [
                SELECT Object__r.QualifiedApiName,
                        Record_Type__c,
                        Status__c,
                        Age_of_Records_to_Purge__c
                FROM Purge_Settings__mdt
        ]) {
            String objectApiName = setting.Object__r.QualifiedApiName;
            recordTypesByObject.put(objectApiName, setting.Record_Type__c.replaceAll( '\\s+', '').split(','));
            statusesByObject.put(objectApiName, setting.Status__c.split(','));
            daysByObject.put(objectApiName, Integer.valueOf(Math.round(setting.Age_of_Records_to_Purge__c)));
            List<SObject> records;
            List<String> recordTypes = recordTypesByObject.get(objectApiName);
            List<String> statuses = statusesByObject.get(objectApiName);
            String query;

            query = 'SELECT Id FROM ' + objectApiName + ' ';
            query += 'WHERE RecordType.DeveloperName IN :recordTypes' + ' ';
            query += 'AND Status__c IN :statuses' + ' ';
            query += 'AND LastModifiedDate < LAST_N_DAYS:' + daysByObject.get(objectApiName);

            records = Database.query(query);
            sobjects.addAll(records);
        }

        return sobjects.iterator();
    }
}