force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Role__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This field maintains the relationship between the Case Role and the Case.  Reparentable.</description>
    <inlineHelpText>This field maintains the relationship between the Case Role and the Case.  Reparentable.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Role</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Case_Role_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Role_Status__c</fullName>
    <description>For requirement 33146; allows users to quickly view the status of related case roles to a given case record.</description>
    <label>Case Role Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>ODA - Defendant</fullName>
            </value>
            <value>
                <fullName>ODA - Plaintiff</fullName>
            </value>
            <value>
                <fullName>ODA by Settlement</fullName>
            </value>
            <value>
                <fullName>Dismissal - Claimant</fullName>
            </value>
            <value>
                <fullName>Dismissal - Deputy</fullName>
            </value>
            <value>
                <fullName>Dismissal - Ineffective service</fullName>
            </value>
            <value>
                <fullName>No Longer Active On Case</fullName>
            </value>
            <value>
                <fullName>De Novo Appeal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Role__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>BOFE Stay</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Citation or Other Issues</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Unable to Pursue</fullName>
            </value>
            <value>
                <fullName>Returned to Claimant</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Waiting for Litigation</fullName>
            </value>
            <value>
                <fullName>New AutoRefer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <description>Vertiba</description>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/Hearing__c/Hearing__c.object-meta.xml
<CustomObject>
    <description>This stores all of the hearings/conferences related to an Appeal, which gets information from the Assessment, Liability Appeal, Case, and Account from a relationship level.</description>
    <label>Meeting</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Meeting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hearing__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Lookup to parent case. Used for easy identification and for rules related to referrals that deal with hearing dates.</description>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Hearings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hearing__c/fields/Meeting_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Start_Date_Time__c</fullName>
    <label>Meeting Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Hearing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Appeal Withdrawn</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Continuance Rejected</fullName>
            </value>
            <value>
                <fullName>Continuance Requested</fullName>
            </value>
            <value>
                <fullName>Continued</fullName>
            </value>
            <value>
                <fullName>Deny License Renewal</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Dismissed-Def FTA</fullName>
            </value>
            <value>
                <fullName>Dismissed–Div FTA</fullName>
            </value>
            <value>
                <fullName>Failure to Appear</fullName>
            </value>
            <value>
                <fullName>Meeting Approved</fullName>
            </value>
            <value>
                <fullName>Meeting Rejected</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Off Calendar</fullName>
            </value>
            <value>
                <fullName>Paid Pre-Hearing</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Referred to Hearing - Claimant only appeared</fullName>
            </value>
            <value>
                <fullName>Referred to Hearing - No Settlement</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Revoke License</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Settled Pre-Hearing</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/Meeting_Participant__c.object-meta.xml
<CustomObject>
    <label>Meeting Participant</label>
    <nameField>
        <displayFormat>MP-{0}</displayFormat>
        <label>Meeting Participant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Participant__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
                <default>true</default>
                <label>Invited</label>
            </value>
            <value>
                <fullName>Appeared</fullName>
            </value>
            <value>
                <fullName>Did Not Appear</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>No Service</fullName>
            </value>
            <value>
                <fullName>Other﻿</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/fields/Case_Role__c.field-meta.xml
<CustomField>
    <fullName>Case_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Case Role for Meeting participant</description>
    <inlineHelpText>Help Text Needed</inlineHelpText>
    <label>Case Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Role__c.Case__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Role__c</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Hearing__c</referenceTo>
    <relationshipLabel>Meeting Participants</relationshipLabel>
    <relationshipName>Meeting_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/fields/Meeting_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Start_Date_Time__c</fullName>
    <formula>Meeting__r.Meeting_Start_Date_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Meeting Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Meeting_Participant__c/recordTypes/Conference.recordType-meta.xml
<RecordType>
    <fullName>Conference</fullName>
    <active>true</active>
    <description>Used for Conferences</description>
    <label>Conference</label>
</RecordType>

force-app/main/default/classes/HearingTriggerHandler.cls
public class HearingTriggerHandler{
    public static void updateMeetingParticipants(List<Hearing__c> newList){
        Map<Id,Id> caseIdMap = new Map<Id,Id>();
        Map<Id,String> recordTypeIdMap = new Map<Id,String>();
        for(Hearing__c h : newList){
            caseIdMap.put(h.Case__c, h.id);
            recordTypeIdMap.put(h.id,h.Record_Type_Name__c);
        }
        
        List<Meeting_Participant__c> mps = new List<Meeting_Participant__c>();
        for(DIR_Case__c c : [select id, (select id from Case_Roles__r where Case_Role_Status__c = 'Active') from DIR_Case__c where Id IN :caseIdMap.keySet()]){
            if(c.Case_Roles__r != null){
                for(Case_Role__c cr : c.Case_Roles__r){
                    Meeting_Participant__c mp = new Meeting_Participant__c();
                    if(recordTypeIdMap.get(caseIdMap.get(c.Id)).contains('Conference'))
                       mp.RecordTypeId = Schema.SObjectType.Meeting_Participant__c.getRecordTypeInfosByName().get('Conference').getRecordTypeId(); 
                       mp.Attendance__c = 'Invited';
                       mp.Case__c = c.id;
                       mp.Case_Role__c = cr.id;
                       mp.Meeting__c = caseIdMap.get(c.id);
                       mps.add(mp);
                    
                }
            }
        }
        if(mps.size() > 0){
            insert mps;
        }
    }
    
    public static void sendEmailToDeputy(List<Hearing__c> newList){
        Map<Id,List<Hearing__c>> caseIdMap = new Map<Id,List<Hearing__c>>();
        for(Hearing__c h : newList){
            if(h.Status__c == 'Scheduled' && h.Meeting_Start_Date_Time__c != null && h.Meeting_Type__c != null){
                if(caseIdMap.containsKey(h.Case__c)){
                    List<Hearing__c> hs = caseIdMap.get(h.Case__c);
                    hs.add(h);
                    caseIdMap.put(h.Case__c, hs);
                }else{
                    caseIdMap.put(h.Case__c, new Hearing__c[]{h});
                }
            }
        }
        
        EmailTemplate et = [Select Id, HtmlValue, Body, subject from EmailTemplate where DeveloperName = 'Linked_Case_Meeting_Notification' LIMIT 1];
        
        Map<Id,List<String>> emailsMap = new Map<Id,List<String>>();
        for(DIR_Case__c c : [select id, (select id,Linked_Case__r.Assigned_Deputy_Email__c from Linked_Cases1__r WHERE Linked_Case__r.Assigned_Deputy_Email__c != null) from DIR_Case__c where Id IN :caseIdMap.keySet() AND Assigned_Deputy__r.User__r.Profile.Name = 'RCI User']){
            if(c.Linked_Cases1__r != null){
                List<String> emailList = new List<String>();
                for(Linked_Case__c lc : c.Linked_Cases1__r){
                    emailList.add(lc.Linked_Case__r.Assigned_Deputy_Email__c);
                }
                emailsMap.put(c.id, emailList);
            }
        }
        
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        String baseURL = system.URL.getSalesforceBaseUrl().toExternalForm();
        for(DIR_Case__c c : [select id, Name, Assigned_Deputy__r.User__c, Case_Number__c from DIR_Case__c where Id IN :caseIdMap.keySet() AND Assigned_Deputy__r.User__r.Profile.Name = 'RCI User']){
            if(emailsMap.containsKey(c.id)){
                for(Hearing__c h : caseIdMap.get(c.id)){
                    Messaging.SingleEmailMessage emsg = new Messaging.SingleEmailMessage();
                    emsg.setTemplateId(et.Id);
                    emsg.setToAddresses(emailsMap.get(c.id));
                    emsg.setTargetObjectId(c.Assigned_Deputy__r.User__c);
                    //emsg.setWhatId(h.id);
                    emsg.saveAsActivity = false;
                    String htmlBody = String.isNotBlank(et.htmlValue) ? et.htmlValue : et.Body;
                    htmlBody = htmlBody.replace('{!Hearing__c.Meeting_Type__c}', h.Meeting_Type__c);
                    htmlBody = htmlBody.replace('{!Hearing__c.Meeting_Start_Date_Time__c}', h.Meeting_Start_Date_Time__c.format());
                    htmlBody = htmlBody.replace('{!DIR_Case__c.Case_Number__c}', c.Case_Number__c);
                    htmlBody = htmlBody.replace('{!DIR_Case__c.Name}', c.Name);
                    htmlBody = htmlBody.replace('{!Hearing__c.Link}',  + baseURL + '/' + h.id);
                    htmlBody = htmlBody.replaceAll(']]>','');
                    emsg.setHtmlBody(htmlBody);
                    emsg.setSubject(et.Subject);
                    emails.add(emsg);
                }
            }
        }
        if(emails.size() > 0){
            Messaging.sendEmail(emails);
        }
    }
}