force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Role__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This field maintains the relationship between the Case Role and the Case.  Reparentable.</description>
    <inlineHelpText>This field maintains the relationship between the Case Role and the Case.  Reparentable.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Role</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Case_Role_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Role_Status__c</fullName>
    <description>For requirement 33146; allows users to quickly view the status of related case roles to a given case record.</description>
    <label>Case Role Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>ODA - Defendant</fullName>
            </value>
            <value>
                <fullName>ODA - Plaintiff</fullName>
            </value>
            <value>
                <fullName>ODA by Settlement</fullName>
            </value>
            <value>
                <fullName>Dismissal - Claimant</fullName>
            </value>
            <value>
                <fullName>Dismissal - Deputy</fullName>
            </value>
            <value>
                <fullName>Dismissal - Ineffective service</fullName>
            </value>
            <value>
                <fullName>No Longer Active On Case</fullName>
            </value>
            <value>
                <fullName>De Novo Appeal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Check__c/Check__c.object-meta.xml
<CustomObject>
    <description>Check object for capturing relevant check data</description>
    <label>Check</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Case Managment object</description>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Office_Account__c.field-meta.xml
<CustomField>
    <fullName>Office_Account__c</fullName>
    <description>Lookup to the Office Account object</description>
    <label>Office Account</label>
    <referenceTo>Office_Account__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Secondary Approval Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Void Requested</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
            <value>
                <fullName>Uncleared</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>UWF Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Check_Batch__c/Check_Batch__c.object-meta.xml
<CustomObject>
    <description>Object for associating groups of checks so that they can be approved/voided in batches</description>
    <label>Check Batch</label>
    <nameField>
        <displayFormat>CB-{0}</displayFormat>
        <label>Check Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Check_Batch__c/fields/Office_Account__c.field-meta.xml
<CustomField>
    <fullName>Office_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to the office account for each check batch. Used for approvals.</description>
    <label>Office Account</label>
    <referenceTo>Office_Account__c</referenceTo>
    <relationshipLabel>Check Batches</relationshipLabel>
    <relationshipName>Check_Batches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Check_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that allows a disbursement clerk to indicate whether or not a batch of checks has been successfully printed so that the balances update and the batch closes.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Review Complete</fullName>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
            <value>
                <fullName>Void Requested</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>UWF Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the office that services this case</description>
    <inlineHelpText>Defines the office that will process this case.</inlineHelpText>
    <label>DIR Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Courthouse</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to the DIR Employee object creating a hierarchial relationship between an employee and his or her manager. Used in code to modify the role hierarchy and dynamically build teams</description>
    <inlineHelpText>Select the employee&#39;s manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Manages these Employees</relationshipLabel>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The office the user is associated to. Related fields are used on output documents</description>
    <inlineHelpText>The office to which the employee is associated.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Internal Employees</relationshipLabel>
    <relationshipName>Internal_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <description>Holds internal office location information</description>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/Office_Account__c.field-meta.xml
<CustomField>
    <fullName>Office_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office Account</label>
    <referenceTo>Office_Account__c</referenceTo>
    <relationshipLabel>Offices</relationshipLabel>
    <relationshipName>Offices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office_Account__c/Office_Account__c.object-meta.xml
<CustomObject>
    <description>This object allows a cashier to view the details associated to a deposit into and office account so that they can monitor the historical transactions associated with a deposit account.</description>
    <label>Office Account</label>
    <nameField>
        <label>Office Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Account__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Office Accounts</relationshipLabel>
    <relationshipName>Office_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <description>Used to capture data for Payee information related to a case and liability</description>
    <label>Payee</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payee__c/fields/Case_Role__c.field-meta.xml
<CustomField>
    <fullName>Case_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the claimant of a Case. Filtered to only return case roles that are in the Case Management record.</description>
    <label>Case Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Role__c.Case__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case_Management__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Role__c</referenceTo>
    <relationshipLabel>Payees</relationshipLabel>
    <relationshipName>Payees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DisplayCheckRecordsControllerTest.cls
@isTest 
public class DisplayCheckRecordsControllerTest 
{
    static testMethod void testMethod1() 
    {
        Test.StartTest(); 
        
        pageReference displayCheckRecords= Page.DisplayCheckRecords;
        
        Test.setCurrentPage(displayCheckRecords);
        
        Account a = new Account(
            Name = 'Test Account'
        );
        insert a;
         
        DIR_Employee__c employeeMgr = new DIR_Employee__c(
            User__c = UserInfo.getUserId()
        );
        insert employeeMgr;
        
        DIR_Employee__c employee = new DIR_Employee__c(
            User__c = UserInfo.getUserId(),
            Manager__c = employeeMgr.Id
        );
        insert employee;
     
        Office__c office = new Office__c(
            Name = 'test office'
        );
        insert office;
        
        Office_Account__c officeAccount = new Office_Account__c(
            Name = 'test office account',
            Office__c = office.id
        );
        insert officeAccount;
        
        DIR_Case__c caseMgmt = new DIR_Case__c(
            Employer__c = a.Id,
            Assigned_Deputy__c = employee.Id
        );
        insert caseMgmt;
        
        Case_Role__c caseRole = new Case_Role__c(
            Case_Role_Status__c = 'Active',
            Case__c = caseMgmt.Id,
            IsPersonAccount__c = false,
            Entity__c = a.Id
        );
        insert caseRole;
        
        Payee__c payee = new Payee__c(
            Case_Management__c = caseMgmt.Id,
            Case_Role__c = caseRole.Id,
            Factor__c = 100,
            Payee_Type__c = 'Employee',
            Status__c = 'Unverified'
        );
        insert payee;
        
        Check_Batch__c cb = new Check_Batch__c(
        Requesting_Cashier__c = employee.id,
        Office_Account__c= officeAccount.id
        );
        insert cb;
        
        Check__c cl= new Check__c(
        Check_Number__c ='58787',
        Check_Batch__c = cb.id,
        Office_Account__c = officeAccount.id,
        Status_Date__c = Date.today(),
        Status__c = 'Approved'
        );
        insert cl;
        
        Check__c cl2= new Check__c(
        Check_Number__c ='87878',
        Check_Batch__c = cb.id,
        Office_Account__c = officeAccount.id,
        Status_Date__c = Date.today(),
        Status__c = 'Not Approved'
        );
        insert cl2;
           
        
        DisplayCheckRecordsController testAccPlan = new DisplayCheckRecordsController();
        testAccPlan.runMethod(); 
        testAccPlan.DisplayCheckRecordsController();
        system.assertEquals(testAccPlan.today,Date.today());
        Test.StopTest();
    }
    
    }