force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check__c/Check__c.object-meta.xml
<CustomObject>
    <description>Check object for capturing relevant check data</description>
    <label>Check</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Care_Of__c.field-meta.xml
<CustomField>
    <fullName>Care_Of__c</fullName>
    <description>To add a memo line to the checks issued</description>
    <label>C/O</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Case Managment object</description>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Check_Batch__c.field-meta.xml
<CustomField>
    <fullName>Check_Batch__c</fullName>
    <label>Check Batch</label>
    <referenceTo>Check_Batch__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Office_Account__c.field-meta.xml
<CustomField>
    <fullName>Office_Account__c</fullName>
    <description>Lookup to the Office Account object</description>
    <label>Office Account</label>
    <referenceTo>Office_Account__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Payee to whom the check is written</inlineHelpText>
    <label>Payee</label>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Payee_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_Name__c</fullName>
    <formula>Payee__r.Case_Role__r.Case_Role_Account_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Payment_Full_or_Partial__c.field-meta.xml
<CustomField>
    <fullName>Payment_Full_or_Partial__c</fullName>
    <label>Payment: Full or Partial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Check__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Secondary Approval Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Void Requested</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
            <value>
                <fullName>Uncleared</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>UWF Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Check_Batch__c/Check_Batch__c.object-meta.xml
<CustomObject>
    <description>Object for associating groups of checks so that they can be approved/voided in batches</description>
    <label>Check Batch</label>
    <nameField>
        <displayFormat>CB-{0}</displayFormat>
        <label>Check Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Check_Batch__c/fields/Office_Account__c.field-meta.xml
<CustomField>
    <fullName>Office_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to the office account for each check batch. Used for approvals.</description>
    <label>Office Account</label>
    <referenceTo>Office_Account__c</referenceTo>
    <relationshipLabel>Check Batches</relationshipLabel>
    <relationshipName>Check_Batches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Check_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that allows a disbursement clerk to indicate whether or not a batch of checks has been successfully printed so that the balances update and the batch closes.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Review Complete</fullName>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
            <value>
                <fullName>Void Requested</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>UWF Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Case Number</description>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>BOFE Stay</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>No Citation or Other Issues</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Unable to Pursue</fullName>
            </value>
            <value>
                <fullName>Returned to Claimant</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Waiting for Litigation</fullName>
            </value>
            <value>
                <fullName>New AutoRefer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office_Account__c/Office_Account__c.object-meta.xml
<CustomObject>
    <description>This object allows a cashier to view the details associated to a deposit into and office account so that they can monitor the historical transactions associated with a deposit account.</description>
    <label>Office Account</label>
    <nameField>
        <label>Office Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <description>Used to capture data for Payee information related to a case and liability</description>
    <label>Payee</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payee__c/fields/Case_Role__c.field-meta.xml
<CustomField>
    <fullName>Case_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the claimant of a Case. Filtered to only return case roles that are in the Case Management record.</description>
    <label>Case Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Role__c.Case__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case_Management__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Role__c</referenceTo>
    <relationshipLabel>Payees</relationshipLabel>
    <relationshipName>Payees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payee__c/fields/Payee_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_Name__c</fullName>
    <description>Pulls the name of the payee through from the associated case role for display on list views, reports, etc</description>
    <formula>IF(Payee_Heir_or_Successor__c = TRUE , Name_of_Heir_or_Successor__c 
&amp;&#39;, Heir or Successor of &#39;&amp;Case_Role__r.Account_Name__c 
&amp;&#39;, Deceased.&#39;, Case_Role__r.Account_Name__c)</formula>
    <label>Payee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the payee record</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unverified</fullName>
            </value>
            <value>
                <fullName>Incomplete-2nd Request</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Undeliverable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisplayCheckRecordsController.cls
/**
 * Class: DisplayCheckRecordsController.cls
 * Developer: Marian Iovi (marian.iovi@vertiba.com)
 * Created: Octomber 12, 2016
 * Modified: -
 * Objective This class provides methods for DisplayCheckRecords.page
 *
 *
 **/ 
public class DisplayCheckRecordsController {
    
    public String checkBatchId {get;set;}
    public Integer count {get;set;}
    public Decimal csscount {get;set;}
    public List<Check__c> chkList {get;set;}
    public Date today {
                        set;
                        get{ return Date.today();}
                        }

    public void DisplayCheckRecordsController(){}

    public void runMethod(){
        checkBatchId = ApexPages.currentPage().getParameters().get('Id'); 
        System.debug('checkBatchId');

        chkList = [Select Id, Amount__c, Check_Number__c, Case__r.Case_Number__c, Case__r.Employer__r.Name, Office_Account__r.Name, 
                                Payee__r.Case_Role__r.Account_Name__c, Payee__r.Case_Role__r.Entity__r.ShippingStreet, Payee__r.Case_Role__r.Entity__r.ShippingCity, 
                                Payee__r.Case_Role__r.Entity__r.ShippingState, Payee__r.Case_Role__r.Entity__r.ShippingPostalCode, Payee__r.Payee_Name__c, Care_Of__c, Payment_Full_or_Partial__c
                                    FROM Check__c WHERE Check_Batch__c =: checkBatchId AND Status__c = 'Approved'];
                                    
       count= database.countQuery('select count() FROM Check__c WHERE Check_Batch__c =: checkBatchId');
       csscount=count * 3.5;
      

    }
}